export const agents = [
  {
    email: "contact@philix",
    phone: "08108850572",
    isApproved: true,
    name: "Philix",
    lga: "Arugungu",
    statecode: "KEBBI",
    img: "images/profile2.jpg",
    userStatus: "LG-AGENT",
  },
  {
    email: "philixbob@gmail.com",
    phone: "09030099092",
    isApproved: false,
    name: "Iyanu",
    lga: "Brinin-Kebbi",
    statecode: "KEBBI",
    img: "images/profile2.jpg",
    userStatus: "LG-AGENT",
  },
  {
    email: "kabri@gmail.com",
    phone: "08108850572",
    isApproved: true,
    name: "Kabri",
    lga: "Jega",
    statecode: "KEBBI",
    img: "images/profile.jpeg",
    userStatus: "LG-AGENT",
  },
  {
    email: "ochuko@gmail.com",
    phone: "08108850572",
    isApproved: false,
    name: "Ochuko",
    lga: "Arugungu",
    statecode: "KEBBI",
    img: "images/profile2.jpg",
    userStatus: "LG-AGENT",
  },
  {
    email: "mustapha@gmail.com",
    phone: "08108850572",
    isApproved: true,
    name: "Mustapha",
    lga: "Yawuri",
    statecode: "KEBBI",
    img: "images/profile.jpeg",
    userStatus: "LG-AGENT",
  },
];
