export const banks = [
  "9 Payment Service Bank (9PSB)",
  "Abbey Mortgage Bank",
  "Access Bank",
  "Access Bank PLC (Diamond)",
  "ACCION MFB",
  "Aku MFB",
  "Baines Credit MFB",
  "Bowen MFB",
  "Carbon",
  "Cellulant",
  "Changan RTS Microfinance Bank",
  "Citi Bank",
  "Contec Global",
  "CoreStep MicroFinance Bank",
  "Coronation",
  "e-BARCs MFB",
  "Ecobank Bank",
  "Ecobank Xpress Account",
  "Ekondo MFB",
  "EYOWO",
  "FairMoney MFB",
  "FCMB",
  "FFS Microfinance Bank",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "FSDH Merchant Bank",
  "Globus Bank",
  "GoMoney",
  "Goodnews MFB",
  "GTBank PIc",
  "Heritage",
  "JAIZ Bank",
  "JubileeLife",
  "KCMB MFB",
  "KEGOW (ChamsMobile)",
  "Keystone Bank",
  "Kredimoney Microfinance Bank",
  "Kuda MFB",
  "Living Trust Morgage Bank Plc",
  "Lotus Bank",
  "Mainstreet MFB",
  "Manny Microfinance bank",
  "Mint-Finex MFB",
  "Moniepoint",
  "Opay Digital Services Limited",
  "Paga",
  "PALMPAY",
  "Parkway-ReadyCash",
  "Parallex Bank",
  "Patrickgold Microfinance Bank",
  "PayAttitude Online",
  "POLARIS BANK",
  "Premium Trust Bank",
  "Providus Bank",
  "Rand Merchant Bank",
  "Rubies",
  "Safe Haven MFB",
  "Seedvest Microfinance Bank",
  "Sparkle MFB",
  "Spectrum MFB",
  "Stanbic IBTC Bank",
  "StanbicMobileMoney",
  "Standard Chartered",
  "Stellas Bank",
  "Sterling Bank",
  "SUNTRUST BANK",
  "TAJ Bank",
  "Tanadi MFB (CRUST)",
  "Tangerine Money",
  "Titan Paystack",
  "Titan Trust Bank",
  "Union Bank",
  "United Bank for Africa",
  "Unity Bank",
  "Uzondu Microfinance Bank",
  "VFD MFB",
  "Wema Bank",
  "ZENITH BANK PLC",
  "Zinternet - KongaPay",
];
