const SR = {
  name: "ADAMAWA",
  email: "Adamawa@apcaims.com",
  password: "adamawa_&bw",
  phone: "08108850572",
  statecode: "ADAMAWA",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "ADAMAWA",
  state: "ADAMAWA",
  lga: [
    {
      wards: [
        "BILLE",
        "BORRONG",
        "DEMSA",
        "DILLI",
        "DONG",
        "DWAM",
        "GWAMBA",
        "KPASHAM",
        "MBULA KULI",
        "NASSARAWO DEMSA",
      ],
      name: "Demsa",
    },
    {
      wards: [
        "BETI",
        "FARANG",
        "FUFORE",
        "GURIN",
        "KARLAHI",
        "MAYO INE",
        "PARIYA",
        "RIBADU",
        "UKI TUKI",
        "WURO BOKKI",
        "YADIM",
      ],
      name: "Fufure",
    },
    {
      wards: [
        "BAKARI GUSO",
        "GAMU",
        "GANYE I",
        "GANYE II",
        "GURUM",
        "JAGGU",
        "SANGASUMI",
        "SUGU",
        "TIMDORE",
        "YEBBI",
      ],
      name: "Ganye",
    },
    {
      wards: [
        "BANJIRAM",
        "BOBINI",
        "BODENO",
        "CHIKILA",
        "DUKUL",
        "DUMNA",
        "GUYUK",
        "KOLA",
        "LOKORO",
        "PUROKAYO",
      ],
      name: "Gayuk",
    },
    {
      wards: [
        "DAKRI",
        "DAMARE",
        "GEREI I",
        "GERENG",
        "GIREI II",
        "JERA BAKARI",
        "JERA BONYO",
        "MODIRE/ VINIKILANG",
        "TAMBO",
        "WURO DOLE",
      ],
      name: "Girei",
    },
    {
      wards: [
        "BOGA/ DINGAI",
        "DUWA",
        "GA'ANDA",
        "GABUN",
        "GARKIDA",
        "GOMBI NORTH",
        "GOMBI SOUTH",
        "GUYAKU",
        "TAWA",
        "YANG",
      ],
      name: "Gombi",
    },
    {
      wards: [
        "BANGSHIKA",
        "DAKSIRI",
        "GARAHA",
        "GAYA",
        "HILDI",
        "HONG",
        "HUSHERE ZUM",
        "KWARHI",
        "MAYO LOPE",
        "SHANGUI",
        "THILBANG",
        "UBA",
      ],
      name: "Hong",
    },
    {
      wards: [
        "DANABA",
        "JADA I",
        "JADA II",
        "KOMA I",
        "KOMA II",
        "LEKO",
        "MAPEO",
        "MAYOKALAYE",
        "MBULO",
        "NYIBANGO",
        "YELLI",
      ],
      name: "Jada",
    },
    {
      wards: [
        "DUBWANGUN",
        "GYAWANA",
        "LAFIYA",
        "LAMURDE",
        "MGBEBONGUN",
        "NGBAKOWO",
        "OPALO",
        "RIGANGE",
        "SUWA",
        "WADUKU",
      ],
      name: "Lamurde",
    },
    {
      wards: [
        "BABEL",
        "DUHU/ SHUWA",
        "GULAK",
        "HYAMBULA",
        "K/WURO NGAYANDI",
        "MADAGALI",
        "PALLAM",
        "SHELMI / SUKUR/ VAPURA",
        "WAGGA",
        "WULA",
      ],
      name: "Madagali",
    },
    {
      wards: [
        "BELEL",
        "HUMBUTUDI",
        "KONKOL",
        "MAIHA GARI",
        "MANJEKIN",
        "MAYONGULI",
        "PAKKA",
        "SORAU 'A'",
        "SORAU 'B'",
        "TAMBAJAM",
      ],
      name: "Maiha",
    },
    {
      wards: [
        "BAJAMA",
        "BINYERI",
        "GANGFADA",
        "GENGLE",
        "GOROBI",
        "MAYO FARANG",
        "MAYO-BELWA",
        "NASSARAWO JERENG",
        "NDIKONG",
        "RIBADU",
        "TOLA",
        "YOFFO",
      ],
      name: "Mayo Belwa",
    },
    {
      wards: [
        "BAZZA MARGI",
        "FUTUDOU / FUTULES",
        "GARTA / GHUNCHI",
        "JIGALAMBU",
        "MADZI",
        "MICHIKA I",
        "MICHIKA II",
        "MINKISI/ WURO NGIKI",
        "MODA / DLAKA / GHENJUWA",
        "MUNKAVICITA",
        "SINA / KAMALE / KWANDE",
        "SUKUMU / TILLIJO",
        "THUKUDOU / SUFUKU / ZAH",
        "TUMBARA / NGABILI",
        "VI / BOKA",
        "WAMBLIMI / TILLI",
      ],
      name: "Michika",
    },
    {
      wards: [
        "BAHULI",
        "BETSO",
        "DIGIL",
        "KOLERE",
        "LOKUWA",
        "MAYO BANI",
        "MIJILU",
        "MUCHALLA",
        "SABON LAYI",
        "VIMTIM",
        "YELWA",
      ],
      name: "Mubi North",
    },
    {
      wards: [
        "DIRBISHI/GANDIRA",
        "DUVU/ CHABA/ GIRBURUM",
        "GELLA",
        "GUDE",
        "KWAJA",
        "LAMORDE",
        "MUGULBU/ YADAFA",
        "MUJARA",
        "NASSARAWO",
        "NDUKU",
      ],
      name: "Mubi South",
    },
    {
      wards: [
        "BARE",
        "BOLKI",
        "GAMADIO",
        "IMBURU",
        "KODOMTI",
        "NUMAN I",
        "NUMAN II",
        "NUMAN III",
        "SABON PEGI",
        "VULPI",
      ],
      name: "Numan",
    },
    {
      wards: [
        "BAKTA",
        "BODWAI",
        "GUNDO",
        "GWAPOPOLOK",
        "JUMBUL",
        "KETEMBERE",
        "KIRI",
        "LIBBO",
        "SHELLENG",
        "TALLUMBAKTA",
        "BODWAI",
        "GUNDO",
        "GWAPOPOLOK",
        "JUMBUL",
        "KETEMBERE",
        "KIRI",
        "LIBBO",
        "SHELLENG",
        "TALLUM",
      ],
      name: "Shelleng",
    },
    {
      wards: [
        "DIRMA",
        "DUMNE",
        "GUDU MBOI",
        "KILANGE FUNA",
        "KILANGE HIRNA",
        "SIGIRE",
        "SONG GARI",
        "SONG WAJE",
        "SUKTU",
        "WALTANDI",
        "ZUMO",
      ],
      name: "Song",
    },
    {
      wards: [
        "DAWO I",
        "DAWO II",
        "GUMTI",
        "KIRI I",
        "KIRI II",
        "KONGIN BABA I",
        "KONGIN BABA II",
        "TOUNGO I",
        "TOUNGO II",
        "TOUNGO III",
      ],
      name: "Toungo",
    },
    {
      wards: [
        "AJIYA",
        "ALKALAWA",
        "DOUBELI",
        "GWADABAWA",
        "JAMBUTU",
        "KARENA",
        "LIMAWA",
        "LUGGERE",
        "NASSARAWO",
        "RUMDE",
        "YELWA",
      ],
      name: "Yola North",
    },
    {
      wards: [
        "ADARAWO",
        "BAKO",
        "BOLE YOLDE PATE",
        "MAKAMA 'A'",
        "MAKAMA 'B'",
        "MBAMBA",
        "MBAMOI",
        "NAMTARI",
        "NGURORE",
        "TOUNGO",
        "YOLDE KOHI",
      ],
      name: "Yola South",
    },
  ],
};

export const ADAMAWA = { states, SR };
