const SR = {
  name: "AKWA IBOM",
  email: "Akwaibom@apcaims.com",
  password: "akwaibom_bnb",
  phone: "08108850572",
  statecode: "AKWAIBOM",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "AKWAIBOM",
  state: "AKWA IBOM",
  lga: [
    {
      wards: [
        "ABAK URBAN I",
        "ABAK URBAN II",
        "ABAK URBAN III",
        "ABAK URBAN IV",
        "AFAHA OBONG I",
        "AFAHA OBONG II",
        "MIDIM I",
        "MIDIM II",
        "OTORO I",
        "OTORO II",
        "OTORO III",
      ],
      name: "ABAK",
    },
    {
      wards: [
        "EASTERN OBOLO 1",
        "EASTERN OBOLO 11",
        "EASTERN OBOLO 111",
        "EASTERN OBOLO 1V",
        "EASTERN OBOLO IX",
        "EASTERN OBOLO V",
        "EASTERN OBOLO V1",
        "EASTERN OBOLO V11",
        "EASTERN OBOLO V111",
        "EASTERN OBOLO X",
      ],
      name: "EASTERN OBOLO",
    },
    {
      wards: [
        "CENTRAL I",
        "CENTRAL II",
        "CENTRAL III",
        "CENTRAL IV",
        "CENTRAL V",
        "OKON 1",
        "OKON 11",
        "URBAN 1",
        "URBAN 11",
        "URBAN 111",
        "URBAN 1V",
      ],
      name: "EKET",
    },
    {
      wards: [
        "AKPAUTONG",
        "EBE EKPI",
        "EBIGHI OKPONO",
        "EDOR",
        "EKPENE OBO",
        "ETEBI AKWATA",
        "ETEBI IDUNG ASSAN",
        "IKPA",
        "NTAK INYANG",
        "UQUO",
      ],
      name: "ESIT EKET (UQUO)",
    },
    {
      wards: [
        "ADIASIM",
        "AFAHA",
        "EKPEYONG 1",
        "EKPEYONG 11",
        "IKPE ANNANG",
        "ODORO IKOT 1",
        "ODORO IKOT 11",
        "OKON",
        "UKANA EAST",
        "UKANA WEST 1",
        "UKANA WEST 11",
      ],
      name: "ESSIEN UDIM",
    },
    {
      wards: [
        "ETIM EKPO 1",
        "ETIM EKPO 11",
        "ETIM EKPO 111",
        "ETIM EKPO 1V",
        "ETIM EKPO IX",
        "ETIM EKPO V",
        "ETIM EKPO V1",
        "ETIM EKPO V11",
        "ETIM EKPO V111",
        "ETIM EKPO X",
      ],
      name: "ETIM EKPO",
    },
    {
      wards: [
        "ETINAN URBAN 1",
        "ETINAN URBAN 11",
        "ETINAN URBAN 111",
        "ETINAN URBAN 1V",
        "ETINAN URBAN V",
        "NORTHERN IMAN 1",
        "NORTHERN IMAN 11",
        "SOUTHERN IMAN 1",
        "SOUTHERN IMAN 11",
        "SOUTHERN IMAN 111",
        "SOUTHERN IMAN 1V",
      ],
      name: "ETINAN",
    },
    {
      wards: [
        "IBENO 1",
        "IBENO 11",
        "IBENO 111",
        "IBENO 1V",
        "IBENO IX",
        "IBENO V",
        "IBENO V11",
        "IBENO V111",
        "IBENO VI",
        "IBENO X",
      ],
      name: "IBENO",
    },
    {
      wards: [
        "ASUTAN 1",
        "ASUTAN 11",
        "ASUTAN 111",
        "ASUTAN IV",
        "ASUTAN V",
        "IBESIKPO 1",
        "IBESIKPO 11",
        "IBESIKPO 111",
        "IBESIKPO 1V",
        "IBESIKPO V",
      ],
      name: "IBESIKPO ASUTAN",
    },
    {
      wards: [
        "IBIONO CENTRAL 1",
        "IBIONO CENTRAL 11",
        "IBIONO EASTERN 1",
        "IBIONO EASTERN 11",
        "IBIONO NORTHERN 1",
        "IBIONO NORTHERN 11",
        "IBIONO SOUTHERN 1",
        "IBIONO SOUTHERN 11",
        "IBIONO WESTERN 1",
        "IBIONO WESTERN 11",
        "IKPANYA",
      ],
      name: "IBIONO IBOM",
    },
    {
      wards: [
        "ACHAN 11",
        "ACHAN 111",
        "ACHAN IKA",
        "ITO 1",
        "ITO 11",
        "ITO 111",
        "ODORO 1",
        "ODORO 11",
        "URBAN 1",
        "URBAN 11",
      ],
      name: "IKA",
    },
    {
      wards: [
        "1TAK",
        "EDIENE 1",
        "EDIENE 11",
        "IKONO MIDDLE 1",
        "IKONO MIDDLE 11",
        "IKONO MIDDLE 111",
        "IKONO MIDDLE 1V",
        "IKONO SOUTH",
        "NDIYA/IKOT IDANA",
        "NKWOT 1",
        "NKWOT 11",
      ],
      name: "IKONO",
    },
    {
      wards: [
        "EDEMAYA 1",
        "EDEMAYA 11",
        "EDEMAYA 111",
        "IKPA IBEKWE 1",
        "IKPA IBEKWE 11",
        "IKPA NUNG ASANG 1",
        "IKPA NUNG ASANG 11",
        "UKPUM ETE 1",
        "UKPUM ETE 11",
        "UKPUM OKON",
      ],
      name: "IKOT ABASI",
    },
    {
      wards: [
        "IKOT EKPENE 1",
        "IKOT EKPENE 11",
        "IKOT EKPENE 111",
        "IKOT EKPENE 1V",
        "IKOT EKPENE IX",
        "IKOT EKPENE V",
        "IKOT EKPENE V1",
        "IKOT EKPENE V11",
        "IKOT EKPENE V111",
        "IKOT EKPENE X",
        "IKOT EKPENE X1",
      ],
      name: "IKOT EKPENE",
    },
    {
      wards: [
        "IKONO NORTH 1",
        "IKONO NORTH 11",
        "IKONO NORTH 111",
        "IKPE 1",
        "IKPE 11",
        "ITU MBONUSO",
        "IWERRE",
        "NKARI",
        "ODORO UKWOK",
        "USUK UKWOK",
      ],
      name: "INI",
    },
    {
      wards: [
        "EAST ITAM 1",
        "EAST ITAM 11",
        "EAST ITAM 111",
        "EAST ITAM 1V",
        "EAST ITAM V",
        "MBIASE/AYADEHE",
        "OKU IBOKU",
        "WEST ITAM 1",
        "WEST ITAM 11",
        "WEST ITAM 111",
      ],
      name: "ITU",
    },
    {
      wards: [
        "EBUGHU 1",
        "EBUGHU 11",
        "EFIAT 1",
        "EFIAT 11",
        "ENWANG 1",
        "ENWANG 11",
        "IBAKA",
        "UDA 1",
        "UDA 11",
        "UDESI",
      ],
      name: "MBO",
    },
    {
      wards: [
        "IBIAKU 1",
        "IBIAKU 11",
        "IBIAKU 111",
        "IKPA IBOM 1",
        "IKPA IBOM 11",
        "IKPA IBOM 111",
        "IKPA IBOM 1V",
        "IKPA IKONO 1",
        "IKPA IKONO 11",
        "IKPA IKONO 111",
        "UKPUM MINYA 1",
        "UKPUM MINYA 11",
        "UKPUM MINYA 111",
        "UKPUM MINYA 1V",
      ],
      name: "MKPAT ENIN",
    },
    {
      wards: [
        "EASTERN NSIT 1",
        "EASTERN NSIT 11",
        "EASTERN NSIT 111",
        "EASTERN NSIT 1V",
        "EASTERN NSIT IX",
        "EASTERN NSIT V",
        "EASTERN NSIT V1",
        "EASTERN NSIT V11",
        "EASTERN NSIT V111",
        "EASTERN NSIT X",
      ],
      name: "NSIT ATAI",
    },
    {
      wards: [
        "ASANG 1",
        "ASANG 11",
        "ASANG 111",
        "ASANG 1V",
        "ASANG V",
        "MBAISO 1",
        "MBAISO 11",
        "MBAISO 111",
        "MBAISO 1V",
        "MBAISO V",
      ],
      name: "NSIT IBOM",
    },
    {
      wards: [
        "IBIAKPAN OBOTIM 1",
        "IBIAKPAN/OBOTIM 11",
        "ITRETO",
        "NDIYA",
        "UBIUM NORTH 1",
        "UBIUM NORTH 11",
        "UBIUM NORTH 111",
        "UBIUM SOUTH 1",
        "UBIUM SOUTH 11",
        "UBIUM SOUTH 111",
      ],
      name: "NSIT UBIUM",
    },
    {
      wards: [
        "IKOT ABIA 1",
        "IKOT ABIA 11",
        "IKOT ABIA 111",
        "NTO EDINO 1",
        "NTO EDINO 11",
        "NTO EDINO 111",
        "NTO EDINO 1V",
        "OBOT AKARA 1",
        "OBOT AKARA 11",
        "OBOT AKARA 111",
      ],
      name: "OBOT AKARA",
    },
    {
      wards: [
        "AKAI/MBUKPO/UDUNG",
        "EKEYA",
        "EWEME 1",
        "EWEME 11",
        "NUNG ATAI/UBE 1",
        "NUNG ATAI/UBE 11",
        "OFFI 1",
        "OFFI 11",
        "OKOPEDI 1",
        "OKOPEDI 11",
      ],
      name: "OKOBO",
    },
    {
      wards: [
        "AWA 1",
        "AWA 11",
        "AWA 111",
        "AWA 1V",
        "NUNG IDEM 1",
        "NUNG IDEM 11",
        "ONIONG EAST 1",
        "ONIONG EAST 11",
        "ONIONG EAST 111",
        "ONIONG WEST 1",
        "ONIONG WEST 11",
        "ONIONG WEST 111",
      ],
      name: "ONNA",
    },
    {
      wards: [
        "ORON URBAN IX",
        "ORON URBAN X",
        "ORON URBAN 1",
        "ORON URBAN 11",
        "ORON URBAN 111",
        "ORON URBAN 1V",
        "ORON URBAN V",
        "ORON URBAN V1",
        "ORON URBAN V11",
        "ORON URBAN V111",
      ],
      name: "ORON",
    },
    {
      wards: [
        "ABAK MIDIM 1",
        "ABAK MIDIM 11",
        "ABAK MIDIM 111",
        "ABAK MIDIM 1V",
        "EKPARAKWA",
        "IBESIT/NUNG IKOT 1",
        "IBESIT/NUNG IKOT 11",
        "IKOT IBRITAM 1",
        "IKOT IBRITAM 11",
        "NDOT/IKOT OKORO 1",
        "NDOT/IKOT OKORO 11",
        "NDOT/IKOT OKORO 111",
        "NDOT/IKOT OKORO V1",
      ],
      name: "ORUK ANAM",
    },
    {
      wards: [
        "UDUNG UKO 1",
        "UDUNG UKO 11",
        "UDUNG UKO 111",
        "UDUNG UKO 1V",
        "UDUNG UKO IX",
        "UDUNG UKO V",
        "UDUNG UKO V1",
        "UDUNG UKO V11",
        "UDUNG UKO V111",
        "UDUNG UKO X",
      ],
      name: "UDUNG UKO",
    },
    {
      wards: [
        "NORTHERN AFAHA 1",
        "NORTHERN AFAHA 11",
        "NORTHERN UKANAFUN 1",
        "NORTHERN UKANAFUN 11",
        "SOUTHERN AFAHA, ADAT IFANG 1",
        "SOUTHERN AFAHA, ADAT IFANG 11",
        "SOUTHERN AFAHA, ADAT IFANG 111",
        "SOUTHERN AFAHA, ADAT IFANG 1V",
        "SOUTHERN UKANAFUN 1",
        "SOUTHERN UKANAFUN 11",
        "UKANAFUN URBAN",
      ],
      name: "UKANAFUN",
    },
    {
      wards: [
        "CENTRAL URUAN 11",
        "CENTYRAL URUAN 1",
        "CENTYRAL URUAN 111",
        "NORTHERN URUAN 1",
        "NORTHERN URUAN 11",
        "SOUTHERN URUAN 1",
        "SOUTHERN URUAN 11",
        "SOUTHERN URUAN 111",
        "SOUTHERN URUAN IV",
        "SOUTHERN URUAN V",
        "SOUTHERN URUAN V1",
      ],
      name: "URUAN",
    },
    {
      wards: [
        "ORUKO 1",
        "ORUKO 11",
        "ORUKO 111",
        "ORUKO 1V",
        "ORUKO V",
        "URUE OFFONG 1",
        "URUE OFFONG 11",
        "URUE OFFONG 111",
        "URUE OFFONG 1V",
        "URUE OFFONG V",
      ],
      name: "URUE OFFONG ORUKO",
    },
    {
      wards: [
        "ETOI 1",
        "ETOI 11",
        "IKONO 1",
        "IKONO 11",
        "OFFOT 1",
        "OFFOT 11",
        "OKU 1",
        "OKU 11",
        "UYO URBAN 1",
        "UYO URBAN 11",
        "UYO URBAN 111",
      ],
      name: "UYO",
    },
  ],
};

export const AKWAIBOM = { states, SR };
