const SR = {
  name: "BAUCHI",
  email: "Bauchi@apcaims.com",
  password: "bauchi_94d",
  phone: "08108850572",
  statecode: "BAUCHI",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  state: "BAUCHI",
  statecode: "BAUCHI",
  lga: [
    {
      wards: [
        "ALKALERI",
        "BIRIN/ GIGARA/ YANKARI",
        "DAN KUNGIBAR",
        "FUTUK",
        "GAR",
        "GWANA / MANSUR",
        "GWARAM",
        "MAIMADI",
        "PALI",
        "YALO",
        "YULI/ LIM",
      ],
      name: "ALKALERI",
    },
    {
      wards: [
        "B O I 'A'",
        "B O I 'B'",
        "B O I 'C'",
        "BOGORO 'A'",
        "BOGORO 'B'",
        "BOGORO 'C'",
        "BOGORO 'D'",
        "LUSA  'A'",
        "LUSA  'B'",
        "LUSA  'C'",
      ],
      name: "BOGORO",
    },
    {
      wards: [
        "BIRSHI/MIRI",
        "DANDANGO/YAMRAT",
        "DAN'IYA HARDO",
        "DAWAKI",
        "GALAMBI/GWASKWARAM",
        "KANGYARE/TURWUN",
        "KUNDUM/DURUM",
        "MAJIDADI 'A'",
        "MAJIDADI 'B'",
        "MAKAMA/SARKI BAKI",
        "MUN/MUNSAL",
        "ZUNGUR/LIMAN  KATAGUM",
      ],
      name: "BAUCHI",
    },
    {
      wards: [
        "DAGAUDA",
        "DAMBAM",
        "GARGAWA",
        "GARUZA",
        "GURBANA",
        "JALAM CENTRAL",
        "JALAM EAST",
        "YAME",
        "YANDA",
        "ZAURA",
      ],
      name: "DAMBAM",
    },
    {
      wards: [
        "DARAZO",
        "GABARIN",
        "GABCIYARI",
        "KONKIYAL",
        "LAGO",
        "LANZAI",
        "PAPA",
        "SADE",
        "TAUYA",
        "WAHU",
        "YAUTARE",
      ],
      name: "DARAZO",
    },
    {
      wards: [
        "BAGEL/BAJAR",
        "BARAZA",
        "BUNDOT",
        "BUNUNU CENTRAL",
        "BUNUNU SOUTH",
        "DOTT",
        "DURR",
        "POLCHI",
        "WANDI",
        "ZUMBUL/LUKSHI",
      ],
      name: "DASS",
    },
    {
      wards: [
        "ALAGARNO/JADORI",
        "GADIYA",
        "GAMAWA",
        "GOLOLO",
        "KAFIN  ROMI",
        "KUBDIYA",
        "RAGA",
        "TARMASUWA",
        "TUMBI",
        "UDUBO",
      ],
      name: "GAMAWA",
    },
    {
      wards: [
        "ZINDI",
        "Ganjuwa",
        "Gungura",
        "KAFIN MADAKI",
        "KARIYA",
        "Kubi East",
        "Kubi West",
        "MIYA  EAST",
        "MIYA  WEST",
        "NASARAWA SOUTH",
        "NASARAWA NORTH",
        "YALI",
      ],
      name: "GANJUWA",
    },
    {
      wards: [
        "CHINKANI",
        "DOGUWA  SOUTH",
        "DOGUWA CENTRAL",
        "GIADE",
        "ISAWA",
        "SABON SARA",
        "U.  ZUM 'A'",
        "UZUM 'B'",
        "ZABI",
        "ZIRRAMI",
      ],
      name: "GIADE",
    },
    {
      wards: [
        "ABDALLAWA/MAGARYA",
        "BAMBAL",
        "BILKICHERI",
        "BUZAWA",
        "GADAU",
        "GWARAI",
        "ITAS",
        "KASHURI",
        "MASHEMA",
        "ZUBUKI",
      ],
      name: "ITAS/GADAU",
    },
    {
      wards: [
        "DOGON JEJI 'A'",
        "DOGON JEJI 'B'",
        "DOGON JEJI 'C'",
        "GALDIMARI",
        "HANAFARI",
        "JAMA'ARE 'A'",
        "JAMA'ARE 'B'",
        "JAMA'ARE 'C'",
        "JAMA'ARE 'D'",
        "JURARA",
      ],
      name: "JAMA'ARE",
    },
    {
      wards: [
        "BULKACHUWA/DAGARO",
        "BUSKURI",
        "CHINADE",
        "GAMBAKI/BIDIR",
        "MADACHI/GANGAI",
        "MADANGALA",
        "MADARA",
        "NASARAWA BAKIN KASUWA",
        "RAGWAM/MAGONSHI",
        "TSAKUWA KOFAR GABAS/ KOFAR KUKA",
        "YAYU",
      ],
      name: "KATAGUM",
    },
    {
      wards: [
        "BADARA",
        "BARA",
        "BENI 'A'",
        "BENI 'B'",
        "DEWU CENTRAL",
        "DEWU EAST",
        "KIRFI",
        "SHANGO",
        "TUBULE",
        "WANKA",
      ],
      name: "KIRFI",
    },
    {
      wards: [
        "AJILIN/GUGULIN",
        "BETI",
        "GWARAM",
        "HARDAWA",
        "JARKASA",
        "KUKADI/GUNDARI",
        "SARMA/AKUYAM",
        "SIRKO",
        "TOFU",
        "ZADAWA",
      ],
      name: "MISAU",
    },
    {
      wards: [
        "BALMA",
        "BASHE",
        "BURRA / KYATA",
        "DINGIS",
        "JANGU",
        "KUDU / YAMMA",
        "KURMI",
        "NASARU",
        "NINGI",
        "SAMA",
        "TIFFI / GUDA",
      ],
      name: "NINGI",
    },
    {
      wards: [
        "ANDUBUN",
        "BELI/GAGIDABA",
        "BUKUL/BANGIRE",
        "DISINA",
        "FAGGO",
        "KILBORI",
        "SAMBUWAL",
        "SHIRA",
        "TSAFI",
        "TUMFAFI",
        "ZUBO",
      ],
      name: "SHIRA",
    },
    {
      wards: [
        "BALL",
        "BULA",
        "BUNUNU",
        "DAJIN",
        "DULL",
        "KARDAM 'A'",
        "KARDAM 'B'",
        "LERE  SOUTH",
        "LERE NORTH",
        "TAPSHIN",
        "WAI",
      ],
      name: "TAFAWA BALEWA",
    },
    {
      wards: [
        "JAMA'A / ZARANDA",
        "LAME",
        "MARA / PALAMA",
        "RAHAMA",
        "RAUTA / GEJI",
        "RIBINA",
        "TAMA",
        "TILDEN FULANI",
        "TORO / TULAI",
        "WONU",
        "ZALAU / RISHI",
      ],
      name: "TORO",
    },
    {
      wards: [
        "BAIMA  SOUTH/EAST",
        "BAIMA NORTH / WEST",
        "DAGU EAST",
        "DAGU WEST",
        "GABANGA",
        "KATANGA",
        "KILBORI",
        "RANGAN",
        "TIYIN",
        "TUDUN WADA WEST",
        "ALANGAWARI / KAFIN / LARABAWA",
      ],
      name: "WARJI",
    },
    {
      wards: [
        "BURSALI",
        "GUMAI",
        "KATAGUM",
        "MAINAKO",
        "MAIWA",
        "MAKAWA",
        "MURMUR  SOUTH",
        "MURMUR NORTH",
        "SAKWA",
        "TASHENA / GADAI",
      ],
      name: "ZAKI",
    },
  ],
};

export const BAUCHI = { states, SR };
