const SR = {
  name: "BAYELSA",
  email: "Bayelsa@apcaims.com",
  password: "bayelsa_6u6",
  phone: "08108850572",
  statecode: "BAYELSA",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

export const states = {
  state: "BAYELSA",
  lga: [
    {
      wards: [
        "BRASS I",
        "BRASS WARD II",
        "CAPE FARMOSA",
        "EWOAMA/FANTUO",
        "KONSHO",
        "MINIBIE",
        "ODIOMA/DIEMA",
        "OKPOAMA",
        "OS-INIBIRI",
        "SANGANA",
      ],
      name: "BRASS",
    },
    {
      wards: [
        "EDUWINI I",
        "EDUWINI II",
        "OPOROMOR I",
        "OPOROMOR II",
        "OPOROMOR III",
        "OPOROMOR IV",
        "OPOROMOR V",
        "OYIAKIRI I",
        "OYIAKIRI II",
        "OYIAKIRI III",
        "OYIAKIRI IV",
        "TARAKIRI",
      ],
      name: "EKEROMOR",
    },
    {
      wards: [
        "IGBEDI",
        "KAIAMA",
        "KAIAMA/OLOBIRI",
        "ODI (CENTRAL) II",
        "ODI (NORTH) I",
        "ODI (SOUTH) III",
        "OKOLOBA (SABAGREIA) II",
        "OPOKUMA NORTH",
        "OPOKUMASOUTH",
        "SAMPOU/KALAMA",
        "SEIBOKOROGHA (SABAGREIA) 1",
      ],
      name: "KOLOKUMA/OPOKUMA",
    },
    {
      wards: [
        "BASSAMBIRI 1",
        "BASSAMBIRI 11",
        "BASSAMBIRI 111",
        "BASSAMBIRI 1V",
        "IGBETA-EWOAMA/FANTUO",
        "IKENSI",
        "MINI",
        "OGBOLOMABIRI 1",
        "OGBOLOMABIRI 11",
        "OGBOLOMABIRI 111",
        "OKOROMA 1",
        "OKOROMA 11",
        "OLUASIRI",
      ],
      name: "NEMBE",
    },
    {
      wards: [
        "ANYAMA",
        "EMEYAL",
        "IMIRINGI",
        "KOLO",
        "OGBIA",
        "OKODI",
        "OLOGI",
        "OLOIBIRI",
        "OPUME",
        "OTAKEME",
        "OTUABULA",
        "OTUASEGA",
        "OTUOKPOTI",
      ],
      name: "OGBIA",
    },
    {
      wards: [
        "ADAGBABIRI",
        "ADONI",
        "AGBERE",
        "AGORO",
        "ANGALABIRI",
        "ASAMABIRI",
        "EBEDEBIRI",
        "OFONI I",
        "OFONI II",
        "OSEKWENIKE",
        "OSSIAMA",
        "SAGBAMA",
        "TORU-EBENI",
        "TROFANI",
      ],
      name: "SAGBAMA",
    },
    {
      wards: [
        "AMASSOMA I",
        "AMASSOMA II",
        "AMASSOMA III",
        "APOI",
        "CENTRAL BOMA I",
        "CENTRAL BOMA II",
        "EAST BOMA I",
        "EAST BOMA II",
        "FOROPA",
        "KOLUAMA",
        "OLODIAMA I",
        "OLODIAMA II",
        "OPOROMA II",
        "OPOROMA 1",
        "OTUAN",
        "UKUBIE",
        "WEST BOMA",
      ],
      name: "SOUTHERN IJAW",
    },
    {
      wards: [
        "ATTISSA I",
        "ATTISSA II",
        "ATTISSA III",
        "BISENI 1",
        "BISENI 11",
        "EKPETIAMA 11",
        "EKPETIAMA I",
        "EPIE 11",
        "EPIE I",
        "EPIE III",
        "GBARAIN I",
        "GBARAIN II",
        "GBARAIN III",
        "OKORDIA",
        "ZARAMA",
      ],
      name: "YENAGOA",
    },
  ],
};

export const BAYELSA = { states, SR };
