const SR = {
  name: "BENUE",
  email: "Benue@apcaims.com",
  password: "benue_xy3",
  phone: "08108850572",
  statecode: "BENUE",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

export const states = {
  state: "BENUE",
  lga: [
    {
      wards: [
        "AKOGE/OGBILOLO",
        "APA",
        "EKILE",
        "IGUMALE I",
        "IGUMALE II",
        "IJIGBAN",
        "OGEGE",
        "ROYONGO",
        "UKWONYO",
        "ULAYI",
      ],
      name: "ADO",
    },
    {
      wards: [
        "EGBA",
        "ENUNGBA",
        "OBAGAJI",
        "ODUGBEHO",
        "OGBAULU",
        "OGWULE OGBAULU",
        "OGWULE-KADUNA",
        "OKOKOLO",
        "OSHIGBUDU",
        "USHA",
      ],
      name: "AGATU",
    },
    {
      wards: [
        "AKPETE/OJANTELLE",
        "AUKE",
        "EDIKWU I",
        "EDIKWU II",
        "IGAH-OKPAYA",
        "IGORO",
        "IKOBI",
        "OBA",
        "OFOKE",
        "OIJI",
        "UGBOKPO",
      ],
      name: "APA",
    },
    {
      wards: [
        "BINEV",
        "ETULO",
        "MBAADE",
        "MBAAKURA",
        "MBAAPEN",
        "MBAATIRKYAA",
        "MBAAZAGEE",
        "MBAIKYONGO/NYIFON",
        "MBAITYOUGH",
        "MBAKYAAN",
        "MBAYA",
        "MBAYAKA",
        "SHOROV",
      ],
      name: "BURUKU",
    },
    {
      wards: [
        "GBK/CENTRAL MARKET",
        "GBOKO EAST",
        "GBOKO NORTH WEST",
        "GBOKO SOUTH",
        "IGYOROV",
        "MBAA VARAKAA",
        "MBAANKU",
        "MBADAM",
        "MBADIM",
        "MBAKPER",
        "MBAKWEN",
        "MBATAN",
        "MBATSER",
        "MBATYU",
        "UKPEKPE",
        "YANDEV NORTH",
        "YANDEV SOUTH",
      ],
      name: "GBOKO",
    },
    {
      wards: [
        "ABINSI",
        "KAAMBE",
        "MBABAI",
        "MBADWEM",
        "MBAWA",
        "MBAYER/YANDEV",
        "NYIEV",
        "NZOROV",
        "SAGHEV",
        "UVIR",
      ],
      name: "GUMA",
    },
    {
      wards: [
        "AKPACH'AYI",
        "ALIADE TOWN",
        "GBEMACHA",
        "IKYOGBAJIR",
        "IKYONOV",
        "MBABUR",
        "MBAIASE",
        "MBAIKYAAN",
        "MBAIKYU",
        "MBALOM",
        "MBASOMBO",
        "MBAYOM",
        "SHOUGH",
        "UGEE",
      ],
      name: "GWER EAST",
    },
    {
      wards: [
        "AVIHIJIME",
        "GAAMBE - USHIN",
        "GBAANGE/TONGOV",
        "IKYAGHEV",
        "ISAMBE/MBASEV",
        "ITYOUGHATEE/INJAHA",
        "MBABUANDE",
        "MBACHOHON",
        "MBANYAMSHI",
        "MBAPA",
        "MERKYEN",
        "SAGHER/UKUSU",
        "SENGEV",
        "SENGEV/YENGEV",
        "TIJIME",
      ],
      name: "GWER WEST",
    },
    {
      wards: [
        "IKURAV TIEV I",
        "IKURAV TIEV II",
        "IWAR(TONGOV I)",
        "KATSINA-ALA TOWN",
        "MBACHER",
        "MBAJIR",
        "MBATULA/MBEREV",
        "MBAYONGO",
        "MICHIHE",
        "TIIR(TONGOV II)",
        "UTANGE",
        "YOOYO",
      ],
      name: "KATSINA-ALA",
    },
    {
      wards: [
        "IKYURAV/MBATWER",
        "MBAGUSA/MBATSER",
        "MBAIKYASE",
        "MBAIWARNYAM",
        "MBAKE",
        "MBANOR",
        "MBATSEN",
        "MBAVOA",
        "MBAWAR",
        "MBAYEGH/MBAIKYER",
        "TSE-AGBERAGBA",
      ],
      name: "KONSHISHA",
    },
    {
      wards: [
        "ADIKPO METROPOLIS",
        "KUMAKWAGH",
        "LIEV I",
        "LIEV II",
        "MBADURA",
        "MBAGBA/MBAIKYAN",
        "MBAIKYOR",
        "MBAKETSA",
        "MBAYOO",
        "MENEV",
        "MOON",
        "TONDOV I",
        "TONDOV II",
        "USAR",
        "YAAV",
      ],
      name: "KWANDE",
    },
    {
      wards: [
        "MBADYUL",
        "MBAGBER",
        "MBATER",
        "MBAVUUR",
        "MBAYAM",
        "NENZEV",
        "TOMBO",
        "TURAN",
        "UKEMBERGYA/ISWAREV",
        "YONOV",
      ],
      name: "LOGO",
    },
    {
      wards: [
        "AGAN",
        "ANKPA/WADATA",
        "BAR",
        "CENTRAL/SOUTH MISSION",
        "CLERKS/MARKET",
        "FILDI",
        "MBALAGH",
        "MODERN MARKET",
        "NORTH BANK I",
        "NORTH BANK II",
        "WAILOMAYO",
      ],
      name: "MAKURDI",
    },
    {
      wards: [
        "ADIKO",
        "ADUM WEST",
        "IKWOKWU",
        "IRABI",
        "ITOGO",
        "OBARIKE",
        "OBEKO",
        "ODIAPA",
        "OGORE",
        "OKPOKWU",
        "OKWUTUNGBE",
        "ORIHI",
      ],
      name: "OBI",
    },
    {
      wards: [
        "AI-OODO I",
        "AI-OODO II",
        "AI-OONO I",
        "AI-OONO II",
        "AI-OONO III",
        "EHAJE I",
        "EHAJE II",
        "ITABONO I",
        "ITABONO II",
        "OLACHAGBAHA",
        "OROKAM I",
        "OROKAM II",
        "OROKAM III",
      ],
      name: "OGBADIBO",
    },
    {
      wards: [
        "AGADAGBA",
        "AWUME EHAJE",
        "AWUME ICHO",
        "EHATOKPE",
        "IDEKPA",
        "OCHOBO",
        "OGLEWU EHAJE",
        "OGLEWU ICHO",
        "ONYAGEDE ICHO (OGOLI)",
        "ONYAGEDE-EHAJE (ALLE)",
      ],
      name: "OHIMINI",
    },
    {
      wards: [
        "ADOKPA",
        "AINU",
        "IBILLA",
        "IDELLE",
        "IYECHE",
        "OBORU/OYE",
        "OJU",
        "OKPOKPO",
        "OKWUDU",
        "OWO",
        "UKPA/AINU ETTE",
      ],
      name: "OJU",
    },
    {
      wards: [
        "AMEJO",
        "EKE",
        "ICHAMA II",
        "OJIGO",
        "OJOGA",
        "OKONOBO",
        "OKPAILE/INGLE",
        "OKPOGA CENTRAL",
        "OKPOGA NORTH",
        "OKPOGA SOUTH",
        "OKPOGA WEST",
        "UGBOKOLO",
      ],
      name: "OKPOKWU",
    },
    {
      wards: [
        "ADOKA-HAJE",
        "ADOKA-ICHO",
        "ALLAN",
        "ENTEKPA",
        "EWULO",
        "OKETE",
        "OTOBI",
        "OTUKPO TOWN CENTRAL",
        "OTUKPO TOWN EAST",
        "OTUKPO TOWN WEST",
        "UGBOJU-EHAJE",
        "UGBOJU-ICHO",
        "UGBOJU-OTAHE",
      ],
      name: "OTUKPO",
    },
    {
      wards: [
        "MBAAJIR AKAA",
        "MBAAYO",
        "MBACHAVER IKYONDO",
        "MBAIGBA",
        "MBAIKYAA",
        "MBAIKYO/MBAYIA",
        "MBAKWAKEM",
        "MBANYAGBER",
        "SHITILE",
        "TONGOV",
      ],
      name: "TARKA",
    },
    {
      wards: [
        "ATERAYANGE",
        "AZENDESHI",
        "BORIKYO",
        "ITYULUV",
        "KENDEV",
        "KUNDAV",
        "LUMBUV",
        "MBATIAN",
        "MBAYENGE",
        "MBAZUN",
        "TSAAV",
        "UGBAAM",
        "UYAM",
      ],
      name: "UKUM",
    },
    {
      wards: [
        "ATIKYESE",
        "IKYOV",
        "LESSEL",
        "MBAAKA",
        "MBAANYAM",
        "MBAGBA",
        "MBAGWAZA",
        "MBAGWE",
        "MBAKUHA",
        "MBAYEGH",
        "UTANGE",
      ],
      name: "USHONGO",
    },
    {
      wards: [
        "MBADEDE",
        "MBAGBAM",
        "MBAGBERA",
        "MBAJOR",
        "MBAKAANGE",
        "MBAKYAHA",
        "MBANYUMANGBAGH",
        "MBATYOUGH",
        "MBAYONGO",
        "NINGEV",
        "TSAMBE",
        "VANDEIKYA TOWNSHIP",
      ],
      name: "VANDEIKYA",
    },
  ],
};

export const BENUE = { states, SR };
