const SR = {
  name: "CROSS RIVERS",
  email: "Crossrivers@apcaims.com",
  password: "crossrivers_4jmm",
  phone: "08108850572",
  statecode: "CROSSRIVERS",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

export const states = {
  statecode: "CROSSRIVERS",
  state: "CROSS RIVERS",
  lga: [
    {
      wards: [
        "ADADAMA",
        "AFAFANYI/IGONIGONI",
        "EBOM",
        "EDIBA",
        "EKUREKU I",
        "EKUREKU II",
        "IMABANA I",
        "IMABANA II",
        "ITIGIDI",
        "USUMUTONG",
      ],
      name: "ABI",
    },
    {
      wards: [
        "AKAMKPA URBAN",
        "AWI",
        "EKU",
        "IKO",
        "IKPAI",
        "MBARAKOM",
        "OBAN",
        "OJUK NORTH",
        "OJUK SOUTH",
        "UYANGA",
      ],
      name: "AKAMKPA",
    },
    {
      wards: [
        "ATIMBO EAST",
        "ATIMBO WEST",
        "ENEYO",
        "IDUNDU/ANYANGANSE",
        "IKANG CENTRAL",
        "IKANG NORTH",
        "IKANG SOUTH",
        "IKOT EDEM ODO",
        "IKOT EYO",
        "IKOT NAKANDA",
      ],
      name: "AKPABUYO",
    },
    {
      wards: [
        "ABANA",
        "AKPANKANYA",
        "AKWA",
        "AMBAI EKPA",
        "AMOTO",
        "ARCHIBONG",
        "ATAI EMA",
        "EFUT INWANG",
        "EKPOT ABIA",
        "ODIONG",
      ],
      name: "BAKASSI",
    },
    {
      wards: [
        "ABUOCHICHE",
        "AFRIKE OCHAGBE",
        "AFRIKE OKPECHE",
        "BETEN",
        "GAKEM",
        "IBIARAGIDI",
        "NYANYA",
        "OTUKPURU",
        "UGBORO",
        "UKPAH",
      ],
      name: "BEKWARRA",
    },
    {
      wards: [
        "ABAYONG",
        "ADIM",
        "AGWAGUNE/OKURIKE",
        "AKPET/ABINI",
        "BIAKPAN",
        "EHOM",
        "EREI NORTH",
        "EREI SOUTH",
        "IKUN/ETONO",
        "UMON NORTH",
        "UMON SOUTH",
      ],
      name: "BIASE",
    },
    {
      wards: [
        "ABO",
        "ALANKWE",
        "BEEBO/BUMAJI",
        "BOJE",
        "BUDA",
        "BUENTSEBE",
        "BUNYIA/OKUBUCHI",
        "EKPASHI",
        "KAKWAGOM/BAWOP",
        "OGEP/OSOKOM",
        "OKU/BORUM/NJUA",
      ],
      name: "BOKI",
    },
    {
      wards: ["I", "II", "III", "IV", "IX", "V", "VI", "VII", "VIII", "X"],
      name: "CALABAR MUNICIPALITY",
    },
    {
      wards: [
        "EIGHT (8)",
        "ELEVEN (11)",
        "FIVE (5)",
        "FOUR (4)",
        "NINE (9)",
        "ONE (1)",
        "SEVEN (7)",
        "SIX (6)",
        "TEN (10)",
        "THREE (3)",
        "TWELVE (12)",
        "TWO (2)",
      ],
      name: "CALABAR SOUTH",
    },
    {
      wards: [
        "ABIA",
        "ABIJANG",
        "AGBOKIM",
        "AJASSOR",
        "BENDEGHE EKIEM",
        "EFFRAYA",
        "ETOMI",
        "ITAKA",
        "MKPOT/AYUK ABA",
        "NSOFANG",
      ],
      name: "ETUNG",
    },
    {
      wards: [
        "ABANYUM",
        "AKPARABONG",
        "IKOM URBAN I",
        "IKOM URBAN II",
        "NDE",
        "NNAM",
        "NTA/NSELLE",
        "OFUTOP I",
        "OFUTOP II",
        "OLULUMO",
        "YALA/NKUM",
      ],
      name: "IKOM",
    },
    {
      wards: [
        "BASANG",
        "BEBI",
        "BECHEVE",
        "BENDI I",
        "BENDI II",
        "BISHIRI NORTH",
        "BISHIRI SOUTH",
        "BISU",
        "BUSI",
        "UTANGA",
      ],
      name: "OBANLIKU",
    },
    {
      wards: [
        "ABABENE",
        "APIAPUM",
        "IYAMOYONG",
        "OBUBRA URBAN",
        "OCHON",
        "OFAT",
        "OFODUA",
        "OFUMBONGHA/YALA",
        "OSOPONG I",
        "OSOPONG II",
        "OVONUM",
      ],
      name: "OBUBRA",
    },
    {
      wards: [
        "ALEGE/UBANG",
        "ANGIABA / BEGIAKA",
        "BEGIADING",
        "IPONG",
        "OBUDU URBAN I",
        "OBUDU URBAN II",
        "UKPE",
        "UTUGWANG CENTRAL",
        "UTUGWANG NORTH",
        "UTUGWANG SOUTH",
      ],
      name: "OBUDU",
    },
    {
      wards: [
        "ADIABO/EFUT",
        "AKAMKPA",
        "CREEK TOWN I",
        "CREEK TOWN II",
        "EKI",
        "EKORI/ANAKU",
        "ENIONG",
        "IKONETO",
        "ITO/IDERE/UKWA",
        "OBOMITIAT/MBIABO/EDIONG",
        "ODOT",
        "ODUKPANI CENTRAL",
        "ONIMAN-KIONG",
      ],
      name: "ODUKPANI",
    },
    {
      wards: [
        "EKAJUK I",
        "EKAJUK II",
        "MBUBE EAST I",
        "MBUBE EAST II",
        "MBUBE WEST I",
        "MBUBE WEST II",
        "NKUM IBORR",
        "NKUM IREDE",
        "OGOJA URBAN I",
        "OGOJA URBAN II",
      ],
      name: "OGOJA",
    },
    {
      wards: [
        "ABANAKPAI",
        "AFREKPE/EKPENTI",
        "AJERE",
        "ASSIGA",
        "BIKO BIKO",
        "IDOMI",
        "IJIMAN",
        "IJOM",
        "IKPAKAPIT",
        "INYIMA",
        "MKPANI/AGOI",
        "NKPOLO/UKPAWEN",
        "NTAN",
      ],
      name: "YAKURR",
    },
    {
      wards: [
        "ECHUMOFANA",
        "GABU",
        "IJIRAGA",
        "NJRIGOM/MFUMA",
        "OKPOMA",
        "OKUKU",
        "WANAKOM",
        "WANIHEM",
        "WANIKADE",
        "YACHE",
        "YAHE",
      ],
      name: "YALA",
    },
  ],
};

export const CROSSRIVERS = { states, SR };
