const SR = {
  name: "EBONYI",
  email: "Ebonyi@apcaims.com",
  password: "ebonyi_rGc",
  phone: "08108850572",
  statecode: "EBONYI",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "EBONYI",
  state: "EBONYI",
  lga: [
    {
      wards: [
        "ABAKPA",
        "AMACHI (NDEBO)",
        "AMACHI (NDEGU)",
        "AMAGU / ENYIEBA",
        "AMAGU UNUHU",
        "AZUII UDENE",
        "AZUIYIOKWU LAYOUT",
        "AZUMILI/AZUGWU",
        "EDDA",
        "IZZI UNUHU",
        "NDIAGU",
        "OKPOITUMO NDEBOR",
        "OKPOITUMO NDIEGU",
        "TIMBER SHED",
      ],
      name: "ABAKALIKI",
    },
    {
      wards: [
        "AMAEKE",
        "AMANGWU EDDA",
        "AMAOSO",
        "AMATO",
        "AMIGBO ETITI EDDA",
        "AMIRI",
        "EBUNWANA",
        "NDIOKE EKOLI EDDA",
        "NGUZU",
        "OSO",
        "OWUTU",
      ],
      name: "AFIKPO SOUTH",
    },
    {
      wards: [
        "AMATA-AKPOHA",
        "AMOGU AKPOHA",
        "EZEKE AMASIRI",
        "IBII/OZIZA AFIKPO",
        "ITIM AFIKPO",
        "NKPOGHORO AFIKPO",
        "OHAISU AFIKPO 'A'",
        "OHAISU AFIKPO 'B'",
        "POPERI AMASIRI",
        "UGWUEGU AFIKPO",
        "UWANA AFIKPO 1",
        "UWANA AFIKPO II",
      ],
      name: "AFIKPO NORTH",
    },
    {
      wards: [
        "(ABAKPA)",
        "ABOFIA",
        "AGALEGU",
        "ECHIABA",
        "EGWUDINAGU",
        "ENYIBICHIRI I",
        "ENYIBICHIRI II",
        "KPIRIKPIRI",
        "MBEKE",
        "NDIEBO",
        "NDIEGU",
        "ONUENYIM",
        "URBAN NEW LAYOUT",
      ],
      name: "EBONYI",
    },
    {
      wards: [
        "AMUDA/AMA WULA",
        "EKKA",
        "INYERE",
        "NDIEGUAZU - UMUOGHARA",
        "NKOMORO",
        "OGBOJI",
        "OKPOSI UMUOGHARA",
        "OMEGE UMUEZEOKOHA",
        "ORIUZOR",
        "OSHIEGBE UMUEZ EOKOHA",
        "UMUEZEOKA",
      ],
      name: "EZZA NORTH",
    },
    {
      wards: [
        "AMAEKA",
        "AMAEZEKWE",
        "AMAGU/NSOKARA",
        "AMANA",
        "AMUDO/OKOFFIA",
        "AMUZU",
        "ECHARE",
        "EZZAMA",
        "IKWUATOR/IDEMBIA",
        "ONUEKE",
        "UMUNWAGU / IDEMBIA",
      ],
      name: "EZZA SOUTH",
    },
    {
      wards: [
        "AMA INYIMA",
        "ECHIALIKE",
        "EKA AWOKE",
        "EKPANWUDELE",
        "EKPELU",
        "ENYIBICHIRI",
        "ETAM",
        "IGBUDU I",
        "IGBUDU II",
        "INYIMAGU I",
        "INYIMAGU II",
        "NDIAGU AMAGU I",
        "NDIAGU AMAGU II",
        "NDIAGU ECHARA I",
        "NDIAGU ECHARA II",
        "NDUFU AMAGU",
        "NDUFU AMAGU I",
        "NDUFU AWKE",
        "NDUFU ECHARA",
        "NOYE ALIKE",
      ],
      name: "IKWO",
    },
    {
      wards: [
        "AGBA",
        "AMAEZU",
        "AZUINYABA 'A'",
        "AZUINYABA 'B'",
        "EZILLO I",
        "EZILLO II",
        "EZZAGU(NKOMOR)",
        "EZZAGU(OGBOJI)",
        "IYIONU",
        "NKALAGU",
        "NKALAHA",
        "NTEZI",
        "OBEAGU",
        "OHOFIA",
        "OKPOTO",
        "UMUHUALI",
      ],
      name: "ISHIELU",
    },
    {
      wards: [
        "AKAEZE ISHIAGU",
        "AKAEZE UKWU",
        "AMAGU",
        "AMONYE",
        "IHENTA OGIDI",
        "IYIOJI AKAEZE",
        "NDIOKORO UKWU",
        "NGWOGWO",
        "OBINAGU",
        "OKUE",
        "UMOBO",
      ],
      name: "IVO",
    },
    {
      wards: [
        "AGBAJA ANYANWUIGWE",
        "AGBAJA OFFIA ONWE",
        "AGBAJA(MGBO)",
        "EZZA INYIMAGU - IGWELED OHA",
        "EZZA INYIMAGU - IZIOGO",
        "EZZA INYIMAGU IGBUHU",
        "EZZA INYIMAGU NDIAGU",
        "IGBEAGU III",
        "IGBEAGU NDI ETTAH",
        "IGBEAGU NDUOGBU",
        "MGBALAKU INYIMAGU I",
        "MGBALAKU INYIMAGU II",
        "NDIEZE INYIMAGU 11 NDIABOR ISHIAGU",
        "NDIEZE INYIMAGU MGBABELUZOR",
      ],
      name: "IZZI",
    },
    {
      wards: [
        "AMAECHI OKPOSI",
        "ENENA EZERAKU",
        "MGBOM OKPOSI",
        "OBIOZARA",
        "OKPOSI ACHARA",
        "OKPOSI OKWU",
        "UGBOGOLOGO/UGWULANGWU",
        "UHUO TARU-UGWU-LANGWU",
        "UMIC HIMA",
        "UMUNAGA",
        "UMUOBUNA",
      ],
      name: "OHAOZARA",
    },
    {
      wards: [
        "EFFIUM II",
        "EFFIUM I",
        "EZZAMGBO",
        "ISHI NGBO I",
        "ISHI NGBO II",
        "NGBO",
        "OKPOSHI I",
        "OKPOSHI II",
        "UMU OGUDU AKPU I",
        "UMU OGUDU AKPU II",
        "UMU OGUDU OSHIA",
        "UMUAGARA / AMECHI",
        "WIGBEKE I",
        "WIGBEKE II",
        "WIGBEKE III",
      ],
      name: "OHAUKWU",
    },
    {
      wards: [
        "ABAOMEGE",
        "AGBABOR-ISU",
        "AMANATOR-ISU",
        "EBIA OSHIRI",
        "ENUAGU-ONICHA",
        "ISI-ONICHA",
        "ISINKWO-UKAMU",
        "OBEAGU-ISU",
        "OGUDUUKWOR OSHIRI",
        "OKUZU-UKAWU",
        "UGWU-OSHIRI",
        "UMUDOMI-ONICHA",
      ],
      name: "ONICHA",
    },
  ],
};

export const EBONYI = { states, SR };
