const SR = {
  name: "EKITI",
  email: "Ekiti@apcaims.com",
  password: "ekiti_etf3",
  phone: "08108850572",
  statecode: "EKITI",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "EKITI",
  state: "EKITI",
  lga: [
    {
      wards: [
        "ADO 'A' IDOFIN",
        "ADO 'B' INISA",
        "ADO 'C' IDOLOFIN",
        "ADO 'D' IJIGBO",
        "ADO 'E' IJOKA / OREREOWU",
        "ADO 'F' OKEYINMI",
        "ADO 'G' OKE ILA",
        "ADO 'H' EREGURU",
        "ADO 'I' DALLIMORE",
        "ADO 'J' OKESA",
        "ADO 'K' IRONA",
        "ADO 'L' IGBEHIN",
        "ADO 'M' FARM SETTLEMENT",
      ],
      name: "ADO EKITI",
    },
    {
      wards: [
        "EFON III",
        "EFON I",
        "EFON II",
        "EFON V",
        "EFON VI",
        "EFON VII",
        "EFON VIII",
        "EFON X",
        "EFON IV",
        "EFON IX",
      ],
      name: "EFON",
    },
    {
      wards: [
        "ARAROMI",
        "ILASA I",
        "ILASA II / IKUN / ARAROMI / EDA ILE",
        "ISINBODE",
        "KOTA I",
        "KOTA II",
        "OBADORE I",
        "OBADORE II",
        "OBADORE III",
        "OBADORE IV",
        "OMUO - OKE I",
        "OMUO OKE II",
      ],
      name: "EKITI EAST",
    },
    {
      wards: [
        "IGBARA ODO I",
        "IGBARA ODO II",
        "ILAWE III",
        "ILAWE IV",
        "ILAWE V",
        "ILAWE I",
        "ILAWE II",
        "ILAWE VI",
        "ILAWE VII",
        "OGOTUN I",
        "OGOTUN II",
      ],
      name: "EKITI SOUTH WEST",
    },
    {
      wards: [
        "ARAMOKO I",
        "ARAMOKO II",
        "ARAMOKO III / ERIO",
        "ERIJIYAN I",
        "ERIJIYAN II",
        "IDO AJINARE",
        "IKOGOSI",
        "IPOLE ILORO",
        "OKEMESI I",
        "OKEMESI II",
        "OKEMESI III",
      ],
      name: "EKITI WEST",
    },
    {
      wards: [
        "IDA MUDU II",
        "IDAMUDU I",
        "ODO - EMURE I",
        "ODO - EMURE II",
        "ODO - EMURE III",
        "ODO - EMURE IV",
        "OGBONTIORO I",
        "OGBONTIORO II",
        "OKE EMURE I",
        "OKE EMURE II",
      ],
      name: "EMURE",
    },
    {
      wards: [
        "ADEGBA I",
        "ADEGBA II",
        "AGBADO",
        "EGBE / IRO",
        "IJAN",
        "ILUOMOBA",
        "IMESI",
        "ODE I",
        "ODE II",
        "ODE III",
      ],
      name: "GBONYIN",
    },
    {
      wards: [
        "AYETORO I",
        "AYETORO II",
        "IDO I",
        "IDO II",
        "IFAKI I",
        "IFAKI II",
        "IGBOLE / IFISIN / AAYE",
        "ILOGBO",
        "ORIN / ORA",
        "OSI",
        "USI",
      ],
      name: "IDO / OSI",
    },
    {
      wards: [
        "EKAMARUN WARD 'A'",
        "EKAMARUN WARD 'B'",
        "IJERO WARD 'A'",
        "IJERO WARD 'B'",
        "IJERO WARD 'C'",
        "IJERO WARD 'D'",
        "IKORO WARD 'A'",
        "ILORO / IJUNRIN WARD 'B'",
        "ILORO WARD 'A'",
        "IPOTI / ODO OWA WARD 'C'",
        "IPOTI WARD 'A'",
        "IPOTI WARD 'B'",
      ],
      name: "IJERO",
    },
    {
      wards: [
        "AFAO / KAJOLA / AYETORO",
        "AGBADO / OYO",
        "ARE ARAROMI",
        "ATIBA/AAFIN",
        "IDEMO",
        "ILAPETU / IJAO",
        "ODOSE",
        "OGBONJANA",
        "OKE - OSUN",
        "OKERUKU",
        "UGELE / AROKU",
      ],
      name: "IKERE",
    },
    {
      wards: [
        "ARAROMI / BOLORUNDURO",
        "IJESA ISU",
        "IKOLE EAST",
        "IKOLE NORTH",
        "IKOLE SOUTH",
        "IKOLE WEST I",
        "IKOLE WEST II",
        "IPAO / OKE AKO / IRELE",
        "ITAPAJI / IYEMERO",
        "ODO AYEDUN I",
        "ODO AYEDUN / AYEBODE",
        "OKE AYEDUN / ---",
      ],
      name: "IKOLE",
    },
    {
      wards: [
        "EDA ONIYO",
        "EWU",
        "IJESAMODU",
        "ILUDUN I",
        "ILUDUN II",
        "IPERE",
        "IYE I",
        "IYE II",
        "IYE III",
        "OBADA",
      ],
      name: "ILEJEMEJE",
    },
    {
      wards: [
        "AFAO",
        "ARE",
        "AWO",
        "IGBEMO",
        "IGEDE I",
        "IGEDE II",
        "IGEDE III",
        "IROPORA / ESURE / EYIO",
        "IWOROKO",
        "IYIN I",
        "IYIN II",
      ],
      name: "IREPODUN / IFELODUN",
    },
    {
      wards: [
        "ERINWA I",
        "ERINWA II",
        "ODO ISE I",
        "ODO ISE II",
        "ODO ISE III",
        "ORAYE III",
        "ORAYE I",
        "ORAYE II",
        "ORUN I",
        "ORUN II",
      ],
      name: "ISE / ORUN",
    },
    {
      wards: [
        "ERINMOPE I",
        "ERINMOPE II",
        "IGOGO I",
        "IGOGO II",
        "IKUN I",
        "IKUN II",
        "OSAN",
        "OSUN",
        "OTUN I",
        "OTUN II",
        "OTUN III",
      ],
      name: "MOBA",
    },
    {
      wards: [
        "AYEDE NORTH",
        "AYEDE SOUTH ITAJI",
        "AYEGBAJU",
        "ILUPEJU I",
        "ILUPEJU II",
        "IRE I",
        "IRE II",
        "ISAN / ILAFON / ILEMESO",
        "ITAPA / OSIN",
        "OMU OKE / OMU ODO / IJELU",
        "OYE I",
        "OYE II",
      ],
      name: "OYE",
    },
  ],
};

export const EKITI = { states, SR };
