const SR = {
  name: "ENUGU",
  email: "Enugu@apcaims.com",
  password: "enugu_L4k",
  phone: "08108850572",
  statecode: "ENUGU",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "ENUGU",
  state: "ENUGU",
  lga: [
    {
      wards: [
        "MPU",
        "NDEABO",
        "NNENWE I",
        "NNENWE II",
        "NNENWE III",
        "ODUMA I",
        "ODUMA II",
        "ODUMA III",
        "ODUMA IV",
        "OKPANKU",
      ],
      name: "ANINRI",
    },
    {
      wards: [
        "AGBOGUGU",
        "ANIKENANO/UGWUEME",
        "AWGU I",
        "AWGU II",
        "IHE",
        "ISU AWA/OGUGU/AGBUDU/ITUKU",
        "MGBIDI/MMAKU",
        "MGBOWO",
        "OBEAGU",
        "OGBAKU",
        "OWELLI/AMOLI/UGBO/OGUGU",
      ],
      name: "AWGU",
    },
    {
      wards: [
        "ABAKPA I",
        "ABAKPA II",
        "AMORJI",
        "IBAGWA-NIKE/EDEM",
        "MBULU-NJODO EAST",
        "MBULU-NJODO WEST",
        "MBULUIYIUKWU",
        "MBULUOWEHE",
        "TRANS-EKULU",
        "UGWUGO NIKE",
        "UMUCHIGBO",
        "UMUENWENE",
      ],
      name: "ENUGU EAST",
    },
    {
      wards: [
        "ASATA TOWNSHIP",
        "CHINA TOWN",
        "G.R.A",
        "GUI NEWLAYOUT",
        "IHEWUZI",
        "INDEPENDENCE LAYOUT",
        "NEW HAVEN",
        "OGBETTE EAST",
        "OGBETTE WEST",
        "OGUI TOWNSHIP",
        "ONU-ASATA",
        "UDI SIDING/IVA VALLEY",
        "UMUNEVO",
      ],
      name: "ENUGU NORTH",
    },
    {
      wards: [
        "ACHARA LAYOUT EAST",
        "ACHARA LAYOUT WEST",
        "AKWUKE",
        "AMECHI I",
        "AMECHI II",
        "AWKUNANAW EAST",
        "AWKUNANAW WEST",
        "MARYLAND",
        "OBEAGU I",
        "OBEAGU II",
        "UGWUAJI",
        "UWANI EAST",
        "UWANI WEST",
      ],
      name: "ENUGU SOUTH",
    },
    {
      wards: [
        "AGBA UMANA",
        "AGUOBU (UMUMBA)",
        "AGUOBU-OWA 1",
        "AGUOBU-OWA 11",
        "AWHA",
        "IMEZI OWA I",
        "IMEZI OWA II",
        "IWOLLO",
        "MGBAGBU OWA I",
        "MGBAGBU OWA III",
        "MGBAGBU OWA II",
        "OBE AGU UMANA",
        "OBINOFIA",
        "OGHE I",
        "OGHE II",
        "OKPOGHO",
        "OLO/AMAGU UMULOKPA I",
        "ULO/AMAGU/UMULOKPA II",
        "UMANA NDIAGU",
        "UMUMBA NDIUMO",
      ],
      name: "EZEAGU",
    },
    {
      wards: [
        "AKU I",
        "AKU II",
        "AKU III",
        "AKU IV",
        "AKU V (IDUEME)",
        "DIOGBE/UMUNKO",
        "EJUOHA/UDEME",
        "EKWEGBE I",
        "EKWEGBE II",
        "IKOLO/OHEBE",
        "OHAODO I",
        "OHAODO II",
        "ONYOHOR/OCHIMA/IDOHA",
        "OZALLA I",
        "OZALLA II",
        "UKEHE I",
        "UKEHE II",
        "UKEHE III",
        "UKEHE IV",
        "UKEHE V",
      ],
      name: "IGBO ETITI",
    },
    {
      wards: [
        "ESSODO 1",
        "ESSODO 11",
        "ESSODO 111",
        "ETTE 1",
        "ETTE 11",
        "ETTE CENTRAL",
        "EZZODO",
        "UMUITODO I",
        "UMUITODO II",
        "UMUITODO III",
        "UMUOZZI I",
        "UMUOZZI II",
        "UMUOZZI III",
        "UMUOZZI IV",
        "UMUOZZI IX",
        "UMUOZZI V",
        "UMUOZZI VI",
        "UMUOZZI VII",
        "UMUOZZI VIII",
        "UMUOZZI X",
      ],
      name: "IGBO EZE NORTH",
    },
    {
      wards: [
        "ALOR AGU",
        "AMABO /HAUSA/ YORUBA",
        "ECHARA",
        "EZEMA WARD",
        "IHEAKA (LIKKI/AKUTARA WARD)",
        "IHEAKA (UGO AKOHI WARD)",
        "IHEAKPU (AJUONA OGBAGU WARD)",
        "IHEAKPU (EZZI NGWU WARD)",
        "ITCHI/UWANI I",
        "ITCHI/UWANI II",
        "NKALAGU OBUKPA",
        "OVOKO (AJUONA WARD)",
        "OVOKO (UMUELO/OVOKO AGU WARD)",
        "OVOKO (UMULOLO WARD)",
        "UHUNOWERRE",
        "UNADU",
      ],
      name: "IGBO EZE SOUTH",
    },
    {
      wards: [
        "EHAMUFU I",
        "EHAMUFU II",
        "EHAMUFU III",
        "EHAMUFU IV",
        "IKEM I",
        "IKEM II",
        "MBU I",
        "MBU II",
        "NEKE I",
        "NEKE II",
        "UMUALOR",
      ],
      name: "ISI UZO",
    },
    {
      wards: [
        "AKPAWFU/ISIENU/AMANGUNZE",
        "AMAGUNZE",
        "AMANKANU/OGBAHU",
        "AMECHI/IDODO/ORUKU",
        "IHUOKPARA",
        "MBURUBU",
        "NARA I",
        "NARA II",
        "NKEREFI I",
        "NKEREFI II",
        "NOMEH",
        "OWO",
        "UGBAWKA I",
        "UGBAWKA II",
      ],
      name: "NKANU EAST",
    },
    {
      wards: [
        "AGBANI",
        "AKEGBE-UGWU (OKWUO)",
        "AKPUGO II",
        "AKPUGO III",
        "AKUGBO IV",
        "AMODU",
        "AMURRI",
        "IBITE AKEGBE UGWU",
        "NDIUNO UWANI (AKPUGO I)",
        "OBE",
        "OBINAGU UWANI (AKPUGO I)",
        "OBUOFFIA",
        "OZALLA",
        "UMUEZE",
      ],
      name: "NKANU WEST",
    },
    {
      wards: [
        "AGBEMEBE/UMABOR",
        "AKALITE",
        "AKPA/OZZI",
        "ALOR-UNO",
        "EDE-NTA",
        "EDE-UKWU",
        "EDEM-ANI",
        "EHA-NDIAGU",
        "EHA-UNO",
        "EJUONA/UWANI",
        "IBAGWANI/IBAGWAGA OKPALIGBO",
        "IBEKU",
        "IHE",
        "MKPUNANO",
        "NNU",
        "OBIMO/IKWOKA",
        "OBUKPA",
        "OGBOZALLA/IDI",
        "OKPUJE/OKUTU/ANUKA",
        "OWERRE/UMUOYO",
      ],
      name: "NSUKKA",
    },
    {
      wards: [
        "ACHIAGU I",
        "ACHIAGU II",
        "ACHIAGU III",
        "ACHIUNO I",
        "ACHIUNO II",
        "ACHIUNO III",
        "ACHIUNO IV",
        "AKPUGOEZE",
        "AWLAW",
        "INYI I",
        "INYI II",
        "INYI III",
        "INYI IV",
        "OJI-RIVER I",
        "OJI-RIVER II",
        "OJI-RIVER III",
        "OJI-RIVER IV",
        "UGWUOBA I",
        "UGWUOBA II",
        "UGWUOBA III",
      ],
      name: "OJI-RIVER",
    },
    {
      wards: [
        "AMALA",
        "EZIMO",
        "IMILIKE",
        "OBOLLO-AFOR",
        "OBOLLO-EKE",
        "OBOLLO-ETITI",
        "OGBODU-ABA",
        "ORBA I",
        "ORBA II",
        "UDUNEDEM",
      ],
      name: "UDENU",
    },
    {
      wards: [
        "ABIA",
        "ABOR",
        "AFFA/OGHU/IKONO",
        "AKPA KWUME/NZE",
        "AMOKWE",
        "AWHUM/UKANA",
        "EBE",
        "EGEDE/UMUOKA",
        "EKE",
        "NACHI",
        "NGWO ASA",
        "NGWO UNO",
        "NSUDE",
        "OBINAGU",
        "OBIOMA",
        "OKPATU",
        "UDI/AGBUDU",
        "UMUABI",
        "UMUAGA",
        "UMULUMGBE",
      ],
      name: "UDI",
    },
    {
      wards: [
        "ABBI",
        "ADABA-NKUME",
        "ADANI",
        "AKPOGU",
        "IGGA/ASABA",
        "NIMBO I",
        "NIMBO II",
        "NKPOLOGU",
        "NROBO",
        "OGURUGU",
        "OJO",
        "UGBENE I",
        "UGBENE II",
        "UKPATA",
        "UMULOKPA",
        "UVURU",
      ],
      name: "UZO-UWANI",
    },
  ],
};

export const ENUGU = { states, SR };
