const SR = {
  name: "GOMBE",
  email: "Gombe@apcaims.com",
  password: "gombe_9e7",
  phone: "08108850572",
  statecode: "GOMBE",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "GOMBE",
  state: "GOMBE",
  lga: [
    {
      wards: [
        "AKKO",
        "GARKO",
        "KALSHINGI",
        "KASHERE",
        "KUMO CENTRAL",
        "KUMO EAST",
        "KUMO NORTH",
        "KUMO WEST",
        "PINDIGA",
        "TUKULMA",
        "TUMU",
      ],
      name: "AKKO",
    },
    {
      wards: [
        "BAMBAM",
        "BANGU",
        "DADIYA",
        "GELENGU / BALANGA",
        "KINDIYO",
        "KULANI / DEGRE /SIKKAM",
        "MWONA",
        "NYUWAR / JESSU",
        "SWA / REF / W. WAJA",
        "TALASSE / DONG / REME",
      ],
      name: "BALANGA",
    },
    {
      wards: [
        "BAGANJE NORTH",
        "BAGANJE SOUTH",
        "BARE",
        "BILLIRI NORTH",
        "BILLIRI SOUTH",
        "KALMAI",
        "TAL",
        "TANGLANG",
        "TODI",
        "TUDU KWAYA",
      ],
      name: "BILLIRI",
    },
    {
      wards: [
        "GOMBE ABBA",
        "HASHIDU",
        "JAMARI",
        "KUNDE",
        "LAFIYA",
        "MALALA",
        "WAZIRI NORTH",
        "WAZIRI SOUTH / CENTRAL",
        "WURO TALE",
        "ZANGE",
        "ZAUNE",
      ],
      name: "DUKKU",
    },
    {
      wards: [
        "ASHAKA / MAGABA",
        "BAGE",
        "BAJOGA  WEST",
        "BAJOGA EAST",
        "BODOR / TILDE",
        "JILLAHI",
        "KUPTO",
        "RIBADU",
        "TONGO",
        "WAWA / WAKKULUTU",
      ],
      name: "FUNAKAYE",
    },
    {
      wards: [
        "AJIYA",
        "BAJOGA",
        "BOLARI EAST",
        "BOLARI WEST",
        "DAWAKI",
        "HERWAGANA",
        "JEKA DAFARI",
        "KUMBIYA - KUMBIYA",
        "NASARAWA",
        "PANTAMI",
        "SHAMAKI",
      ],
      name: "GOMBE",
    },
    {
      wards: [
        "AWAK",
        "BULE / KALTIN",
        "KALTUNGO EAST",
        "KALTUNGO WEST",
        "KAMO",
        "TULA - YIRI",
        "TULA BAULE",
        "TULA WANGE",
        "TUNGO",
        "TURE",
      ],
      name: "KALTUNGO",
    },
    {
      wards: [
        "BOJUDE",
        "DABAN FULANI",
        "DOHO",
        "DUKUL",
        "GADAM",
        "JURARA",
        "KOMFULATA",
        "KWAMI",
        "MALAM SIDI",
        "MALLERI",
      ],
      name: "KWAMI",
    },
    {
      wards: [
        "BARWO / NASARAWO",
        "BARWO WINDE",
        "BIRIN BOLEWA",
        "BIRIN FULANI EAST",
        "BIRIN FULANI WEST",
        "GUDUKKU",
        "JIGAWA",
        "NAFADA CENTRAL",
        "NAFADA EAST",
        "NAFADA WEST",
      ],
      name: "NAFADA",
    },
    {
      wards: [
        "BANGUNJI",
        "BOH",
        "BURAK",
        "FILIYA",
        "GUNDALE",
        "GWANDUM",
        "KULISHIN",
        "KUSHI",
        "LALAIPIDO",
        "LAPAN",
      ],
      name: "SHONGOM",
    },
    {
      wards: [
        "DEBA",
        "DIFA / LUBO / KINAFA",
        "GWANI / SHINGA / WADE",
        "HINNA",
        "JAGALI NORTH",
        "JAGALI SOUTH",
        "KANAWA / WAJARI",
        "KURI /LANO / LAMBAM",
        "KWADON / LIJI / KURBA",
        "NONO / KUNWAL / W. BIRDEKA",
        "ZAMBUL / KWALI",
      ],
      name: "YALMALTU/ DEBA",
    },
  ],
};

export const GOMBE = { states, SR };
