const SR = {
  name: "IMO",
  email: "Imo@apcaims.com",
  password: "imo_ui2",
  phone: "08108850572",
  statecode: "IMO",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "IMO",
  state: "IMO",
  lga: [
    {
      wards: [
        "AMUZU",
        "ENYIOGUGU",
        "IBEKU",
        "LAGWA",
        "LORJI",
        "MBUTU",
        "NGURU-AHIATO",
        "NGURU-NWEKE",
        "NGURU-NWENKWO",
        "UMUHU",
        "UVURU 1",
        "UVURU II",
      ],
      name: "ABOH MBAISE",
    },
    {
      wards: [
        "AMUZI/IHENWORIE",
        "MPAM",
        "NNARAMBIA",
        "OBOHIA/EKWEREAZU",
        "OGBE",
        "OGBOR/UMUEZE",
        "OKIRIKA NWEKE",
        "OKIRIKA NWENKWO",
        "OPARANADIM",
        "ORU-NA-LUDE",
        "OTULU/AGUNEZE",
        "UMUNUMO/UMUCHIEZE",
      ],
      name: "AHIAZU MBAISE",
    },
    {
      wards: [
        "AGBAJA",
        "NSU 'A' IKPE",
        "NSU 'B' IHITTE",
        "NZEREM/IKPEM",
        "UMUALUMAKU/UMUIHIM",
        "UMUEZE I",
        "UMUEZE II/UMUELEKE",
        "UMUEZEALA",
        "UMUKABIA",
        "UMUNAKANU",
        "UMUNUMO",
      ],
      name: "EHIME MBANO",
    },
    {
      wards: [
        "AMUMARA",
        "CHOKONEZE/AKPODIM/IFE",
        "EZIUDO",
        "IHITTE",
        "ITU",
        "OBOAMA/UMUNAMA",
        "OKPOFE / EZEAGBOGU",
        "ONICHA I",
        "ONICHA II",
        "ONICHA III",
        "ONICHA IV",
        "UDO-NA-OBIZI",
      ],
      name: "EZINIHITTE MBAISE",
    },
    {
      wards: [
        "AKPULU",
        "AKWU OWERRE",
        "EZEMAZU/OZU",
        "ISIOKPO",
        "IZUOGU I",
        "IZUOGU II",
        "NDI IHEME ARONDIZUOGU",
        "NDIMOKO",
        "OBODOUKWU",
        "OSINA",
        "OZUAKOKI/UMUAGO",
        "UMUOKWARA/UMUEZEAGA",
        "UMUOPIA/UMUKEGWU",
        "UZII/UMUALOMA",
      ],
      name: "IDEATO NORTH",
    },
    {
      wards: [
        "AMANATOR/UMUESHI",
        "DIKENAFAI",
        "ISIEKENESI I",
        "ISIEKENESI II",
        "NTUEKE",
        "OBIOHIA",
        "OGBOKO I",
        "OGBOKO II",
        "UGBELLE",
        "UMUAKAM/UMUAGO",
        "UMUCHIMA",
        "UMUMA ISIAKU",
        "UMUOBOM",
      ],
      name: "IDEATO SOUTH",
    },
    {
      wards: [
        "ABUEKE",
        "AMAINYI",
        "AMAKOHIA",
        "ATONERIM",
        "AWUCHINUMO",
        "DIMNEZE",
        "IKPEREJERE",
        "OKATA",
        "UMUEZEGWU",
        "UMUIHI",
      ],
      name: "IHITTE/UBOMA (ISINWEKE)",
    },
    {
      wards: [
        "AKABO",
        "AMAIMO",
        "AMAKOHIA",
        "AMATTA",
        "ATTA I",
        "ATTA II",
        "AVUVU",
        "IHO",
        "INYISHI/UMUDIM",
        "NGUGO/IKEMBARA",
        "UGIRIKE / OKWU / EZIAMA",
        "UZOAGBA",
      ],
      name: "IKEDURU (IHO)",
    },
    {
      wards: [
        "AMARAKU",
        "AMAUZARI",
        "IBEME",
        "OBOLLO",
        "OGBOR",
        "OSU-ACHARA",
        "OSU-OWERRE I",
        "OSU-OWERRE II",
        "OSUAMA/ANARA",
        "UGIRI/OKA",
        "UMUNKWO",
        "UMUOZU",
      ],
      name: "ISIALA MBANO (UMUELEMAI)",
    },
    {
      wards: [
        "AMANDUGBA I",
        "AMANDUGBA II",
        "AMURIE OMANZE I",
        "AMURIE OMANZE II",
        "EKWE I",
        "EKWE II",
        "ISU NJABA III",
        "ISU-NJABA I",
        "ISU-NJABA II",
        "UMUNDUGBA I",
        "UMUNDUGBA II",
      ],
      name: "ISU (UMUNDUGBA)",
    },
    {
      wards: [
        "AFARA/EZIAMA",
        "AMAIKE MBIERI",
        "EZINIHITIE MBIERI",
        "IFAKALA",
        "OGBAKU",
        "OGWA I",
        "OGWA II",
        "ORODO 'A'",
        "ORODO 'B'",
        "UBOMIRI",
        "UMUNOHA/AZARA",
        "UMUNWOHA/MBIERI/UMUAWU",
      ],
      name: "MBAITOLI (NWAORIEUBI)",
    },
    {
      wards: [
        "AMALA/ALULU/OBURU/OBOKWE/NTU",
        "ELELEM/OBIKE",
        "EZIAMA/OKPALA",
        "IMERIENWE",
        "LOGARA/UMUOHIAGU",
        "NGOR/IHITTE/UMUKABIA",
        "NGURU/UMUOWA",
        "OBIANGWU",
        "OHEKELEM NNORIE",
        "OZUZU",
        "UMUHU",
      ],
      name: "NGOR OKPALA (UMUNEKE)",
    },
    {
      wards: [
        "AMUCHA I",
        "AMUCHA II",
        "ATTA I",
        "ATTA II",
        "ATTA III",
        "NKUME",
        "OKWUDOR",
        "UMUAKA I",
        "UMUAKA II",
        "UMUAKA III",
        "UMUAKA IV",
      ],
      name: "NJABA (NNENASA)",
    },
    {
      wards: [
        "AMAOKPARA",
        "EZIAMA OBAIRE",
        "NKWERRE IV (UMUNUBO/UMUNACHI)",
        "NKWERRE V",
        "NNANANO (NKWERRE II)",
        "ONUSA",
        "OWERRE NKWORJI I",
        "OWERRE NKWORJI II",
        "UMUDI/UMUWALA",
        "UMUKOR (NKWERRE III)",
      ],
      name: "NKWERRE",
    },
    {
      wards: [
        "ABAJAH WARD I",
        "ABAJAH WARD II",
        "ABBA WARD",
        "AMAJU COMMUNITY WARD (AMAIGBO III)",
        "AMAMNAISI (AMAIGBO IV)",
        "AMANO/UMUDURUMBA WARD (AMAIGBO I)",
        "DIM-NA NUME",
        "EZEOBOLO/OFEAHIA/DURUOHA/UMUKABIA (AMAIGBO WARD V)",
        "KARA-NA-ORLU",
        "UMUANU COMMUNITY WARD (AMAIGBO II)",
        "UMUOZU WARD",
      ],
      name: "NWANGELE (ONU-NWANGELE AMAIGBO)",
    },
    {
      wards: [
        "ALIKE",
        "AMANZE/UMUNGWA",
        "AMUZI",
        "AVUTU",
        "EHUME",
        "ODENKUME/UMUOSOCHIE",
        "OKENALOGHO",
        "OKWUOHIA",
        "UMUARIAM/ACHARA",
        "UMUNACHI",
      ],
      name: "OBOWO (OTOKO)",
    },
    {
      wards: [
        "AWA",
        "EGWE/EGBUOMA",
        "IZOMBE",
        "MBALA/UBA",
        "NDEULOUKWU/UMUOWERE",
        "OBUDI/ARO",
        "OGUTA 'A'",
        "OGUTA 'B'",
        "ORU",
        "OSSEMOTOR/ENUIGBO",
        "UWAORIE",
      ],
      name: "OGUTA (OGUTA)",
    },
    {
      wards: [
        "ASSA/OBILE",
        "AWARA/IKWEREDE",
        "EGBEMA 'A'",
        "EGBEMA 'B'",
        "EGBEMA 'C'",
        "EGBEMA 'D'",
        "EGBEMA 'E'",
        "EKWUATO",
        "OBITTI/MGBISHI",
        "OHOBA",
        "UMUAGWO",
        "UMUAPU",
      ],
      name: "OHAJI/EGBEMA (MMAHU-EGBEMA)",
    },
    {
      wards: [
        "AGBOBU",
        "AKU",
        "AMURO",
        "EZINACHI",
        "IHUBE",
        "NDIMOKO OFEIMO/IBINTA/OKANACHI/UMUOWA IBU",
        "OGII",
        "OKIGWE I",
        "OKIGWE II",
        "UMUALUMUOKE",
        "UMULOLO",
      ],
      name: "OKIGWE (OKIGWE)",
    },
    {
      wards: [
        "ABOH/OKOHIA",
        "EZELU",
        "EZIAMA",
        "OFEAHIA / UMUANUMEZE",
        "OKWELLE I",
        "OKWELLE II",
        "OWERRE-OKWE",
        "OZIMO / UMUNEZE",
        "UMUCHEKE",
        "UMUNA",
      ],
      name: "ONUIMO (OKWE)",
    },
    {
      wards: [
        "AMAIFEKE",
        "EBENESE/UMUEZE/NNACHI IHIOMA",
        "EZIACHI/AMIKE",
        "IHITE OWERRE",
        "OGBERURU/OBIBI",
        "OHAFOR/OKPORO/UMUTANZE",
        "OKAEKE/OKPORO",
        "OKWUA BALA/IHIOMA",
        "ORLU/MGBEE/ORLU GOVT. STATION",
        "OWERRI EBEIRI",
        "UMUDIOKA",
        "UMUNA",
        "UMUZIKE/UMUOWA",
      ],
      name: "ORLU",
    },
    {
      wards: [
        "AMARURU",
        "ASSAH UBIRI ELEM",
        "EBENATOR",
        "EZIAWA",
        "IHITENANSA",
        "OKWUAMARAIHIE I",
        "OKWUAMARAIHIE II",
        "OKWUETITI",
        "OKWUFURUAKU",
        "ORSU IHITEUKWA",
        "UMUHU OKABIA",
      ],
      name: "ORSU (AWO IDEMILI)",
    },
    {
      wards: [
        "AJI",
        "AMAFUO",
        "IBIASO EGBE",
        "MGBIDI I",
        "MGBIDI II",
        "NEMPI/ELEM",
        "OHAKPU",
        "OTULU",
        "OZARA",
        "UBULU",
      ],
      name: "ORU WEST (MGBIDI)",
    },
    {
      wards: [
        "AKATA",
        "AKUMA",
        "AMAGU",
        "AMIRI I",
        "AMIRI II",
        "AWO-OMAMMA I",
        "AWO-OMAMMA II",
        "AWO-OMAMMA III",
        "AWO-OMAMMA IV",
        "OMUMA",
      ],
      name: "ORU-EAST",
    },
    {
      wards: [
        "AGBALA/OBUBE/ULAKWO",
        "AWAKA/IHITTE-OGADA",
        "EGBU",
        "EMEKUKU I",
        "EMEKUKU II",
        "EMII",
        "IHITTA-OHA",
        "NAZE",
        "OBIBI-URATTA I",
        "OBIBI-URATTA II",
        "OBIBIEZENA",
        "ORJI",
      ],
      name: "OWERRI NORTH (ORIE URATTA)",
    },
    {
      wards: [
        "ALADINMA I",
        "ALADINMA II",
        "AZUZI I",
        "AZUZI II",
        "AZUZI III",
        "AZUZI IV",
        "GRA",
        "IKENEGBU I",
        "IKENEGBU II",
        "NEW OWERRI I",
        "NEW OWERRI II",
      ],
      name: "OWERRI URBAN (OWERRI)",
    },
    {
      wards: [
        "AMAKOHIA-UBI/NDEGWU OHII",
        "AVU/OFOROLA",
        "EMEABIAM/OKOLOCHI",
        "EZIOBODO",
        "IHIAGWA",
        "IRETE/OROGWE",
        "NEKEDE",
        "OBINZE",
        "OKUKU",
        "UMUGUMA",
      ],
      name: "OWERRI WEST (UMUGUMA)",
    },
  ],
};

export const IMO = { states, SR };
