const SR = {
  name: "KADUNA",
  email: "Kaduna@apcaims.com",
  password: "kaduna_66fc",
  phone: "08108850572",
  statecode: "KADUNA",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "KADUNA",
  state: "KADUNA",
  lga: [
    {
      wards: [
        "DOGON DAWA",
        "GAYAM",
        "KAKANGI",
        "KAZAGE",
        "KUTEMESI",
        "KUYELO",
        "MAGAJIN GARI I",
        "MAGAJIN GARI II",
        "MAGAJIN GARI III",
        "RANDAGI",
        "TABANNI",
      ],
      name: "BIRNIN GWARI",
    },
    {
      wards: [
        "CHIKUN",
        "GWAGWADA",
        "KAKAU",
        "KUJAMA",
        "KUNAI",
        "KURIGA",
        "NARAYI",
        "NASARAWA",
        "RIDO",
        "S/GGARIN AREWA TIRKANIYA",
        "SABON TASHA",
        "UNG. YELWA",
      ],
      name: "CHIKUN",
    },
    {
      wards: [
        "DANMAHAWAYI",
        "GALADIMAWA",
        "GANGARA",
        "GIWA",
        "IDASU",
        "KADAGE",
        "KAKANGI",
        "KIDANDAN",
        "PAN HAUYA",
        "SHIKA",
        "YAKAWADA",
      ],
      name: "GWIWA",
    },
    {
      wards: [
        "AFAKA",
        "BIRNIN YERO",
        "GADAN GAYAN",
        "GWARAJI",
        "IGABI",
        "KERAWA",
        "KWARAU",
        "RIGACHIKUN",
        "RIGASA",
        "SABON BIRNIN DAJI",
        "TURUNKU",
        "ZANGON AYA",
      ],
      name: "IGABI",
    },
    {
      wards: [
        "AUCHAN",
        "IKARA",
        "JANFALA",
        "K/KOGI",
        "KUYA",
        "PAKI",
        "PALA",
        "RUMI",
        "SAULAWA",
        "SAYA-SAYA",
      ],
      name: "IKARA",
    },
    {
      wards: [
        "CHORI",
        "DADDU",
        "DURA/BITARO",
        "FADA",
        "FAI",
        "NDUYAH",
        "NOK",
        "SABCHEM",
        "SABZURO",
        "SAMBAM",
      ],
      name: "JABA",
    },
    {
      wards: [
        "ASSO",
        "ATUKU",
        "BEDDE",
        "GIDAN WAYA",
        "GODOGODO",
        "JAGINDI",
        "KAFANCHAN 'A'",
        "KAFANCHAN 'B'",
        "KAGOMA",
        "KANINKON",
        "MAIGIZO 'A'",
        "TAKAU 'B'",
      ],
      name: "JEMA'A",
    },
    {
      wards: [
        "AGUNU",
        "ANKWA",
        "AWON",
        "BISHINI",
        "DOKA",
        "GIDAN TAGWAI",
        "GUMEL",
        "KACHIA URBAN",
        "KATARI",
        "KURMIN MUSA",
        "KWATURU",
        "SABON SARKI",
      ],
      name: "KACHIA",
    },
    {
      wards: [
        "BADARAWA",
        "GABASAWA",
        "GAJI",
        "HAYIN BANKI",
        "KABALA COSTAIN/ DOKI",
        "KAWO",
        "MAIBURJI",
        "SHABA",
        "UNGUWAN DOSA",
        "UNGUWAN LIMAN",
        "UNGUWAN SARKI",
        "UNGUWAN SHANU",
      ],
      name: "KADUNA NORTH",
    },
    {
      wards: [
        "BADIKO",
        "BARNAWA",
        "KAKURI GWARI",
        "KAKURI HAUSA",
        "MAKERA",
        "SABON GARI NORTH",
        "SABON GARI SOUTH",
        "TELEVISION",
        "TUDUN NUWAPA",
        "TUDUN WADA NORTH",
        "TUDUN WADA SOUTH",
        "TUDUN WADA WEST",
        "UNG. SANUSI",
      ],
      name: "KADUNA SOUTH",
    },
    {
      wards: [
        "ARIBI",
        "IDDAH",
        "JERE NORTH",
        "JERE SOUTH",
        "KAGARKO NORTH",
        "KAGARKO SOUTH",
        "KATUGAL",
        "KUKUI",
        "KURMIN JIBRIN",
        "KUSHE",
      ],
      name: "KAGARKO",
    },
    {
      wards: [
        "AFOGO",
        "BUDA",
        "IDON",
        "KAJURU",
        "KALLAH",
        "KASUWAN MAGANI",
        "KUFANA",
        "MARO",
        "RIMAU",
        "TANTATU",
      ],
      name: "KAJURU",
    },
    {
      wards: [
        "AGBAN",
        "BONDON",
        "FADA",
        "KADARKO",
        "KAURA",
        "KPAK",
        "KUKUM",
        "MALLAGUM",
        "MANCHOK",
        "ZANKAN",
      ],
      name: "KAURA",
    },
    {
      wards: [
        "BADURUM SAMA",
        "BITAL",
        "DAMAKASUWA",
        "DAWAKI",
        "GESHERE",
        "KAMARU",
        "KAURU EAST",
        "KAURU WEST",
        "KWASSAM",
        "MAKAMI",
        "PARI",
      ],
      name: "KAURU",
    },
    {
      wards: [
        "ANCHAU",
        "DAMAU",
        "DUTSEN WAI",
        "HASKIYA",
        "KARGI",
        "KARREH",
        "KUBAU",
        "MAH",
        "PAMBEGUA",
        "ZABI",
        "ZUNTU",
      ],
      name: "KUBAU",
    },
    {
      wards: [
        "DOKA",
        "GARU",
        "HUNKUYI",
        "KAURAN WALI NORTH",
        "KAURAN WALI SOUTH",
        "KUDAN",
        "LIKORO",
        "SABON GARI HUNKUYI",
        "TABAN SANI",
        "ZABI",
      ],
      name: "KUDAN",
    },
    {
      wards: [
        "ABADAWA",
        "DAN ALHAJI",
        "GARU",
        "GURE/KAHUGU",
        "KAYARDA",
        "LAZURU",
        "LERE",
        "RAMIN KURA",
        "SABON BIRNIN",
        "SAMINAKA",
        "YAR KASUWA",
      ],
      name: "LERE",
    },
    {
      wards: [
        "DANDAMISA",
        "DANGUZIRI",
        "GAZARA",
        "GIMI",
        "GUBUCHI",
        "GWANKI",
        "MAKARFI",
        "MAYERE",
        "NASSARWAN DOYA",
        "TUDUN WADA",
      ],
      name: "MAKARFI",
    },
    {
      wards: [
        "BASAWA",
        "BOMO",
        "CHIKAJI",
        "DOGARAWA",
        "HANWA",
        "JAMA'A",
        "JUSHIN WAJE",
        "MUCHIA",
        "SAMARU",
        "UNGUWAN GABAS",
        "ZABI",
      ],
      name: "SABON GARI",
    },
    {
      wards: [
        "ABORO",
        "ARAK",
        "AYU",
        "BOKANA",
        "FADAN KARSHI",
        "GWANTU",
        "NANDU",
        "NINZAM NORTH",
        "NINZAM SOUTH",
        "NINZAM WEST",
        "WASA STATION",
      ],
      name: "SANGA",
    },
    {
      wards: [
        "DAN WATA",
        "GAMAGIRA",
        "GARUN GWANKI",
        "GIMBA",
        "KINKIBA",
        "KWASSALLO",
        "MAIGANA",
        "RAHAMA",
        "RICHIFA",
        "SOBA",
        "TURAWA",
      ],
      name: "SOBA",
    },
    {
      wards: [
        "GIDAN JATAU",
        "GORA",
        "KAMANTAN",
        "KAMURU IKULU NORTH",
        "MADAKIYA",
        "UNGUWAR GAIYA",
        "UNGUWAR RIMI",
        "ZAMAN DABO",
        "ZANGO URBAN",
        "ZONKWA",
        "ZONZON",
      ],
      name: "ZANGON KATAF",
    },
    {
      wards: [
        "DAMBO",
        "DUTSEN ABBA",
        "GYALLESU",
        "KAURA",
        "KUFENA",
        "KWARBAI 'A'",
        "KWARBAI 'B'",
        "LIMANCIN-KONA",
        "TUDUN WADA",
        "TUKUR TUKUR",
        "UNG. FATIKA",
        "UNG. JUMA",
        "WUCICCIRI",
      ],
      name: "ZARIA",
    },
  ],
};

export const KADUNA = { states, SR };
