const SR = {
  name: "KANO",
  email: "Kano@apcaims.com",
  password: "kano_b6y",
  phone: "08108850572",
  statecode: "KANO",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "KANO",
  state: "KANO",
  lga: [
    {
      wards: [
        "AJINGI",
        "BALARE",
        "CHULA",
        "DABIN KANAWA",
        "DUNDUN",
        "GAFASA",
        "GURDUBA",
        "KUNKURAWA",
        "TORANKE",
        "UNGAWAR BAI",
      ],
      name: "AJINGI",
    },
    {
      wards: [
        "ALBASU CENTRAL",
        "BATAIYA",
        "CHAMARANA",
        "DAHO",
        "FANDA",
        "FARAGAI",
        "GAGARAME",
        "HUNGU",
        "SAYA-SAYA",
        "TSANGAYA",
      ],
      name: "ALBASU",
    },
    {
      wards: [
        "BAGWAI",
        "DANGADA",
        "GADANYA",
        "GOGORI",
        "KIYAWA",
        "KWAJALI",
        "RIMIN DAKO",
        "ROMO",
        "SARE-SARE",
        "WURO BAGGA",
      ],
      name: "BAGWAI",
    },
    {
      wards: [
        "ANADARIYA",
        "BAGUDA",
        "BEBEJI",
        "DAMAU",
        "DURMAWA",
        "GARGAI",
        "GWARMAI",
        "KOFA",
        "KUKI",
        "RAHAMA",
        "RANKA",
        "RANTAN",
        "TARIWA",
        "WAK",
      ],
      name: "BEBEJI",
    },
    {
      wards: [
        "BADUME",
        "BICHI",
        "DANZABUWA",
        "FAGOLO",
        "KAUKAU",
        "KWAMARAWA",
        "KYALLI",
        "MUNTSIRA",
        "SAYE",
        "WAIRE",
        "YALLAMI",
      ],
      name: "BICHI",
    },
    {
      wards: [
        "BARKUM",
        "BONO",
        "BUNKURE",
        "CHIRIN",
        "GAFAN",
        "GURJIYA",
        "GWAMMA",
        "KULLUWA",
        "KUMURYA",
        "SANDA",
      ],
      name: "BUNKURE",
    },
    {
      wards: [
        "ADAKAWA",
        "BAKIN RUWA",
        "DALA",
        "DOGON NAMA",
        "GOBIRAWA",
        "GWAMMAJA",
        "KABUWAYA",
        "KANTUDU",
        "KOFAR MAZUGAL",
        "KOFAR RUWA",
        "MADIGAWA",
        "YALWA",
      ],
      name: "DALA",
    },
    {
      wards: [
        "AJUMAWA",
        "DANBATTA EAST",
        "DANBATTA WEST",
        "FAGWALAWA",
        "GORON MAJE",
        "GWANDA",
        "GWARABJAWA",
        "KORE",
        "SAIDAWA",
        "SANSAN",
      ],
      name: "DANBATTA",
    },
    {
      wards: [
        "DABAR KWARI",
        "DANBAGIWA",
        "DAWAKI",
        "DAWAKIJI",
        "DOSAN",
        "GANO",
        "GURJIYA",
        "JIDO",
        "TAMBURAWA",
        "TSAKUWA",
        "UNGUWAR DUNIYA",
        "YANBARAU",
        "YANKATSARI",
        "YARGAYA",
        "ZOGARAWA",
      ],
      name: "DAWAKI KUDU",
    },
    {
      wards: [
        "DAN GUGUWA",
        "DAWAKI EAST",
        "DAWAKI WEST",
        "DAWANAU",
        "GANDUJE",
        "GARGARI",
        "JALLI",
        "KWA",
        "MARKE",
        "TATTARAWA",
        "TUMFAFI",
      ],
      name: "DAWAKI TOFA",
    },
    {
      wards: [
        "DARIYA",
        "DOGON KAWO",
        "DUGUWA",
        "FALGORE",
        "MARAKU",
        "RAGADA",
        "RIRIWAI",
        "TAGWAYE",
        "UNGUWAR NATSOHUWA",
        "ZAINABI",
      ],
      name: "DOGUWA",
    },
    {
      wards: [
        "FAGGE A",
        "FAGGE B",
        "FAGGE C",
        "FAGGE D",
        "FAGGE E",
        "KWACHIRI",
        "RIJIYAR LEMO",
        "SABONGARI EAST",
        "SABONGARI WEST",
        "YAMMATA",
      ],
      name: "FAGGE",
    },
    {
      wards: [
        "GABASAWA",
        "GARUN DANGA",
        "JODA",
        "KARMAKI",
        "MEKIYA",
        "TARAUNI",
        "YANTAR AREWWA",
        "YAUTAR KUDU",
        "YUMBU",
        "ZAKIRAI",
        "ZUGACHI",
      ],
      name: "GABASAWA",
    },
    {
      wards: [
        "DAL",
        "GARIN ALI",
        "GARKO",
        "GURJIYA",
        "KAFIN MALAMAI",
        "KATUMARI",
        "KWAS",
        "RABA",
        "SARINA",
        "ZAKARAWA",
      ],
      name: "GARKO",
    },
    {
      wards: [
        "CHIROMAWA",
        "DORAWAR-SALLAU",
        "FANKURUN",
        "GARUN BABBA",
        "GARUN MALAM",
        "JOBAWA",
        "KADAWA",
        "MAKWARO",
        "YAD AKWARI",
        "YALWAN  YADAKWARI",
      ],
      name: "GURUN MALAM",
    },
    {
      wards: [
        "BALAN",
        "GAMARYA",
        "GAMOJI",
        "GAYA AREWA",
        "GAYA KUDU",
        "KADEMI",
        "KAZURAWA",
        "MAIMAKAWA",
        "SHAGOGO",
        "WUDILAWA",
      ],
      name: "GAYA",
    },
    {
      wards: [
        "BABAWA",
        "GAWO",
        "GEZAWA",
        "JOGANA",
        "KETAWA",
        "MESAR-TUDU",
        "SARARIN-GEZAWA",
        "TSAMIYA-BABBA",
        "TUMBAU",
        "WANGARA",
        "ZANGO",
      ],
      name: "GEZAWA",
    },
    {
      wards: [
        "DANDAGO",
        "DISO",
        "DORAYI",
        "GALADANCHI",
        "GORON DUTSE",
        "GWALE",
        "GYARANYA",
        "KABUGA",
        "MANDAWARI",
        "SANI MAI MAGGE",
      ],
      name: "GWALE",
    },
    {
      wards: [
        "GETSO",
        "GWARZO",
        "JAMA' A",
        "KARA",
        "KUTAMA",
        "LAKWAYA",
        "MADADI",
        "MAINIKA",
        "SABON BIRNI",
        "UNGUWAR TUDU",
      ],
      name: "GWARZO",
    },
    {
      wards: [
        "DUGABAU",
        "DURUN",
        "GAMMO",
        "GARO",
        "GODIYA",
        "GUDE",
        "HAUWADE",
        "KABO",
        "KANWA",
        "MASANAWA",
      ],
      name: "KABO",
    },
    {
      wards: [
        "CHEDI",
        "DAN'AGUNDI",
        "GANDUN ALBASA",
        "JAKARA",
        "KANKAROFI",
        "SHAHUCHI",
        "SHARADA",
        "SHESHE",
        "TUDUN NUFAWA",
        "TUDUN WAZIRCHI",
        "YAKASAI",
        "ZAITAWA",
        "ZANGO",
      ],
      name: "KANO MUNICIPAL",
    },
    {
      wards: [
        "DAURA",
        "KAFIN DAFGA",
        "KARAYE",
        "KURUGU",
        "KWANYAWA",
        "TUDUN KAYA",
        "TURAWA",
        "UNGUWAR HAJJI",
        "YAMMEDI",
        "YOLA",
      ],
      name: "KARAYE",
    },
    {
      wards: [
        "DURBA",
        "FAMMAR",
        "FASSI",
        "KADIGAWA",
        "KAHU",
        "KIBIYA  I",
        "KIBIYA II",
        "NARIYA",
        "TARAI",
        "UNGUWAR GAI",
      ],
      name: "KIBIYA",
    },
    {
      wards: [
        "BA'AWA",
        "BADAFI",
        "BARGONI",
        "BAUDA",
        "DANGORA",
        "DANSOHIYA",
        "DASHI",
        "GALADIMAWA",
        "KIRU",
        "KOGO",
        "MARAKU",
        "TSAUDAWA",
        "YAKO",
        "YALWA",
        "ZUWO",
      ],
      name: "KIRU",
    },
    {
      wards: [
        "CHALLAWA",
        "CHIRANCHI",
        "DANBARE",
        "DANMALIKI",
        "GURINGAWA",
        "KUMBOTSO",
        "KUREKEN SANI",
        "MARIRI",
        "NA'IBAWA",
        "PANSHEKARA",
        "UNGUWAR RIMI",
      ],
      name: "KUMBOTSO",
    },
    {
      wards: [
        "BUMAI",
        "GARIN SHEME",
        "GWARMAI",
        "KASUWAR KUKA",
        "KUNCHI",
        "MATAN FADA",
        "RIDAWA",
        "SHAMAKAWA",
        "SHUWAKI",
        "YANDADI",
      ],
      name: "KUNCHI",
    },
    {
      wards: [
        "DALILI",
        "DAN HASSAN",
        "DUKAWA",
        "GUNDUTSE",
        "KARFI",
        "KOSAWA",
        "KURA",
        "KURUNSUMAU",
        "RIGAR DUKA",
        "TANAWA",
      ],
      name: "KURA",
    },
    {
      wards: [
        "BURJI",
        "CINKOSO",
        "GALINJA",
        "GORA",
        "KAFIN AGUR",
        "KANWA",
        "KAURA MATA",
        "KUBARACI",
        "KWANKWASO",
        "MADOBI",
        "RIKADAWA",
      ],
      name: "MADOBI",
    },
    {
      wards: [
        "BABBAR RIGA",
        "DURMA",
        "JIBGA",
        "KADANDANI",
        "KOGUNA",
        "KOREN TATSO",
        "MAITSIDAU",
        "MAKODA",
        "SATAME",
        "TANGAJI",
        "WAILARE",
      ],
      name: "MAKODA",
    },
    {
      wards: [
        "AZORE",
        "GANDURWAWA",
        "KANTAMA",
        "KUNYA",
        "KURU",
        "KWARKIYA",
        "MINJIBIR",
        "SARBI",
        "TSAKIYA",
        "TSAKUWA",
        "WASAI",
      ],
      name: "MINJIBIR",
    },
    {
      wards: [
        "DAKATA",
        "GAMA",
        "GAWUNA",
        "GIGINYU",
        "GWAGWARWA",
        "HOTORO NORTH",
        "HOTORO SOUTH",
        "KAURA GOJE",
        "KAWAJI",
        "TUDUN MURTALA",
        "TUDUN WADA",
      ],
      name: "NASARAWA",
    },
    {
      wards: [
        "DAWAKI",
        "LAUSU",
        "MADACHI",
        "RANO",
        "RURUM SABON-GARI",
        "RURUM TSOHON-GARI",
        "SAJI",
        "YALWA",
        "ZINYAU",
        "ZURGU",
      ],
      name: "RANO",
    },
    {
      wards: [
        "BUTU-BUTU",
        "DAWAKI GULU",
        "DOKA DAWA",
        "DUGURAWA",
        "GULU",
        "JILI",
        "KAROFIN YASHI",
        "RIMIN GADO",
        "SAKARATSA",
        "TAMAWA",
        "YALWAN DANZIYAL",
        "ZANGO DAN ABDU",
      ],
      name: "RIMIN GADO",
    },
    {
      wards: [
        "BELI",
        "FALGORE",
        "FULATAN",
        "GWANGWAN",
        "JAJAYE",
        "ROGO RUMA",
        "ROGO SABON GARI",
        "RUWAN BAGO",
        "ZAREWA",
        "ZOZA",
      ],
      name: "ROGO",
    },
    {
      wards: [
        "ALAJAWA",
        "DUTSEN-BAKOSHI",
        "FARURUWA",
        "GORON DUTSE",
        "KADAMU",
        "KOKIYA",
        "LENI",
        "SHAKOGI",
        "SHANONO",
        "TSAURE",
      ],
      name: "SHANONO",
    },
    {
      wards: [
        "GALA",
        "GANI",
        "GARFA",
        "GEDIYA",
        "KANAWA",
        "MAGAMI",
        "MASU",
        "RIMI",
        "RUMO",
        "SITTI",
        "SUMAILA",
      ],
      name: "SUMAILA",
    },
    {
      wards: [
        "BAGWARO",
        "DURBUNDE",
        "FAJEWA",
        "FALALI",
        "FARURUWA",
        "KACHAKO",
        "KARFI",
        "KUKA",
        "TAKAI",
        "ZUGA",
      ],
      name: "TAKAI",
    },
    {
      wards: [
        "BABBAN GIJI",
        "DARMANAWA",
        "DAURAWA",
        "GYADI-GYADI AREWA",
        "GYADI-GYADI KUDU",
        "HOTORO (NNPC)",
        "KAUYEN  ALU",
        "TARAUNI",
        "UNGUWA  UKU",
        "UNGUWAR GANO",
      ],
      name: "TARAUNI",
    },
    {
      wards: [
        "DINDERE",
        "DOKA",
        "GAJIDA",
        "GINSAWA",
        "JANGUZA",
        "JAUBEN KUDU",
        "KWAMI",
        "LAMBU",
        "LANGEL",
        "TOFA",
        "UNGUWAR RIMI",
        "WANGARA",
        "YALWA KARAMA",
        "YANOKO",
        "YARIMAWA",
      ],
      name: "TOFA",
    },
    {
      wards: [
        "DADDARAWA",
        "DUNBULUN",
        "GOZAKI",
        "GURUN",
        "KABAGIWA",
        "TATSAN",
        "TSANYAWA",
        "YANGANAU",
        "YANKAMAYE",
        "ZAROGI",
      ],
      name: "TSANYAWA",
    },
    {
      wards: [
        "BABURI",
        "BURUMBURUM",
        "DALAWA",
        "JANDUTSE",
        "JITA",
        "KAREFA",
        "NATA'ALA",
        "SABON GARI",
        "SHUWAKI",
        "TSOHOGARI",
      ],
      name: "TUDUN WADA",
    },
    {
      wards: [
        "BACHIRAWA",
        "GAYAWA",
        "KADAWA",
        "KARO",
        "PANISAU",
        "RANGAZA",
        "RIJIYAR ZAKI",
        "TUDUN FULANI",
        "UNGOGO",
        "YADAKUNYA",
        "ZANGO",
      ],
      name: "UNGOGO",
    },
    {
      wards: [
        "AMARAWA",
        "DANLASAN",
        "GARIN DAU",
        "GOGEL",
        "IMAWA",
        "J/GALADIMA",
        "JEMAGU",
        "JIGAWA",
        "KATARKAWA",
        "MADARI MATA",
        "TAMBURAWAR GABAS",
        "TANGAR",
        "WARAWA",
        "YAN DALLA",
        "YANGIZO",
      ],
      name: "WARAWA",
    },
    {
      wards: [
        "ACHIKA",
        "DAGUMAWA",
        "DANKAZA",
        "DARKI",
        "INDABO",
        "KAUSANI",
        "LAJAWA",
        "SABON GARI",
        "UTAI",
        "WUDIL",
      ],
      name: "WUDIL",
    },
  ],
};

export const KANO = { states, SR };
