const SR = {
  name: "KATSINA",
  email: "Katsina@apcaims.com",
  password: "katsina_6np",
  phone: "08108850572",
  statecode: "KATSINA",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "KATSINA",
  state: "KATSINA",
  lga: [
    {
      wards: [
        "BAKORI A",
        "BAKORI B",
        "BARDE/KWANTAKWARAN",
        "DAWAN MUSA",
        "GUGA",
        "JARGABA",
        "KABOMO",
        "KAKUMI",
        "KANDARAWA",
        "KURAMI/YANKWANI",
        "TSIGA",
      ],
      name: "BAKORI",
    },
    {
      wards: [
        "AJIWA",
        "BAKIYAWA",
        "BARAWA",
        "BATAGARAWA A",
        "BATAGARAWA B",
        "DANDAGORO",
        "JINO",
        "KAYAUKI",
        "TSANNI",
        "YARGAMJI",
      ],
      name: "BATAGARAWA",
    },
    {
      wards: [
        "ABADAU/KAGARA",
        "BATSARI",
        "DAN. ALH/YANGAIYA",
        "DARINI/MAGAJI/ABU",
        "KANDAWA",
        "KARARE",
        "MADOGARA",
        "MANAWA",
        "RUMA",
        "WAGINI",
        "YAUYAU/MALLAMAWA",
      ],
      name: "BATSARI",
    },
    {
      wards: [
        "AGALA",
        "BABBAN MUTUM",
        "BAURE",
        "GARKI",
        "HUI",
        "KAGARA/FASKI",
        "MAI BARA",
        "MUDURI",
        "TARAMNAWA/BARE",
        "UNGUWAR RAI",
        "YANDUNA",
        "YANMAULU",
      ],
      name: "BAURE",
    },
    {
      wards: [
        "BAURE",
        "BINDAWA",
        "DORO",
        "FARU/DALLAJI",
        "GAIWA",
        "GIREMAWA",
        "JIBAWA/R,BADE",
        "KAMRI",
        "SHIBDAWA",
        "TAMA/DAYE",
        "YANGORA",
      ],
      name: "BINDAWA",
    },
    {
      wards: [
        "BANYE",
        "CHARANCHI",
        "DOKA",
        "GANUWA",
        "KODA",
        "KURAYE",
        "MAJEN WAYYA",
        "RADDA",
        "SAFANA",
        "TSAKATSA",
      ],
      name: "CHARANCHI",
    },
    {
      wards: [
        "DAN ALI",
        "DAN ALKIMA",
        "DAN MUSA A",
        "DAN MUSA B",
        "DANDIRE 'B'",
        "DANDIRE A",
        "MAI DABINO A",
        "MAI DABINO B",
        "MARA",
        "YAN-TUMAKI A",
        "YAN-TUMAKI B",
      ],
      name: "DANMUSA",
    },
    {
      wards: [
        "DANDUME A",
        "DANDUME B",
        "DANTANKARI",
        "MAGAJI WANDO A",
        "MAGAJI WANDO B",
        "MAHUTA A",
        "MAHUTA B",
        "MAHUTA C",
        "NASARAWA",
        "TUMBURKAI A",
        "TUMBURKAI B",
      ],
      name: "DANDUME",
    },
    {
      wards: [
        "DABAI",
        "DANJA A",
        "DANJA B",
        "JIBA",
        "KAHUTU A",
        "KAHUTU B",
        "TANDAMA",
        "TSANGAMAWA",
        "YAKAJI A",
        "YAKAJI B",
      ],
      name: "DANJA",
    },
    {
      wards: [
        "KUSUGU",
        "MADOBI A",
        "MADOBI B",
        "MAZOJI A",
        "MAZOJI B",
        "SABON GARI",
        "SARKIN YARA A",
        "SARKIN YARA B",
        "TUDUN WADA",
        "UBANDAWAKI A",
        "UNBADAWAKI B",
      ],
      name: "DAURA",
    },
    {
      wards: [
        "DAN AUNAI",
        "DUTSI A",
        "DUTSI B",
        "KAYAWA",
        "RUWANKAYA A",
        "RUWANKAYA B",
        "SIRIKA A",
        "SIRIKA B",
        "YAMEL A",
        "YAMEL B",
      ],
      name: "DUTSI",
    },
    {
      wards: [
        "BAGAGADI",
        "DABAWA",
        "DUTSIN-MA A",
        "DUTSIN-MA B",
        "KAROFI A",
        "KAROFI B",
        "KUKI A",
        "KUKI B",
        "KUTAWA",
        "MAKERA",
        "SHEMA",
      ],
      name: "DUTSIN-MA",
    },
    {
      wards: [
        "DAUDAWA",
        "FASKARI",
        "MAIGORA",
        "MAIRUWA",
        "RUWAN GODIYA",
        "SABONLAYI/GALADIMA",
        "SHEME",
        "TAFOKI",
        "YANKARA",
        "YARMALAMAI",
      ],
      name: "FASKARI",
    },
    {
      wards: [
        "DANDUTSE",
        "DUKKE",
        "GOYA",
        "MAI GAMJI",
        "MAKERA",
        "MASKA",
        "SABON GARI",
        "TUDUN IYA",
        "UNG IBRAHIM",
        "UNGUWAR MUSA",
        "UNGUWAR RABIU",
      ],
      name: "FUNTUA",
    },
    {
      wards: [
        "AGAYAWA",
        "BARERUWA/RURUMA",
        "BIDORE/YAYA",
        "DARA",
        "DAUNAKA/B.KWARI",
        "DUGUL",
        "INGAWA",
        "JOBE/KANDAWA",
        "KURFEJI/YANKAURA",
        "MANOMAWA/KAFI",
        "YANDOMA",
      ],
      name: "INGAWA",
    },
    {
      wards: [
        "BUGAJE",
        "FARFARU",
        "FARU",
        "G/BAURE/MALLAMAWA",
        "GANGARA",
        "JIBIA A",
        "JIBIA B",
        "KUSA",
        "MAZANYA/MAGAMA",
        "RIKO",
        "YANGAIYA",
      ],
      name: "JIBIA",
    },
    {
      wards: [
        "DANTUTTURE",
        "DUTSIN KURA/KANYA",
        "GAMZAGO",
        "GOZAKI",
        "KAFUR",
        "MAHUTA",
        "MASARI",
        "SABUWAR KASA",
        "YARI BORI",
        "YARTALATA/RIGOJI",
      ],
      name: "KAFUR",
    },
    {
      wards: [
        "ABDALLAWA",
        "BAAWA",
        "DANKABA",
        "DANKAMA",
        "GAFIYA",
        "GIRKA",
        "KAITA",
        "MATSAI",
        "YANDAKI",
        "YANHOHO",
      ],
      name: "KAITA",
    },
    {
      wards: [
        "BURDUGAU",
        "DAN MURABU",
        "DAN'MAIDAKI",
        "GARAGI",
        "GATAKAWA S/GARI/MABAI",
        "HURYA",
        "KANKARA A&B",
        "KUKASHEKA",
        "PAUWA A&B",
        "WAWAR KAZA",
        "ZANGO/ZABARO",
      ],
      name: "KANKARA",
    },
    {
      wards: [
        "GACHI",
        "GALADIMA 'A'",
        "GALADIMA 'B'",
        "KAFIN DANGI/FAKUWA",
        "KAFINSOLI",
        "KUNDURU/GYAZA",
        "MAGAM/TSA",
        "RIMAYE",
        "SUKUNTUNI",
        "TAFASHIYA/NASARAWA",
      ],
      name: "KANKIA",
    },
    {
      wards: [
        "KANGIWA",
        "SHINKAFI 'A",
        "SHINKAFI 'B'",
        "WAKILI KUDU III",
        "WAKILIN AREWA (A)",
        "WAKILIN AREWA (B)",
        "WAKILIN GABAS I",
        "WAKILIN GABAS II",
        "WAKILIN KUDU I",
        "WAKILIN KUDU II",
        "WAKILIN YAMMA 1",
        "WAKILIN YAMMA 1I",
      ],
      name: "KATSINA",
    },
    {
      wards: [
        "BARKIYYA",
        "BIRCHI",
        "KURFI 'A'",
        "KURFI 'B'",
        "RAWAYAU 'A'",
        "RAWAYAU 'B'",
        "TSAURI 'A'",
        "TSAURI 'B'",
        "WURMA 'A'",
        "WURMA 'B'",
      ],
      name: "KURFI",
    },
    {
      wards: [
        "BAURANYA 'A'",
        "BAURANYA 'B'",
        "BOKO",
        "DUDUNNI",
        "KAIKAI",
        "KOFA",
        "KUSADA",
        "MAWASHI",
        "YASHE 'A",
        "YASHE 'B'",
      ],
      name: "KUSADA",
    },
    {
      wards: [
        "BUMBUM 'A'",
        "BUMBUM 'B'",
        "DANYASHE",
        "KOZA",
        "MAI KONI 'A'",
        "MAI KONI 'B'",
        "MAI'ADUA 'A'",
        "MAI'ADUA 'B'",
        "MAI'ADUA 'C'",
        "NATSALLE",
      ],
      name: "MAI'ADUA",
    },
    {
      wards: [
        "BORIN DAWA",
        "DANSARAI",
        "DAYI",
        "GORAR DANSAKA",
        "KARFI",
        "MAKAURACHI",
        "MALUM FASHI 'A'",
        "MALUM FASHI 'B'",
        "NA-ALMA",
        "RAWAN SANYI",
        "YABA",
        "YARMAMA",
      ],
      name: "MALUFASHI",
    },
    {
      wards: [
        "BAGIWA",
        "BUJAWA/GEWAYAU",
        "DUWAN/MAKAU",
        "HAMCHETA",
        "JANI",
        "KWATTA",
        "MACHIKA",
        "MAGAMI",
        "MANI",
        "MUDURU",
        "TSAGEM/TAKUSHEYI",
      ],
      name: "MANI",
    },
    {
      wards: [
        "BAMBLE",
        "DOGURU 'A'",
        "DOGURU 'B'",
        "GALLU",
        "JIGAWA",
        "KARAU",
        "MASHI",
        "S/RIJIYA",
        "SONKAYA",
        "TAMILO 'A'",
        "TAMILO 'B'",
      ],
      name: "MASHI",
    },
    {
      wards: [
        "DISSI",
        "GWARJO",
        "KARADUWA",
        "KOGARI",
        "MATAZU 'A",
        "MATAZU 'B'",
        "MAZOJI 'A'",
        "MAZOJI 'B'",
        "RINJIN IDI",
        "SAYAYA",
      ],
      name: "MATAZU",
    },
    {
      wards: [
        "DANGANI",
        "DANJANKU/KARACHI",
        "GARU",
        "GINGIN",
        "JIKAMSHI",
        "KIRA",
        "KURKUJAN 'A'",
        "KURKUJAN 'B'",
        "MUSAWA",
        "TUGE",
        "YARADAU/TABANNI",
      ],
      name: "MUSAWA",
    },
    {
      wards: [
        "ABUKUR",
        "FARDAMI",
        "KADANDANI",
        "MAJENGOBIR",
        "MAKURDA",
        "MASABO/KURABAU",
        "REMAWA/IYATAWA",
        "RIMI",
        "SABON GARIN/ALARAIN",
        "TSAGERO",
      ],
      name: "RIMI",
    },
    {
      wards: [
        "DAMARI",
        "DUGUN MU'AZU",
        "GAMJI",
        "GAZARI",
        "MACHIKA",
        "MAIBAKKO",
        "RAFIN IWA",
        "SABUWA 'A'",
        "SABUWA 'B'",
        "SAYAU",
      ],
      name: "SABUWA",
    },
    {
      wards: [
        "BABBAN DUHU 'A'",
        "BABBAN DUHU 'B'",
        "BAURE 'A'",
        "BAURE 'B'",
        "RUNKA 'A'",
        "RUNKA 'B'",
        "SAFANA",
        "TSASKIYA",
        "ZAKKA 'A'",
        "ZAKKA 'B'",
      ],
      name: "SAFANA",
    },
    {
      wards: [
        "DANEJI 'A'",
        "DANEJI 'B'",
        "FAGO 'A'",
        "FAGO 'B'",
        "KAGARE",
        "KARKARKU",
        "KATSAYAL",
        "KWASARAWA",
        "RADE 'A'",
        "RADE 'B'",
        "SANDAMU",
      ],
      name: "SANDAMU",
    },
    {
      wards: [
        "DARGAGE",
        "GARNI",
        "GWAMBA",
        "KANDA",
        "KAWARIN KUDI",
        "KAWARIN MALAWAMAI",
        "ROGOGO/CIDARI",
        "SARA",
        "YARDAJE",
        "ZANGO",
      ],
      name: "ZANGO",
    },
  ],
};

export const KATSINA = { states, SR };
