const SR = {
  name: "KEBBI",
  email: "Kebbi@apcaims.com",
  password: "kebbi_b8&",
  phone: "08108850572",
  statecode: "KEBBI",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "KEBBI",
  state: "KEBBI",
  lga: [
    {
      wards: [
        "ALIERO DANGALADIMA I",
        "ALIERO DANGALADIMA II",
        "ALIERO S/FADA I",
        "ALIERO S/FADA II",
        "DANWARAI",
        "JIGA BIRNI",
        "JIGA MAKERA",
        "KASHIN ZAMA",
        "RAFIN BAUNA",
        "SABIYAL",
      ],
      name: "ALIERO",
    },
    {
      wards: [
        "BIU",
        "CHIBIKE",
        "DAURA/SAKKWABE/JARKUKA",
        "FALDE",
        "FESKE/JAFFEJI",
        "GORUN DIKKO",
        "GUMUMDAI/RAFIN TSAKA",
        "KANGIWA",
        "LAIMA/JANTULLU",
        "SARKA/DANTSOHO",
        "YELDU",
      ],
      name: "AREWA",
    },
    {
      wards: [
        "ALWASA/GOTOMO",
        "DIKKO",
        "FELANDE",
        "GALADIMA",
        "GULMA",
        "GWAZANGE/KISAWA/U GYAGA",
        "KOKANI NORTH",
        "KOKANI SOUTH",
        "LAILABA",
        "SAUWA/KAURAR SANI",
        "TUNGAR ZAZZAGAWA/RUMBUKI/SARKAWA",
      ],
      name: "ARGUNGU",
    },
    {
      wards: [
        "AUGIE NORTH",
        "AUGIE SOUTH",
        "BAGAYE/MERA",
        "BAYAWA NORTH",
        "BAYAWA SOUTH",
        "BIRNIN TUDU/GUDALE",
        "BUBUCE",
        "DUNDAYE/KWAIDO/ZAGI/ILLELA",
        "TIGGI/AWADE",
        "YOLA",
      ],
      name: "AUGIE",
    },
    {
      wards: [
        "BAGUDO/TUGA",
        "BAHINDI/BOKI-DOMA",
        "BANI/TSAMIYA/KALI",
        "ILLO/SABON/GARI/YANTAU",
        "KAOJE/GWAMBA",
        "KENDE/KURGU",
        "LAFAGU/GANTE",
        "LOLO/GIRIS",
        "MATSINKA/GEZA",
        "SHARABI/KWANGUWAI",
        "ZAGGA/KWASARA",
      ],
      name: "BAGUDO",
    },
    {
      wards: [
        "AMBURSA",
        "BIRNIN KEBBI DANGALADIMA",
        "BIRNIN KEBBI MAFARA",
        "GAWASU",
        "GODONGAJI",
        "GULUMBE",
        "KARDI/YAMAMA",
        "KOLA /TARASA",
        "LAGA",
        "MAKERA",
        "MAURIDA /KARYO/UNG. MIJIN-NANA",
        "NASSARAWA - I",
        "NASSARAWA II",
        "UJARIYO",
        "ZAURO",
      ],
      name: "BIRNIN KEBBI",
    },
    {
      wards: [
        "BUNZA DANGALADIMA",
        "BUNZA MARAFA",
        "GWADE",
        "MAIDAHINI",
        "RAHA",
        "SABON BIRNI",
        "SALWAI",
        "TILLI/HILEMA",
        "TUNGA",
        "ZOGRIMA",
      ],
      name: "BUNZA",
    },
    {
      wards: [
        "BANI ZUMBU",
        "BUMA",
        "DOLEKAINA",
        "FANA",
        "GEZA",
        "KAMBA / KAMBA",
        "KWAKKWABA",
        "KYANGAKWAI",
        "MAIGWAZA",
        "MAIHAUSAWA",
        "SHIKO",
      ],
      name: "DANDI",
    },
    {
      wards: [
        "BAJIDA",
        "BANGU/GARINISA",
        "BIRNIN TUDU",
        "FAKAI/ZUSSUN",
        "GULBIN KUKA/MAIJARHULA",
        "INGA(BULU) MAIKENDE",
        "KANGI",
        "MAHUTA",
        "MARAFA",
        "PENIN AMANA/PENIN GABA",
      ],
      name: "FAKAI",
    },
    {
      wards: [
        "CHEBERU/BADA",
        "DALIJAN",
        "DODORU",
        "GULMARE",
        "GWANDU MARAFA",
        "GWANDU SARKIN FAWA",
        "KAMBAZA",
        "MALISA",
        "MARUDA",
        "MASAMA KWASGARA",
      ],
      name: "GWANDU",
    },
    {
      wards: [
        "ALELU/GEHURU",
        "DANGAMAJI",
        "DUNBEGU/BAUSARA",
        "GINDI/NASSARAWA/KYARMI/GALBI",
        "JANDUTSI/BIRNIN MALAM",
        "JEGA FIRCHIN",
        "JEGA KOKANI",
        "JEGA MAGAJI 'A'",
        "JEGA MAGAJI 'B'",
        "KATANGA/FAGADA",
        "KIMBA",
      ],
      name: "JEGA",
    },
    {
      wards: [
        "BADARIYA/MAGARZA",
        "DANGOMA/GAYI",
        "DIGGI",
        "ETENE",
        "KALGO",
        "KUKA",
        "MUTUBARI",
        "NAYILWA",
        "WUROGAURI",
        "ZUGURU",
      ],
      name: "KALGO",
    },
    {
      wards: [
        "BESSE",
        "DADA/ALELU",
        "DUTSIN MARI/DULMERU",
        "ILLELA/S/GARI",
        "JADADI",
        "KOKO FIRCIN",
        "KOKO MAGAJI",
        "LANI/MANYAN/TAFUKKA/SHIBA",
        "MADACCI/FIRINI",
        "MAIKWARI/ KARAMAR/ DAMBA/ BAKOSHI",
        "TAKWARE",
        "ZARIYA KALAKALA/AMIRU",
      ],
      name: "KOKO BESSE",
    },
    {
      wards: [
        "ANDARAI/ KURUNKWU/ ZONGUN LIBA",
        "GIWA TAZO/ZARA",
        "GUMBIN KURE",
        "KARAYE/DOGONDAJI",
        "KAWARA/S/SARA/YARKAMBA",
        "KUBEN RIGIDIGA",
        "LIBA/DANWA/KUKA KOGO",
        "MAIYAMA",
        "MUNGADI/BOTORO",
        "SAMBAWA/MAYALO",
        "SARANDOSA/GUBBA",
      ],
      name: "MAIYAMA",
    },
    {
      wards: [
        "BIRNIN YAURI",
        "GAFARA MACHUPA",
        "GARIN BAKA/MAKARIN",
        "KAMBUWA/DANMARAYA",
        "KWAKWARAN",
        "LIBATA/KWANGIA",
        "MAKAWA ULEIRA",
        "NGASKI",
        "UTONO/HOGE",
        "WARA",
      ],
      name: "NGASKI",
    },
    {
      wards: [
        "ADAI",
        "DANKOLO",
        "DOKA/BERE",
        "FADA",
        "GELWASA",
        "JANBIRNI",
        "MAKUKU",
        "MAZA/MAZA",
        "SAKABA",
        "TUDUN KUKA",
      ],
      name: "SAKABA",
    },
    {
      wards: [
        "ATUWO",
        "BINUWA/GEBE/BUNKUJI",
        "DUGU TSOHO/DUGU RAHA",
        "KAWARA/INGU/SARGO",
        "RAFIN KIRYA/TEFKI TARA",
        "SAWASHI",
        "SHANGA",
        "SOKAGE/GOLONGO/HUNDEJI",
        "TAKWARE",
        "YARBESSE",
      ],
      name: "SHANGA",
    },
    {
      wards: [
        "ALJANNARE",
        "BAKUWAI",
        "BANDAN",
        "BARBAREJO",
        "DAKINGARI",
        "DANIYA/SHEMA",
        "DENDANE",
        "GINGA",
        "GIRO",
        "KWAIFA",
        "SURU",
      ],
      name: "SURU",
    },
    {
      wards: [
        "AYU",
        "BENA",
        "DAN UMARU/MAIRAIRAI",
        "DANKO/MAGA",
        "GWANFI/KELE",
        "KANYA",
        "KYABU/KANDU",
        "RIBAH/MACHIKA",
        "WAJE",
        "WASAGU",
        "YALMO/SHINDI",
      ],
      name: "WASAGU/DANKO",
    },
    {
      wards: [
        "CHULU/KOMA",
        "GUNGUN SARKI",
        "JIJIMA",
        "TONDI",
        "YELWA CENTRAL",
        "YELWA EAST",
        "YELWA NORTH",
        "YELWA SOUTH",
        "YELWA WEST",
        "ZAMARE",
      ],
      name: "YAURI",
    },
    {
      wards: [
        "BEDI",
        "CIROMAN DABAI",
        "ISGOGO /DAGO",
        "MANGA/USHE",
        "RAFIN ZURU",
        "RIKOTO",
        "RUMU/DABEN/SEME",
        "SENCHI",
        "TADURGA",
        "ZODI",
      ],
      name: "ZURU",
    },
  ],
};

export const KEBBI = { states, SR };
