const SR = {
  name: "LAGOS",
  email: "Lagos@apcaims.com",
  password: "lagos_9y27v",
  phone: "08108850572",
  statecode: "LAGOS",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "LAGOS",
  state: "LAGOS",
  lga: [
    {
      wards: [
        "AGBOTIKUYO/DOPEMU",
        "DAROCHA",
        "ILORO/ONIPETESI",
        "ISALE ODO",
        "ISALE/IDIMANGORO",
        "KEKE",
        "OKEKOTO",
        "ONIWAYA/PAPA-UKU",
        "ORILE AGEGE/OKO OBA",
        "OYEWOLE/PAPA ASHAFA",
        "TABON TABON/OKO OBA",
      ],
      name: "AGEGE",
    },
    {
      wards: [
        "AGO HAUSA",
        "ALABA ORO",
        "AWODI-ORA",
        "LAYENI",
        "MOSAFEJO",
        "OJO ROAD",
        "OLODI",
        "TEMIDIRE I",
        "TEMIDIRE II",
        "TOLU",
        "WILMER",
      ],
      name: "AJEROMI/IFELODUN",
    },
    {
      wards: [
        "ABULE-EGBA/ABORU/MEIRAN/ALAGBADO",
        "AYOBO/IJON VILLAGE (CAMP DAVID)",
        "EGBE/AGODO",
        "EGBEDA/ALIMOSHO",
        "IDIMU/ISHERI OLOFIN",
        "IGANDO/EGAN",
        "IKOTUN/IJEGUN",
        "IPAJA NORTH",
        "IPAJA SOUTH",
        "PLEASURE/OKE-ODO",
        "SHASHA/AKOWONJO",
      ],
      name: "ALIMOSHO",
    },
    {
      wards: [
        "AMUWO",
        "AMUWO-ODOFIN HOUSING ESTATE, MILE 2",
        "FESTAC 1",
        "FESTAC II",
        "FESTAC III",
        "IBESHE",
        "IGBOLOGUN",
        "IJEGUN",
        "IREDE",
        "KIRIKIRI",
        "SATELLITE",
      ],
      name: "AMUWO-ODOFIN",
    },
    {
      wards: [
        "AFOLABI ALASIA STR. AND ENVIRONS",
        "APAPA I (MARINE RD. & ENVIRONS)",
        "APAPA II (LIVERPOOL RD. AND ENVIRONS)",
        "APAPA III (CREEK RD. TINCAN/SNAKE ISLAND",
        "APAPA IV (PELEWURA CRESCENT AND ENVIRONS)",
        "GASKIYA & ENVIRONS",
        "IJORA-OLOYE",
        "MALU ROAD AND ENVIRONS",
        "OLODAN ST. OLOJOWOU ST/ALH.DOGO OLATOKUNBO ST. IGANMU",
        "SARI AND ENVIRONS",
      ],
      name: "APAPA",
    },
    {
      wards: [
        "AJARA",
        "AJIDO",
        "APA",
        "AWHANJIGOH",
        "IBEREKO",
        "IKOGA",
        "ILOGBO-ARAROMI",
        "IWORO GBANKO",
        "IYA-AFIN",
        "KETA-EAST",
        "POSUKOH",
      ],
      name: "BADAGRY",
    },
    {
      wards: [
        "ABOMITI",
        "AGBOWA",
        "AGBOWA IKOSI",
        "AGO OWU",
        "AJAGANABE",
        "EJIRIN",
        "ETITA/EBODE",
        "IBONWON",
        "ILARA",
        "ISE/IGBOGUN",
        "ITOIKIN",
        "LAGBADE",
        "ODOMOLA",
        "ODORAGUNSIN",
        "OKE-BALOGUN",
        "ORIBA/LADABA",
        "ORUGBO",
        "POKA",
        "POPO-OBA",
      ],
      name: "EPE",
    },
    {
      wards: [
        "ADO/LANGBASA/BADORE",
        "AJAH/SANGOTEDO",
        "IKOYI I",
        "IKOYI II",
        "ILADO/ETI-OSA AND ENVIRONS",
        "ILASAN HOUSING ESTATE",
        "LEKKI/IKATE AND ENVIRONS",
        "OBALENDE",
        "VICTORIA ISLAND I",
        "VICTORIA ISLAND II",
      ],
      name: "ETI-OSA",
    },
    {
      wards: [
        "02, (ORIMEDU II)",
        "03, (ORIMEDU III)",
        "IBEJU I",
        "IWEREKUN II",
        "LEKKI II",
        "N2, (IBEJU II)",
        "ORIMEDU I",
        "P1, (IWEREKUN I)",
        "S,2a (SIRIWON/IGBEKODO II)",
        "S1, (LEKKI I)",
        "S2, (SIRIWON/IGBEKODO I)",
      ],
      name: "IBEJU/LEKKI",
    },
    {
      wards: [
        "AJEGUNLE/AKINDE/ANIMASHAUN",
        "ALAKUKO/KOLLINGTON",
        "FAGBA/AKUTE ROAD",
        "IJAIYE/AGBADO/KOLLINGTON",
        "IJAIYE/OJOKORO",
        "IJAYE",
        "IJU ISAGA",
        "IJU-OBAWOLE",
        "NEW IFAKO/OYEMEKUN",
        "OLD IFAKO/KARAOLE",
        "PAMADA/ABULE-EGBA",
      ],
      name: "IFAKO-IJAYE",
    },
    {
      wards: [
        "ADEKUNLE VILL./ADENIYI JONES/OGBA",
        "AIRPORT/ONIPETESI/INILEKERE",
        "ALAUSA/OREGUN/OLUSOSUN",
        "ANIFOWOSHE/IKEJA",
        "GRA/POLICE BARRACKS",
        "IPODO/SERIKI ARO",
        "OJODU/AGIDINGBI/OMOLE",
        "OKE-IRA/AGUDA",
        "ONIGBONGBON",
        "WASIMI/OPEBI/ALLEN",
      ],
      name: "IKEJA",
    },
    {
      wards: [
        "AGA/IJIMU",
        "AGBALA",
        "AGURA/IPONMI",
        "BAIYEKU/ORETA",
        "ERIKORODU",
        "IBESHE",
        "IGBOGBO I",
        "IGBOGBO II",
        "IJEDE II",
        "IJEDE J",
        "IMOTA 1",
        "IMOTA II",
        "IPAKODO",
        "ISELE I",
        "ISELE II",
        "ISELE III",
        "ISIU",
        "ODOGUNYAN",
        "OLORUNDA/IGBAGA",
      ],
      name: "IKORODU",
    },
    {
      wards: [
        "AGBOYI I",
        "AGBOYI II",
        "ANTHONY/AJAO ESTATE/MENDE/MARYLAND",
        "IFAKO/SOLUYI",
        "IKOSI KETU/MILE 12/AGILITI/MAIDAN",
        "ISHERI-OLOWO-IRA/SHANGISHA/MAGODO PHASE I & II",
        "KETU/ALAPERE/AGIDI/ORISIGUN/KOSOFE/AJELOGO/AKANIMODO",
        "OJOTA/OGUDU",
        "OWODE ONIRIN/AJEGUNLE/ODO-OGUN",
        "OWORONSHOKI",
      ],
      name: "KOSOFE",
    },
    {
      wards: [
        "AGARAWU/OBADINA",
        "ANIKANTAMO",
        "EIYEKOLE",
        "EPETEDO",
        "IDUMOTA/OKE",
        "IDUNTAFA",
        "ILUPESI",
        "ISALE-AGBEDE",
        "LAFIAJI/EBUTE",
        "OJU-OTO",
        "OKO-AWO",
        "OKO-FAJI",
        "OLOSUN",
        "OLOWOGBOWO/ELEGBATA",
        "OLUSHI/KAKAWA",
        "OLUWOLE",
        "ONIKAN",
        "POPO-AGUDA",
        "SANDGROUSE",
      ],
      name: "LAGOS ISLAND",
    },
    {
      wards: [
        "ALAGOMEJI",
        "EPETEDO",
        "GLOVER/EBUTE METTA",
        "IWAYA",
        "MAROKO/EBUTE METTA",
        "OKO-BABA",
        "OLALEYE VILLAGE",
        "OTTO/IDDO",
        "OYADIRAN ESTATE/ABULE-OJA",
        "OYINGBO MARKET/EBUTE METTA",
        "YABA/IGBOBI",
      ],
      name: "LAGOS MAINLAND",
    },
    {
      wards: [
        "ALAKARA",
        "BABALOSA",
        "BABALOSA/IDI-ARABA",
        "IDI-ARABA",
        "IDI-ORO/ODI-OLOWU",
        "ILASAMAJA",
        "ILUPEJU",
        "ILUPEJU INDUSTRIAL ESTATE",
        "ITIRE",
        "KAYODE/FADEYI",
        "MUSHIN/ATEWOLARA",
        "OJUWOYE",
        "OLATEJU",
        "PAPA-AJAO",
      ],
      name: "MUSHIN",
    },
    {
      wards: [
        "AJANGBADI",
        "ETEGBIN",
        "IBA",
        "IDOLUWO",
        "IJANIKIN",
        "ILOGBO",
        "IREWE",
        "OJO TOWN",
        "OKOKOMAIKO",
        "SABO",
        "TAFI",
      ],
      name: "OSHO",
    },
    {
      wards: [
        "AJAO ESTATE",
        "ILASAMAJA",
        "ISHAGATEDO",
        "ISOLO",
        "MAFOLUKU",
        "OKE-AFA/EJIGBO",
        "OKOTA",
        "ORILE-OSHODI",
        "OSHODI/BOLADE",
        "SOGUNLE",
        "SOGUNLE/ALASIA",
      ],
      name: "OSHODI/ISOLO",
    },
    {
      wards: [
        "ABULE-OKUTA/ILAJE/BARIGA",
        "ALADE",
        "BAJULAIYE",
        "FOLA AGORO/BAJULAIYE/IGBARI-AKOKA",
        "GBAGADA PHASE I OBANIKORO/PEDRO",
        "GBAGADA PHASE II /BARIGA/APELEHIN",
        "IGBOBI/FADEYI",
        "ILAJE/AKOKA",
        "LAD-LAK/BARIGA",
        "MAFOWOKU/PEDRO",
        "ONIPANU",
        "PALMGROVE/IJEBUTEDO",
      ],
      name: "SOMOLU",
    },
    {
      wards: [
        "ADENIRAN/OGUNSANYA",
        "AGUDA",
        "AKINHANMI/COLE",
        "COKER",
        "IGBAJA/STADIUM",
        "IJESHATEDO",
        "IKATE",
        "IPONRI HOUSING ESTATE/ERIC MOORE",
        "ITIRE",
        "ORILE",
        "SHITTA/OGUNLANA DRIVE",
        "YABA/OJUELEGBA",
      ],
      name: "SURULERE",
    },
  ],
};

export const LAGOS = { states, SR };
