const SR = {
  name: "NASSARAWA",
  email: "Nasarawa@apcaims.com",
  password: "nasarawa_b@uu4",
  phone: "08108850572",
  statecode: "NASSARAWA",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "NASSARAWA",
  state: "NASSARAWA",
  lga: [
    {
      wards: [
        "AGYAGA",
        "AKWANGA EAST",
        "AKWANGA WEST",
        "ANCHO NIGHAAN",
        "ANCHOBABA",
        "ANDAHA",
        "GUDI",
        "GWANJE.GWANJE",
        "MOROA",
        "NINGO / BOHAR",
        "NUNKU",
      ],
      name: "AKWANGA",
    },
    {
      wards: [
        "AKIRI",
        "AZARA",
        "GALADIMA",
        "JANGARU",
        "KANJE/ABUNI",
        "MADAKI",
        "MAKWANGIJI",
        "RIBI",
        "TUNGA",
        "WUSE",
      ],
      name: "AWE",
    },
    {
      wards: [
        "AGBASHI",
        "AKPANAJA",
        "ALAGYE",
        "DOKA",
        "GALADIMA",
        "MADAUCHI",
        "RUKUBI",
        "SABON GARI",
        "SARKIN DAWAKI",
        "UNGWAN MADAKI",
      ],
      name: "DOMA",
    },
    {
      wards: [
        "AGADA/BAGAJI",
        "ASO / KODAPE",
        "GITATA",
        "GURKU/KABUSU",
        "KAFIN SHANU/BETTI",
        "KARSHI I",
        "KARSHI II",
        "KARU",
        "PANDA / KARE",
        "TATTARA/KONDORO",
        "UKE",
      ],
      name: "KARU",
    },
    {
      wards: [
        "AGAZA",
        "ALOSHI",
        "AMIRI",
        "GIZA GALADIMA",
        "GIZA MADAKI",
        "IWAGU",
        "KADARKO",
        "KWARA",
        "OBENE",
        "OKI",
      ],
      name: "KEANA",
    },
    {
      wards: [
        "ANG.RIMI",
        "ANGWAN IYA I",
        "ANGWAN IYA II",
        "GANGARE TUDU",
        "JIGWADA",
        "KEFFI TOWN EAST / KOFAR GORIYA",
        "LIMAN ABAJI",
        "SABON GARI",
        "TUDUN KOFA T.V",
        "YARA",
      ],
      name: "KEFFI",
    },
    {
      wards: [
        "AGWADA",
        "AMBA",
        "BASSA",
        "DARI",
        "GARAKU",
        "HADARI",
        "KOFAR GWARI",
        "KOKONA",
        "KOYA  / KANA",
        "NINKORO",
        "YELWA",
      ],
      name: "KOKONA",
    },
    {
      wards: [
        "ADOGI",
        "AGYARAGUN TOFA",
        "ARIKYA",
        "ASHIGIE",
        "ASSAKIO",
        "BAKIN RIJIYA/AKURBA/SARKIN PADA",
        "CHIROMA",
        "GAYAM",
        "KEFFIN/WAMBAI",
        "MAKAMA",
        "SHABU/KWANDERE",
        "WAKWA",
        "ZANWA",
      ],
      name: "LAFIA",
    },
    {
      wards: [
        "AKUM",
        "ARA I",
        "ARA II",
        "GUTO/AISA",
        "KANAH/ONDO/APAWU",
        "LAMINGA",
        "LOKO",
        "NASARAWA  CENTRAL",
        "NASARAWA EAST",
        "NASARAWA MAIN TOWN",
        "NASARAWA NORTH",
        "ODU",
        "TUNGA/BAKONO",
        "UDENIN",
        "UDENIN GIDA",
      ],
      name: "NASSARAWA",
    },
    {
      wards: [
        "AGUNJI",
        "ALOCE/GINDA",
        "ALOGANI",
        "ENDE",
        "IGGA/BURUMBURUM",
        "IKKA WANGIBI",
        "KAGBU WANA",
        "LAMBAGA/ARIKPA",
        "LIZZIN KEFFI/EZZEN",
        "MADA STATION",
        "NASARAWA EGGON",
        "UBBE",
        "UMME",
        "WAKAMA",
      ],
      name: "NASARAWA EGGON",
    },
    {
      wards: [
        "ADUDU",
        "AGWATASHI",
        "DEDDERE/RIRI",
        "DUDUGURU",
        "GIDAN AUSA I",
        "GIDAN AUSA II",
        "GWADENYE",
        "KYAKALE",
        "OBI",
        "TUDUN ADABU",
      ],
      name: "OBI",
    },
    {
      wards: [
        "BUGAKARMO",
        "DAUSU",
        "GADAGWA",
        "GWARGWADA",
        "KANYEHU",
        "KATAKPA I",
        "SHAFAN ABAKPA I",
        "SHAFAN KWATTO I",
        "SHEGE I",
        "TOTO",
        "UGYA",
        "UMAISHA",
      ],
      name: "TOTO",
    },
    {
      wards: [
        "ARUM",
        "GITTA",
        "JIMIYA",
        "KONVAH",
        "KWARA",
        "MANGAR",
        "NAKERE",
        "WAMBA EAST",
        "WAMBA WEST",
        "WAYO",
      ],
      name: "WAMBA",
    },
  ],
};

export const NASARAWA = { states, SR };
