const SR = {
  name: "NIGER",
  email: "Niger@apcaims.com",
  password: "niger_##df",
  phone: "08108850572",
  statecode: "NIGER",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "NIGER",
  state: "NIGER",
  lga: [
    {
      wards: [
        "BARO",
        "BOKU",
        "DAUACI",
        "EKOBADEGGI",
        "EKOSSA",
        "EKOWUGI",
        "EKOWUNA",
        "ETSUGAIE",
        "KUTIRIKO",
        "MAGAJI",
        "TAGAGI",
      ],
      name: "AGAIE",
    },
    {
      wards: [
        "ADEHE",
        "AGWATA",
        "BUSURU",
        "GALLAH",
        "KASHINI",
        "KOKOLI",
        "MAGO",
        "PAPIRI",
        "ROFIA",
        "SUTEKU",
      ],
      name: "AGWARA",
    },
    {
      wards: [
        "BARIKI",
        "CENIYAN",
        "DOKODZA",
        "KYARI",
        "LANDZUN",
        "MASABA II",
        "MASABA I",
        "MASAGA I",
        "MASAGA II",
        "MAYAKI NDAJIYA",
        "NASSARAFU",
        "UMARU MAJIGI II",
        "UMARU/MAJIGI I",
        "WADATA",
      ],
      name: "BIDA",
    },
    {
      wards: [
        "BABANNA",
        "DUGGA",
        "KABE/PISSA",
        "KARABONDE",
        "KONKOSO",
        "MALALE",
        "NEW BUSSA",
        "RIVERINE",
        "SHAGUNU",
        "WAWA",
      ],
      name: "BORGU",
    },
    {
      wards: [
        "BEJI",
        "BOSSO CENTRAL I",
        "BOSSO CENTRAL II",
        "CHANCHAGA",
        "GARATU",
        "KAMPALA",
        "KODO",
        "MAIKUNKELE",
        "MAITUMBI",
        "SHATA",
      ],
      name: "BOSSO",
    },
    {
      wards: [
        "LIMAWA 'A'",
        "LIMAWA 'B'",
        "MAKERA",
        "MINNA CENTRAL",
        "MINNA SOUTH",
        "NASSARAWA 'A'",
        "NASSARAWA 'B'",
        "NASSARAWA 'C'",
        "SABON GARI",
        "TUDUN WADA NORTH",
        "TUDUN WADA SOUTH",
      ],
      name: "CHANCHAGA",
    },
    {
      wards: [
        "ENAGI",
        "ETSU TASHA",
        "FAZHI",
        "GAZHE I",
        "GAZHE II",
        "GBANGBAN",
        "GONAGI",
        "GUZAN",
        "ROKOTA",
        "SAKPE",
      ],
      name: "EDATTI",
    },
    {
      wards: [
        "BATAGI",
        "BATAKO",
        "EDOKOTA",
        "EDOZHIGI",
        "ETSU AUDU",
        "GBADAFU",
        "GOGATA",
        "LEMU",
        "NUWANKOTA",
        "SAMMAJIKO",
      ],
      name: "GBAKO",
    },
    {
      wards: [
        "BONU",
        "DIKO",
        "GAWU",
        "IZOM",
        "KABO",
        "KWAKA",
        "LAMBATA",
        "LEFU",
        "SHAKO",
        "TUFA",
      ],
      name: "GURARA",
    },
    {
      wards: [
        "BADEGGI",
        "BAKEKO",
        "BISANTI",
        "DZWAFU",
        "EDOTSU",
        "ESSA",
        "GBAKOGI",
        "KATAREGI",
        "KATCHA",
        "SIDI SABA",
      ],
      name: "KATCHA",
    },
    {
      wards: [
        "AREWA",
        "CENTRAL",
        "GABAS",
        "KUDU",
        "MADARA",
        "MAGAJIYA",
        "MASUGA",
        "NAGWAMATSE",
        "RAFIN GORA",
        "TUNGAN KAWO",
        "TUNGANWAWA",
        "USALLE",
        "YAMMA",
      ],
      name: "KONTAGORA",
    },
    {
      wards: [
        "AREWA/YAMMA",
        "BIRNIN MAZA/TASHIBO",
        "EBBO/GBACINKU",
        "EVUTI/KPADA",
        "GULU/ANGUWA VATSA",
        "GUPA/ABUGI",
        "GURDI/ZAGO",
        "KUDU/GABAS",
        "MUYE/EGBA",
        "TAKUTI/SHAKU",
      ],
      name: "LAPAI",
    },
    {
      wards: [
        "BATATI",
        "BUSU/KUCHI",
        "DABBAN",
        "DASSUN",
        "DOKO",
        "EGBAKO",
        "GABA",
        "JIMA",
        "KUSOTACHI",
        "KUTIGI",
        "LAGUN",
        "MAMBE",
      ],
      name: "LAVUN",
    },
    {
      wards: [
        "AUNA CENTRAL",
        "AUNA EAST",
        "AUNA EAST CENTRAL",
        "AUNA SOUTH",
        "AUNA SOUTH EAST",
        "IBELU CENTRAL",
        "IBELU EAST",
        "IBELU NORTH",
        "IBELU WEST",
        "NASKO",
        "NASSARAWA",
      ],
      name: "MAGAMA",
    },
    {
      wards: [
        "BANGI",
        "BERI",
        "BOBI",
        "GALMA/WAMBA",
        "GULBIN - BOKA",
        "IGWAMA",
        "INKWAI",
        "KAKIHUM",
        "KONTOKORO",
        "KUMBASHI",
        "MABURYA",
      ],
      name: "MARIGA",
    },
    {
      wards: [
        "BABBAN RAMI",
        "DAPANGI/MAKERA",
        "IBBI",
        "KABOJI",
        "KASANGA",
        "KULHO",
        "KWATACHI",
        "MASHEGU",
        "MAZAKUKA/LIKORO",
        "SAHO-RAMI",
      ],
      name: "MASHEGU",
    },
    {
      wards: [
        "BOKANI",
        "GBAJIBO/MUWO",
        "GBARA",
        "JA'AGI",
        "JEBBA NORTH",
        "KPAKI/TAKUMA",
        "KUDU",
        "LABOZHI",
        "MOKWA",
        "MUREGI",
        "RABBA/NDAYAKO",
      ],
      name: "MOKWA",
    },
    {
      wards: [
        "BENI",
        "DANDAUDU",
        "DANGUNU",
        "DAZA",
        "FUKA",
        "GINI",
        "GUNI",
        "KABULA",
        "KAZAI",
        "KUCHI",
        "SARKIN PAWA",
      ],
      name: "MUNYA",
    },
    {
      wards: [
        "ADUNU",
        "CHIMBI",
        "GWAM",
        "ISHAU",
        "JERE",
        "KAFIN KORO",
        "KWAGANA",
        "KWAKUTI",
        "NIKUCHI T/MALLAM",
        "PAIKO CENTRAL",
        "TUTUNGO JEDNA",
      ],
      name: "PAIKORO",
    },
    {
      wards: [
        "KAGARA GARI",
        "KAKURI",
        "KONGOMA CENTRAL",
        "KONGOMA WEST",
        "KUNDU",
        "KUSHERKI NORTH",
        "KUSHIRKI SOUTH",
        "SABON GARI",
        "TEGINA GARI",
        "TEGINA WEST",
        "YAKILA",
      ],
      name: "RAFI",
    },
    {
      wards: [
        "DANRANGI",
        "DUGGE",
        "DUKKU",
        "GENU",
        "JAMA'ARE",
        "RIJAU",
        "SHAMBO",
        "T/BUNU",
        "T/MAGAJIYA",
        "USHE",
        "WARARI",
      ],
      name: "RIJAU",
    },
    {
      wards: [
        "ALLAWA",
        "BANGAJIYA",
        "BASSA/KUKOKI",
        "EGWA/GWADA",
        "ERANA",
        "GALKOGO",
        "GURMANA",
        "GUSSORO",
        "KATO",
        "KUSHAKA/KUREBE",
        "KWAKI/CHUKWUBA",
        "MANTA",
        "PINA",
        "SHE",
        "UBANDOMA",
      ],
      name: "SHIRORO",
    },
    {
      wards: [
        "BAGAMA 'B'",
        "BAGMAMA 'A'",
        "HASHIMI 'A'",
        "HASHIMI 'B'",
        "IKU SOUTH I",
        "IKU SOUTH II",
        "KURMIN SARKI",
        "MAGAJIYA",
        "MAJE NORTH",
        "WAMBAI",
      ],
      name: "SULEJA",
    },
    {
      wards: [
        "DOGON KURMI",
        "GARAM",
        "IJA GWARI",
        "IJA KORO",
        "IKU",
        "NEW BWARI",
        "WUSE EAST",
        "WUSE WEST",
        "ZUMA EAST",
        "ZUMA WEST",
      ],
      name: "TAFA",
    },
    {
      wards: [
        "AKARE",
        "BARWA",
        "GWARJIKO",
        "KANWURI",
        "KODO",
        "KWATA",
        "LOKOGOMA",
        "MAITO",
        "SABON GARI",
        "TUKUNJI/YAMIGI",
        "ZUNGERU",
      ],
      name: "WUSHISHI",
    },
  ],
};

export const NIGER = { states, SR };
