const SR = {
  name: "OGUN",
  email: "Ogun@apcaims.com",
  password: "ogun_vb55",
  phone: "08108850572",
  statecode: "OGUN",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "OGUN",
  state: "OGUN",
  lga: [
    {
      wards: [
        "AGO OKO",
        "ELEGA",
        "GBAGURA",
        "IBARA ORILE/ONISASA",
        "IKA",
        "IKEREKU",
        "IKIJA",
        "ILUGUN/IBEREKODO",
        "IMALA - IDIEMI",
        "ISAGA ILEWO",
        "ITA OSIN/OLOMORE",
        "LAFENWA",
        "OKE-AGO OWU",
        "OLORUNDA IJALE",
        "SABO",
        "TOTORO/SOKORI",
      ],
      name: "ABEOKUTA NORTH",
    },
    {
      wards: [
        "AGO-EGUN/IJESA",
        "AKE I",
        "AKE III",
        "AKE II",
        "ERUNBE/OKE IJEUN",
        "IBARA I",
        "IBARA II",
        "IGBORE/AGO OBA",
        "IJAYE/IDI-ABA",
        "IJEMO",
        "IMO/ISABO",
        "ITOKO",
        "KEESI/EMERE",
        "SODEKE/SALE-IJEUN I",
        "SODEKE/SALE-IJEUN II",
      ],
      name: "ABEOKUTA SOUTH",
    },
    {
      wards: [
        "ADO ODO I",
        "ADO ODO II",
        "AGBARA I",
        "AGBARA/EJILA AWORI",
        "ALAPOTI",
        "ATAN",
        "ERE",
        "IGBESA",
        "IJOKO",
        "IJU",
        "ILOGBO",
        "KETU-ADIE-OWE",
        "OTA I",
        "OTA II",
        "OTA III",
        "SANGO",
      ],
      name: "ADO ODO-OTA",
    },
    {
      wards: [
        "AYE TORO I",
        "AYE TORO II",
        "EBUTE IGBOORO",
        "IBESE",
        "IBORO/JOGA",
        "IDO FOI",
        "IGUA",
        "IJOUN",
        "IMASAI",
        "OHUNBE",
        "SUNWA",
      ],
      name: "EGBADO NORTH",
    },
    {
      wards: [
        "AJILETE",
        "IDOGO",
        "ILARO I",
        "ILARO II",
        "ILARO III",
        "ILOBI/ERINJA",
        "IWOYE",
        "OKE ODAN",
        "OWODE I",
        "OWODE II",
      ],
      name: "EGBADO SOUTH",
    },
    {
      wards: [
        "ABALABI",
        "ARIGBAJO",
        "ASA/YOBO",
        "ELERE/ONIGBEDU",
        "ITORI",
        "MOSAN",
        "OBADA-OKO",
        "OWOWO",
        "PAPALANTO",
        "WASIMI",
      ],
      name: "EWEKORO",
    },
    {
      wards: [
        "AGBADO",
        "AJUWON/AKUTE",
        "COKER",
        "IBOGUN",
        "IFO I",
        "IFO II",
        "IFO III",
        "ISERI",
        "OKE-ARO/IBARAGUN/ROBIYAN",
        "OSOSUN",
        "SUNREN",
      ],
      name: "IFO",
    },
    {
      wards: [
        "AJEBANDELE",
        "IJEBU IFE I",
        "IJEBU IFE II",
        "IJEBU MUSHIN I",
        "IJEBU MUSHIN II",
        "IKIJA",
        "IMOBI I",
        "IMOBI II",
        "ITELE",
        "OGBERE",
        "OWU",
      ],
      name: "IJEBU EAST",
    },
    {
      wards: [
        "AGO IWOYE I",
        "AGO IWOYE II",
        "AKO-ONIGBAGBO/GELETE",
        "ATIKORI",
        "JAPARA/OJOWO",
        "MAMU/ETIRI",
        "OKE AGBO",
        "OKE SOPIN",
        "OMEN",
        "ORU/AWA/ILAPORU",
        "OSUN",
      ],
      name: "IJEBU NORTH",
    },
    {
      wards: [
        "ATAN/IMUKU",
        "ERUNWON",
        "IGEDE/ITAMARUN",
        "ILESE",
        "IMEWIRO/ODODEYO/IMOMO",
        "ISOYIN",
        "ODESENLU",
        "ODOSIMADEGUN/ODOSEBORA",
        "OJU ONA",
        "OKE-ERI/OGBOGBO",
      ],
      name: "IJEBU NORTH EAST",
    },
    {
      wards: [
        "IJADE / IMEPE I",
        "IJADE / IMEPE II",
        "IJASI/ IDEPO",
        "ISIWO",
        "ISOKU/OSOSA",
        "ITAMAPAKO",
        "ITANTEBO",
        "ODO-EGBO/OLIWORO",
        "ODO-ESA",
        "POROGUN I",
        "POROGUN II",
      ],
      name: "IJEBU ODE",
    },
    {
      wards: [
        "IKENNE I",
        "IKENNE II",
        "ILISAN I",
        "ILISAN II",
        "ILISAN/IROLU",
        "IPERU I",
        "IPERU II",
        "IPERU III",
        "OGERE I",
        "OGERE II",
      ],
      name: "IKENNE",
    },
    {
      wards: [
        "AFON",
        "IDI AYIN",
        "IDOFA",
        "ILARA/ALAGBE",
        "IMEKO",
        "IWOYE/JABATA",
        "KAJOLA/AGBERIODO",
        "OKE AGBEDE/MORIWI/MATALE",
        "OLORUNDA/GBOMO",
        "OTAPELE",
      ],
      name: "IMEKO/AFON",
    },
    {
      wards: [
        "AGADA",
        "AGOSASA",
        "AJEGUNLE",
        "IDIROKO",
        "IFONYINTEDO",
        "IHUNBO/ ILASE",
        "IJOFIN/IDOSA",
        "IPOKIA I",
        "IPOKIA II",
        "MAUNI I",
        "MAUNI II",
        "TUBE",
      ],
      name: "IPOKIA",
    },
    {
      wards: [
        "AJEBO",
        "AJURA",
        "ALAPAKO-ONI",
        "EGBEDA",
        "KAJOLA",
        "MOKOLOKI",
        "MOLOKO-ASIPA",
        "OBA",
        "OBAFEMI",
        "OFADA",
        "ONIDUNDU",
        "OWODE",
      ],
      name: "OBAFEMI/OWODE",
    },
    {
      wards: [
        "ALABATA",
        "ALAGBAGBA",
        "BALOGUN ITESI",
        "ILUGUN",
        "OBANTOKO",
        "OBETE",
        "ODEDA",
        "OLODO",
        "OPEJI",
        "OSIELE",
      ],
      name: "ODEDA",
    },
    {
      wards: [
        "AIYEPE",
        "ALA/IGBILE",
        "IBEFUN",
        "IDOWA",
        "ILADO",
        "IMODI",
        "IMOSAN",
        "JOBORE/IBIDO/IKISE",
        "ODOGBOLU I",
        "ODOGBOLU II",
        "OGBO/MORAIKA/ITA EPO II",
        "OGBO/MORAIKA/ITA-EPO I",
        "OKUN-OWA",
        "OMU",
        "OSOSA",
      ],
      name: "ODOGBOLU",
    },
    {
      wards: [
        "ABIGI",
        "AYEDE/LOMIRO",
        "AYILA/ITEBU",
        "EFIRE",
        "IBIADE",
        "IWOPIN",
        "LUKOGBE/ILUSIN",
        "MAKUN/IROKUN",
        "ODE-OMI",
        "ONI",
      ],
      name: "OGUN WATER SIDE",
    },
    {
      wards: [
        "AKAKA",
        "AYEGBAMI",
        "IGAN/AJINA",
        "ILARA",
        "IPARA",
        "MOBORODE/OKE-OLA",
        "ODE I",
        "ODE II",
        "ODOFIN/IMAGBO/PETEKUN/DAWARA",
        "ORILE-OKO",
      ],
      name: "REMO NORTH",
    },
    {
      wards: [
        "AGBOWA",
        "AYEGBAMI/IJOKUN",
        "IBIDO/ITUWA/ALARA",
        "IJAGBA",
        "ISOKUN / OYEBAJO",
        "ISOTE",
        "LATAWA",
        "ODE -LEMO",
        "OGIJO/ LIKOSI",
        "OKO/EPE/ITULA I",
        "OKO/EPE/ITULA II",
        "SABO 1",
        "SABO II",
        "SIMAWA / IWELEPE",
        "SURULERE",
      ],
      name: "SAGAMU",
    },
  ],
};

export const OGUN = { states, SR };
