const SR = {
  name: "OYO",
  email: "Oyo@apcaims.com",
  password: "oyo_f%g1",
  phone: "08108850572",
  statecode: "OYO",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "OYO",
  state: "OYO",
  lga: [
    {
      wards: [
        "AKINMORIN/JOBELE",
        "AWE I",
        "AWE II",
        "FIDITI I",
        "FIDITI II",
        "ILORA I",
        "ILORA II",
        "ILORA III",
        "IMINI",
        "IWARE",
      ],
      name: "AFIJIO",
    },
    {
      wards: [
        "AJIBADE/ALABATA/ELEKURU",
        "AKINYELE/ISABIYI/IREPODUN",
        "ARULOGUN/ENIOSA/ARORO",
        "IJAYE/OJEDEJI",
        "IKEREKU",
        "IROKO",
        "IWOKOTO/TALONTAN/IDI-ORO",
        "OJO-EMO/MONIYA",
        "OJOO/AJIBODE/LANIBA",
        "OLANLA/OBODA/LABODE",
        "OLODE/AMOSUN/ONIDUNDU",
        "OLORISA-OKO/OKEGBEMI/MELE",
      ],
      name: "AKINYELE",
    },
    {
      wards: [
        "AGUNPOPO I",
        "AGUNPOPO II",
        "AGUNPOPO III",
        "AREMO",
        "ASHIPA I",
        "ASHIPA II",
        "ASHIPA III",
        "BASHORUN",
        "OKE-AFIN 1",
        "OKE-AFIN II",
      ],
      name: "ATIBA",
    },
    {
      wards: [
        "AGO ARE I",
        "AGO ARE II",
        "ALAGA",
        "BASI",
        "IRAWO ILE",
        "IRAWO OWODE",
        "OFIKI",
        "OWO/AGUNREGE/SABE",
        "TEDE I",
        "TEDE II",
      ],
      name: "ATISBO",
    },
    {
      wards: [
        "AYEDE/ALUGBO/KOLOKO",
        "EGBEDA",
        "ERUNMU",
        "OLODAN/AJINOGBO",
        "OLODE/ALAKIA",
        "OLODO II",
        "OLODO III",
        "OLODO/KUMAPAYI I",
        "OLUBADAN ESTATE",
        "OSEGERE/AWAYE",
        "OWOBAALE/KASUMU",
      ],
      name: "EGBEDA",
    },
    {
      wards: [
        "WARD I N2",
        "WARD II, N3",
        "WARD III, N4",
        "WARD IV, N5A",
        "WARD IX, (N6B PART I)",
        "WARD V, N5B",
        "WARD VI, N6A PART I",
        "WARD VII, N6A PART II",
        "WARD VIII, N6A PART III",
        "WARD X, N6B PART II",
        "WARD XI, NW8",
        "WARD XII, NW8",
      ],
      name: "IBADAN NORTH",
    },
    {
      wards: [
        "III E3",
        "WARD 2 NI (PART II)",
        "WARD I. EI",
        "WARD IV E4",
        "WARD IX E7II",
        "WARD V E5A",
        "WARD VI E5B",
        "WARD VII E6",
        "WARD VIII E7 I",
        "WARD X E8",
        "WARD XI E9 I",
        "WARD XII E9 II",
      ],
      name: "IBADAN NORTH EAST",
    },
    {
      wards: [
        "WARD 08 SW7",
        "WARD 1 C2",
        "WARD 2 SW1",
        "WARD 3 SW2",
        "WARD 4 SW3A & 3B",
        "WARD 5 SW4",
        "WARD 6 SW5",
        "WARD 7 SW6",
        "WARD 9 SW8 (1)",
        "WARD 10 SW8 II",
        "WARD 11 SW9(1)",
        "WARD 12 SW9 II",
      ],
      name: "IBADAN SOUTH WEST",
    },
    {
      wards: [
        "WARD 10 NW7",
        "WARD 11 NW7",
        "WARD 2 NI (PART II)",
        "WARD 3 NW1",
        "WARD 4 NW2",
        "WARD 5 NW3 (PART I)",
        "WARD 6 NW3 (PART I)",
        "WARD 7 NW4",
        "WARD 8 NW5",
        "WARD 9 NW6",
        "WARD I NI (PART I)",
      ],
      name: "IBADAN NORTH-WEST",
    },
    {
      wards: [
        "C1",
        "S S5",
        "S 1",
        "S 2A",
        "S 3",
        "S 4A",
        "S 4B",
        "S 6A",
        "S 7A",
        "S 7B",
        "S. 2B",
        "S. 6B",
      ],
      name: "IBADAN SOUTH-EAST",
    },
    {
      wards: [
        "IBEREKODO I /(PATAOJU)",
        "IBEREKODO/AGBOORO/ITA BAALE",
        "IDERE I (MOLETE)",
        "IDERE II (OMINIGBO/OKE - OBA)",
        "IDERE III (KOSO/APA)",
        "IDOFIN ISAGANUN",
        "IGBOLE/PAKO",
        "ISALE-OBA",
        "OKE-ODO",
        "OKESERIN I & II",
      ],
      name: "IBARAPA CENTRAL",
    },
    {
      wards: [
        "ABORERIN",
        "ANKO",
        "ISABA",
        "ISALE TOGUN",
        "ITABO",
        "NEW ERUWA",
        "OKE -OBA",
        "OKE OTUN",
        "OKE-IMALE",
        "SANGO",
      ],
      name: "IBARAPA EAST",
    },
    {
      wards: [
        "AYETE I",
        "AYETE II",
        "IGANGAN I",
        "IGANGAN II",
        "IGANGAN III",
        "IGANGAN IV",
        "OFIKI I",
        "OFIKI II",
        "TAPA I",
        "TAPA II",
      ],
      name: "IBARAPA NORTH",
    },
    {
      wards: [
        "ABA EMO/ILAJU/ALAKO",
        "AKINWARE/AKINDELE",
        "AKUFO/IDIGBA/ARAROMI",
        "APETE/AYEGUN/AWOTAN",
        "BATAKE/IDI-IYA",
        "ERINWUSI/KOGUO/ODETOLA",
        "FENWA/OGANLA/ELENUSONSO",
        "IDO/ONIKEDE/OKUNA AWO",
        "OGUNDELE/ALAHO/SIBA/IDI-AHUN",
        "OMI ADIO/OMI ONIGBAGBO BAKATARI",
      ],
      name: "IDO",
    },
    {
      wards: [
        "AGORO",
        "AJAGUNNA",
        "ATIPA",
        "IBA I",
        "IBA II",
        "IBA III",
        "IBA IV",
        "IBA V",
        "IKOLABA",
        "LAHA/AJANA",
      ],
      name: "IREPO",
    },
    {
      wards: [
        "ADO-AWAYE",
        "AKINWUMI/OSOOGUN",
        "EKUNLE I",
        "EKUNLE II",
        "FARAMORA",
        "IJEMBA/OKE-OLA/OKE-OJA",
        "ISALU I",
        "ISALU II",
        "KOSO I",
        "KOSO II",
        "LADOGAN/OKE EYIN",
      ],
      name: "ISEYIN",
    },
    {
      wards: [
        "BABAODE",
        "IGBOJAIYE",
        "IPAPO",
        "KOMU",
        "OKAKA I",
        "OKAKA II",
        "OKE-AMU",
        "OTU 1",
        "OTU II",
        "OWODE/IPAPO",
      ],
      name: "ITESIWAJU",
    },
    {
      wards: [
        "AGBAAKIN I",
        "AGBAAKIN II",
        "IWERE-ILE I",
        "IWERE-ILE II",
        "IWERE-ILE III",
        "IWERE-ILE IV",
        "SABI GANA I",
        "SABI GANA II",
        "SABI GANA III",
        "SABI GANA IV",
      ],
      name: "IWAJOWA",
    },
    {
      wards: [
        "AYETORO-OKE I",
        "ELERO",
        "GBELEKALE I & II",
        "IBA-OGAN",
        "IJO",
        "ILAJI OKE/IWERE-OKE",
        "IMOBA/OKE-OGUN",
        "ISEMI-ILE/IMIA/ILUA",
        "ISIA",
        "KAJOLA",
        "OLELE",
      ],
      name: "KAJOLA",
    },
    {
      wards: [
        "AJARA/OPEODU",
        "APATERE/KUFFI/OGUNBODE/OGO",
        "ARULOGUN EHIN/KELEBE",
        "EJIOKU/IGBON/ARIKU",
        "LAGELU MARKET/KAJOLA/GBENA",
        "LAGUN",
        "LALUPON I",
        "LALUPON II",
        "LALUPON III",
        "OFA-IGBO",
        "OGUNJANA/OLOWODE/OGBURO",
        "OGUNREMI/OGUNSINA",
        "OYEDEJI/OLODE/KUTAYI",
        "SAGBE/PABIEKUN",
      ],
      name: "LAGELU",
    },
    {
      wards: [
        "AAJE/OGUNBADO/OKE AGBEDE",
        "ABOGUNDE",
        "AGUODO/ MASIFA",
        "ISALE AFON",
        "ISALE ALAASA",
        "ISALE ORA/SAJA",
        "JAGUN",
        "OKELERIN",
        "OSUPA",
        "SABO/TARA",
      ],
      name: "OGBOMOSO NORTH",
    },
    {
      wards: [
        "AKATA",
        "ALAPATA",
        "AROWOMOLE",
        "IBAPON",
        "IJERU I",
        "IJERU II",
        "ILOGBO",
        "ISOKO",
        "LAGBEDU",
        "OKE-OLA/FARM SETTLEMENT",
      ],
      name: "OGBOMOSO SOUTH",
    },
    {
      wards: [
        "AJAAWA I",
        "AJAAWA II",
        "AYEDE",
        "AYETORO",
        "IDEWURE",
        "LAGBEDU",
        "MOWOLOWO/IWO-ATE",
        "ODO-OBA",
        "OPETE",
        "OTAMOKUN",
      ],
      name: "OGO-OLUWA",
    },
    {
      wards: [
        "ABOKE (ABOYUN OGUN)",
        "ELERUGBA/ELEHINKE/SAGBO (APERU)",
        "IKOLABA/OBADIMO",
        "ONIGBETI I (IYAMOPO)",
        "ONIGBETI II/SAAGBON AGORO (SANTO)",
        "ONIGBETI III & IV (AGBENI)",
        "OPA/OGUNNIYI",
        "SERIKI I & ABOSINO (OKIN)",
        "SERIKI II (AGBELE)",
        "WARO/APATA-ALAJE",
      ],
      name: "OLORUNSOGO",
    },
    {
      wards: [
        "AYEGUN",
        "IDI-IROKO/IKEREKU",
        "IDI-OSAN/EGBEDA-ATUBA",
        "MUSLIM/OGBERE",
        "ODO-ONA NLA",
        "OKANHINDE/LATUNDE",
        "OLOMI/OLUNDE",
        "OLONDE/ABA-NLA",
        "ONIPE",
        "ORISUNBARE/OJO-EKUN",
      ],
      name: "OLUYOLE",
    },
    {
      wards: [
        "AKANRAN/OLORUNDA",
        "ARAROMI/APERIN",
        "BADEKU",
        "GBADA EFON",
        "ODI ODEYALE/ODI APERIN",
        "OGBERE",
        "OGBERE TIOYA",
        "OJOKU/AJIA",
        "OLODE/GBEDUN/OJEBODE",
        "OLORUNSOGO",
        "OREMEJI/AGUGU",
      ],
      name: "ONA-ARA",
    },
    {
      wards: [
        "AARE",
        "ALEPATA",
        "BONNI",
        "IGBOPE/IYEYE I",
        "IGBOPE/IYEYE II",
        "IGI ISUBU",
        "ONIBODE I",
        "ONIBODE II",
        "ONIBODE III",
        "ONIGBOHO/ALOMO/OKERE",
      ],
      name: "OORELOPE",
    },
    {
      wards: [
        "ORI IRE I",
        "ORI IRE II",
        "ORI IRE III",
        "ORI IRE IV",
        "ORI IRE IX",
        "ORI IRE V",
        "ORI IRE VI",
        "ORI IRE VII",
        "ORI IRE VIII",
        "ORI IRE X",
      ],
      name: "ORI IRE",
    },
    {
      wards: [
        "AGBOYE/MOLETE",
        "AJAGBA",
        "ALAODI/MODEKE",
        "APAARA",
        "APINNI",
        "BALOGUN",
        "JABATA",
        "OKE APO",
        "OLUAJO",
        "OWODE/ARAROMI",
      ],
      name: "OYO EAST",
    },
    {
      wards: [
        "AJOKIDERO/AKEWUGBERU",
        "AKEETAN",
        "FASOLA/SOKU",
        "ISEKE",
        "ISOKUN",
        "IYAJI",
        "OJONGBODU",
        "OPAPA",
        "OWODE",
        "PAKOYI/IDODE",
      ],
      name: "OYO WEST",
    },
    {
      wards: [
        "AGBONLE",
        "AGO AMODU I",
        "AGO AMODU II",
        "OGBOORO I",
        "OGBOORO II",
        "OJE OWODE I",
        "OJE OWODE II",
        "SEPETERI I",
        "SEPETERI II",
        "SEPETERI III",
        "SEPETERI IV",
      ],
      name: "SAKI EAST",
    },
    {
      wards: [
        "AGANMU/KOOKO",
        "AJEGUNLE",
        "BAGII",
        "EKOKAN-MUA",
        "IYA",
        "OGIDIGBO/KINNIKINNI",
        "OKE-ORO",
        "OKERE I",
        "OKERE II",
        "SANGOTE/BOODA/BAABO/ILUS",
        "SEPETERI/BAPON",
      ],
      name: "SAKI WEST",
    },
    {
      wards: [
        "BAYA-OJE",
        "IGBON/GAMBARI",
        "IRESAADU I (IRESAAPA)",
        "IRESAADU II (AROLU)",
        "IRESAADU III (IRESAADU)",
        "IRESAADU IV (IREGBA)",
        "IWOFIN",
        "OKO I (OKO",
        "OKO II (ILAJUE)",
        "OKO III (MAYIN)",
      ],
      name: "SURULERE",
    },
  ],
};

export const OYO = { states, SR };
