const SR = {
  name: "PLATEAU",
  email: "Plateau@apcaims.com",
  password: "plateau_krt7",
  phone: "08108850572",
  statecode: "PLATEAU",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "PLATEAU",
  state: "PLATEAU",
  lga: [
    {
      wards: [
        "BARAKIN LADI",
        "GASSA/SHO",
        "GINDIN AKWATI",
        "HEIPANG",
        "KAPWIS",
        "KURRA FALLS",
        "LOBIRING",
        "MARIT/MAZAT",
        "RAFAN",
        "TAFAN",
        "ZABOT",
      ],
      name: "BARIKIN LADI",
    },
    {
      wards: [
        "BUHIT",
        "BUJI",
        "GABIA",
        "GURUM",
        "JENGRE",
        "KADAMO",
        "KAKKEK",
        "KASURU",
        "KIMAKPA",
        "KISHIKA",
        "MAFARA",
        "RIMI",
        "TA'AGBE",
        "TAHU",
        "ZABOLO",
        "ZOBWO",
      ],
      name: "BASSA",
    },
    {
      wards: [
        "BOKKOS",
        "BUTURA",
        "DAFFO",
        "DAMWAI",
        "KWATAS",
        "MANGOR",
        "MANGUNA",
        "MBAR/MANGAR",
        "MUSHERE WEST",
        "MUSHERE CENTRAL",
        "RICHA",
        "SHA",
        "TANGUR",
        "TOFF",
      ],
      name: "BOKKOS",
    },
    {
      wards: [
        "FEDERE",
        "FOBUR 'B'",
        "FOBUR 'A'",
        "FURSUM",
        "JARAWAN KOGI",
        "MAI GEMU",
        "MAIJUJU",
        "SHERE EAST",
        "SHERE WEST",
        "ZANDI",
      ],
      name: "JOS EAST",
    },
    {
      wards: [
        "ABBA NA SHEHU",
        "ALI KAZAURE",
        "GANGARE",
        "GARBA DAHO",
        "IBRAHIM KATSINA",
        "JENTA ADAMU",
        "JENTA APATA",
        "JOS JARAWA",
        "NARAGUTA 'A'",
        "NARAGUTA 'B'",
        "SARKIN ARAB",
        "TAFAWA BALEWA",
        "TUDUN WADA - KABONG",
        "VANDERPUYE",
      ],
      name: "JOS NORTH",
    },
    {
      wards: [
        "BUKURU",
        "DU",
        "GIRING",
        "GYEL 'A'",
        "GYEL 'B'",
        "KURU 'A'",
        "KURU 'B'",
        "SHEN",
        "TURU",
        "VWANG",
        "ZAWAN 'A'",
        "ZAWAN 'B'",
      ],
      name: "JOS SOUTH",
    },
    {
      wards: [
        "BIRBYANG",
        "DENGI",
        "DUGUB",
        "GAGDIB",
        "GARGA",
        "GUMSHER",
        "GWAMLAR",
        "JARMAI",
        "JOM",
        "KANAM",
        "KANTANA",
        "KUNKYAM",
        "MUNBUTBO",
        "NAMARAN",
      ],
      name: "KANAM",
    },
    {
      wards: [
        "AMPANG-EAST",
        "AMPER CHIKA 'A'",
        "AMPER CHIKA 'B'",
        "AMPER SERI",
        "DAWAKI",
        "GARRAM",
        "KABWIR PADA",
        "KABWIR/GYANGYANG",
        "LANGSHI",
        "NEMEL",
      ],
      name: "KANKE",
    },
    {
      wards: [
        "FUNYALANG",
        "JAT",
        "KELLER",
        "KUFFEN",
        "KWALLAK",
        "KWANDE",
        "LIPCHOK",
        "MBAN/ZAMKO",
        "NYER",
        "PAJAT",
        "PIL GANI",
        "PISHE/YASHI",
        "REAK",
        "WAROH",
      ],
      name: "LANGTANG NORTH",
    },
    {
      wards: [
        "DADIN KOWA",
        "FAJUL",
        "GAMAKAI",
        "LASHEL",
        "MABUDI",
        "MAGAMA",
        "SABON GIDA",
        "TALGWANG",
        "TIMBOL",
        "TURAKI",
      ],
      name: "LANGTANG SOUTH",
    },
    {
      wards: [
        "AMPANG WEST",
        "CHANSO",
        "GINDIRI 1",
        "GINDIRI 11",
        "JANNARET",
        "JIPAL/CHAKFEM",
        "KADUNU",
        "KERANG",
        "KOMBUN",
        "LANGAI",
        "MANGU 1",
        "MANGU 11",
        "MANGU HALLE",
        "MANGUN",
        "PAN YAM",
        "PUSHIT",
      ],
      name: "MANGU",
    },
    {
      wards: [
        "BALTEP",
        "GARKAWA CENTRAL",
        "GARKAWA NORTH",
        "GARKAWA NORTH EAST",
        "KOENOEM 'A'",
        "KOENOEM 'B'",
        "LALIN",
        "PIAPUNG 'A'",
        "PIAPUNG 'B'",
        "TUNKUS",
      ],
      name: "MIKANG",
    },
    {
      wards: [
        "CHIP",
        "DOK-PAI",
        "FIER",
        "JIBLIK",
        "KADUNG",
        "KANGSHU",
        "LANKANG",
        "PANKSHIN CHIGWONG",
        "PANKSHIN SOUTH (BELNING)",
        "PANKSHIN CENTRAL",
        "TAL",
        "WOKKOS",
      ],
      name: "PANKSHIN",
    },
    {
      wards: [
        "BWALL",
        "DOEMAK-GOECHIM",
        "DOEMAK-KOPLONG",
        "DOKAN KASUWA",
        "KURGWI",
        "KWA",
        "KWALLA MOEDA",
        "KWALLA YITLA'AR",
        "KWANDE",
        "KWANG",
        "NAMU",
      ],
      name: "QUA'AN PAN",
    },
    {
      wards: [
        "ATTAKAR",
        "BUM",
        "DANTO",
        "JOL/KWI",
        "RA-HOSS",
        "RIM",
        "RIYOM",
        "SHARUBUTU",
        "SOPP",
        "TA-HOSS",
      ],
      name: "RIYOM",
    },
    {
      wards: [
        "DERTENG",
        "KALONG",
        "KURUNGBAU (A)",
        "KURUNGBAU (B)",
        "MOEKAT",
        "PANGSHOM",
        "POESHIP",
        "SHENDAM CENTRAL (A)",
        "SHENDAM CENTRAL (B)",
        "SHIMANKAR",
        "YELWA",
      ],
      name: "SHENDAM",
    },
    {
      wards: [
        "BASHAR",
        "DANBIRAM",
        "GUDUS",
        "KADARKO",
        "KUMBONG",
        "KUMBUR",
        "KUYAMBANA",
        "MAVO",
        "NYALUM/KAMPANI",
        "SALUWE",
        "WASE TOFA",
        "YOLA WAKAT",
      ],
      name: "WASE",
    },
  ],
};

export const PLATEAU = { states, SR };
