const SR = {
  name: "SOKOTO",
  email: "Sokoto@apcaims.com",
  password: "sokoto_ww56",
  phone: "08108850572",
  statecode: "SOKOTO",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "SOKOTO",
  state: "SOKOTO",
  lga: [
    {
      wards: [
        "BINJI",
        "BUNKARI",
        "GAWAZZAI",
        "INNAME",
        "JAMMALI",
        "MAIKULKI",
        "SAMAMA",
        "SORO GABAS",
        "SORO YAMMA",
        "T/KOSE",
      ],
      name: "BINJI",
    },
    {
      wards: [
        "BADAU/DARHELA",
        "BAGARAWA",
        "BANGI/DABAGA",
        "BODINGA/TAUMA",
        "DANCHADI",
        "DINGYADI/BADAWA",
        "KWACCIYAR LALLE",
        "MAZAN GARI/JIRGA MIYO",
        "SIFAWA/LUKUYAWA",
        "TAKATUKU/MADORAWA",
        "TULLUWA/KULAFASA",
      ],
      name: "BODINGA",
    },
    {
      wards: [
        "BODAI/JURGA",
        "DANGE",
        "FAJALDU",
        "GIERE/GAJARA",
        "RIKINA",
        "RUDU/AMANAWA",
        "RUGGAR GIDADO",
        "SHUNI",
        "TSAFANADE",
        "TUNTUBE/TSEHE",
        "WABABE/SALAU",
      ],
      name: "DANGE/SHUNI",
    },
    {
      wards: [
        "DUKAMAJE/ILAH",
        "GADA",
        "GILBADI",
        "KADADIN BUDA (KADDI)",
        "KADASSAKA",
        "KADDI",
        "KAFFE",
        "KIRI",
        "KWARMA",
        "KYADAWA/HOLAI",
        "TSITSE",
      ],
      name: "GADA",
    },
    {
      wards: [
        "BIRJINGO",
        "BOYEKAI",
        "GIYAWA",
        "GORONYO",
        "KAGARA",
        "KOJIYO",
        "KWAKWAZO",
        "RIMAWA",
        "S/GARI DOLE/DAN/TASAKKO",
        "SHINAKA",
        "TAKAKUME",
      ],
      name: "GORONYO",
    },
    {
      wards: [
        "AWULKITI",
        "BACHAKA",
        "BALLE",
        "CHILAS/MAKUYA",
        "GWAZANGE/BOTO",
        "KARFEN CHANA",
        "KARFEN SARKI",
        "KURDULA",
        "MARAKEN BORI",
        "TULUN DOYA",
      ],
      name: "GUDU",
    },
    {
      wards: [
        "ASARA AREWA",
        "ASARA KUDU",
        "ATAKWANYO",
        "CHIMMOLA/KUDU",
        "CHIMOLA AREWA",
        "GIDAN KAYA",
        "GIGANE",
        "GWADABAWA",
        "HUCHI",
        "MAMMANDE",
        "SALAME",
      ],
      name: "GWADABAWA",
    },
    {
      wards: [
        "ARABA",
        "DAMBA",
        "DARNA/ SABON GARI",
        "DARNE/ TSOLAWO",
        "G/ HAMMA",
        "G/ KATTA",
        "GARU",
        "ILLELA",
        "KALMALO",
        "R. GATI",
        "TOZAI",
      ],
      name: "ILLELA",
    },
    {
      wards: [
        "BARGAJA",
        "GEBE 'A'",
        "GEBE 'B'",
        "ISA NORTH",
        "ISA SOUTH",
        "TIDIBALE",
        "TOZAI",
        "TSABREN SARKIN DARAI",
        "TURBA",
        "YANFAKO",
      ],
      name: "ISA",
    },
    {
      wards: [
        "FAKKU",
        "GIRKAU",
        "KEBBE EAST",
        "KEBBE WEST",
        "KUCHI",
        "MARGAI - A",
        "MARGAI - B",
        "NASAGUDU",
        "SANGI",
        "UNGUSHI",
      ],
      name: "KEBBE",
    },
    {
      wards: [
        "BANKANU/ R, KADE",
        "BASANSAN",
        "DURBAWA",
        "G. RUGGA",
        "G/ MODIBBO/ G. AKWARA",
        "H/ ALI/ MARABAWA",
        "KABANGA",
        "KWARE",
        "S/BIRNI/ G. KARMA",
        "TSAKI/ WALAKE'E",
        "TUNGA/ MALLAMAWA",
      ],
      name: "KWARE",
    },
    {
      wards: [
        "GANDI 'A'",
        "GANDI 'B'",
        "GAWAKUKE",
        "GWADDODI/GIDAN BU WAI",
        "KURYA",
        "RABAH",
        "RARA",
        "RIJI/MAIKUJERA",
        "TSAMIYA",
        "TURSA",
        "YAR TSAKUWA",
      ],
      name: "RABAH",
    },
    {
      wards: [
        "GANGARA",
        "GATAWA",
        "KALGO",
        "KURUWA",
        "LAJINGE",
        "MAKUWANA",
        "S/BIRNI EAST",
        "S/BIRNI WEST",
        "TARA",
        "TSAMAYE",
        "UNGUWAR LALLE",
      ],
      name: "S/BIRNI",
    },
    {
      wards: [
        "DANDIN MAHE",
        "GANGAM",
        "HORO BIRNI",
        "JAREDI",
        "KAJIJI",
        "KAMBAMA",
        "LAMBARA",
        "MANDERA",
        "SANYINNAWAL",
        "SHAGARI",
      ],
      name: "SHAGARI",
    },
    {
      wards: [
        "GANDE EAST",
        "GANDE WEST",
        "KATAMI NORTH",
        "KATAMI SOUTH",
        "KUBODU NORTH",
        "KUBODU SOUTH",
        "LABANI",
        "MARAFA EAST",
        "MARAFA WEST",
        "SILAME",
      ],
      name: "SILAME",
    },
    {
      wards: [
        "MAGAJIN GARI 'A'",
        "MAGAJIN GARI B",
        "MAGAJIN RAFI 'A'",
        "MAGAJIN RAFI 'B'",
        "S/ADAR GANDU",
        "S/ADAR/G/IGWAI",
        "S/MUSULMI 'A'",
        "S/MUSULMI 'B'",
        "WAZIRI 'A'",
        "WAZIRI 'B'",
        "WAZIRI 'C'",
      ],
      name: "SOKOTO NORTH",
    },
    {
      wards: [
        "GAGI 'A'",
        "GAGI 'B'",
        "GAGI 'C'",
        "R/DOROWA 'A'",
        "R/DOROWA 'B'",
        "S/A/K/ATIKU",
        "S/ZAMFARA 'A'",
        "S/ZAMFARA 'B'",
        "SARKIN ADAR KWANNI",
        "T/WADA 'A'",
        "T/WADA 'B'",
      ],
      name: "SOKOTO SOUTH",
    },
    {
      wards: [
        "BAGIDA/LUKKINGO",
        "BAKAYA/SABON BIRNI",
        "BARKEJI/NABAGUDA",
        "BASHIRE/MAIKADA",
        "DOGONDAJI/SALA",
        "FAGA/ALASAN",
        "JABO/KAGARA",
        "ROMON SARKI",
        "SAIDA/GOSHE",
        "SANYINNA",
        "TAMBUWAL/SHINFIRI",
      ],
      name: "TAMBUWAL",
    },
    {
      wards: [
        "GIDAN MADI",
        "KALANJENI",
        "KWACCE-HURU",
        "MAGONHO",
        "RAKA",
        "RUWA-WURI",
        "SAKKWAI",
        "SALEWA",
        "SUTTI",
        "TANGAZA",
      ],
      name: "TANGAZA",
    },
    {
      wards: [
        "BARAYAR GIWA",
        "DUMA",
        "FURA GIRKE",
        "GIDAN KARE/BIMASA",
        "KURUWA",
        "KWARARE",
        "LAMBAR TURETA",
        "LOFA",
        "TSAMIYA",
        "TURETA GARI",
      ],
      name: "TURETA",
    },
    {
      wards: [
        "ARKILLA",
        "BADO/KASARAWA",
        "DUNDAYE/GUMBURAWA",
        "G/BUBU/G/YARO",
        "G/HAMIDU/G/KAYA",
        "GUMBI/WAJAKE",
        "GWAMATSE",
        "K/KIMBA/GEDEWA",
        "KALAMBAINA/GIRABSHI",
        "KAMMATA",
        "WAMAKKO",
      ],
      name: "WAMAKKO",
    },
    {
      wards: [
        "ACHIDA",
        "ALKAMMU/GYELGYEL",
        "CHACHO/MARNONA",
        "DANKEMU",
        "DIMBISO",
        "DINAWA",
        "KWARGABA",
        "KWASARE/SISAWA",
        "LAHODU/G/BANGO",
        "MAGARYA",
        "MARAFA",
      ],
      name: "WURNO",
    },
    {
      wards: [
        "BAKALE",
        "BINGAJE",
        "BINJI",
        "BIRNIRUWA",
        "FAKKA",
        "KILGORI",
        "RUGGAR IYA",
        "TORANKAWA",
        "YABO 'A'",
        "YABO 'B'",
      ],
      name: "YABO",
    },
  ],
};

export const SOKOTO = { states, SR };
