const SR = {
  name: "TARABA",
  email: "Taraba@apcaims.com",
  password: "taraba_m88v",
  phone: "08108850572",
  statecode: "TARABA",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "TARABA",
  state: "TARABA",
  lga: [
    {
      wards: [
        "ALIM GORA",
        "ARDO KOLA",
        "IWARE",
        "JAURO YINU",
        "LAMIDO BORNO",
        "MAYO RANEWO",
        "SARKIN DUTSE",
        "SUNKANI",
        "TAU",
        "ZONGON KOMBI",
      ],
      name: "ARDO - KOLA",
    },
    {
      wards: [
        "BADAKOSHI",
        "BALI  A",
        "BALI B",
        "GANG DOLE",
        "GANG MATA",
        "GANGLARI",
        "GANGTIBA",
        "KAIGAMA",
        "MAIHULA",
        "SUNTAI",
        "TAKALAFIYA",
      ],
      name: "BALI",
    },
    {
      wards: [
        "AKATE",
        "ASIBITI",
        "BIKADARKO",
        "FADA",
        "GAYAMA",
        "GINDIN DUTSE",
        "GYATTA AURE",
        "MARARRABA",
        "NYITA",
        "SUNTAI",
      ],
      name: "DONGA",
    },
    {
      wards: [
        "GALUMJINA",
        "GANGUMI",
        "GARBABI",
        "GASHAKA",
        "GAYAM",
        "JAMTARI",
        "MAI-IDANU",
        "MAYO SELBE",
        "SERTI 'A'",
        "SERTI 'B'",
      ],
      name: "GASHAKA",
    },
    {
      wards: [
        "GASSOL",
        "GUNDUMA",
        "MUTUM BIYU I",
        "MUTUM BIYU II",
        "NAM NAI",
        "SABON GIDA",
        "SARKIN SHIRA",
        "SENDIRDE",
        "TUTARE",
        "WUROJAM",
        "WURYO",
        "YARIMA",
      ],
      name: "GASSOL",
    },
    {
      wards: [
        "DAMPAR I",
        "DAMPAR II",
        "DAMPAR III",
        "IBI NWONYO I",
        "IBI NWONYO II",
        "IBI RIMI UKU I",
        "IBI RIMI UKU II",
        "SARKIN KUDU I",
        "SARKIN KUDU II",
        "SARKIN KUDU III",
      ],
      name: "IBI",
    },
    {
      wards: [
        "ABBARE YELWA",
        "BARADE",
        "KACHALLA SEMBE",
        "KONA",
        "MAJIDADI",
        "MAYO GOI",
        "SARKIN DAWAKI",
        "SINTALI",
        "TURAKI 'A'",
        "TURAKI 'B'",
      ],
      name: "JALINGO",
    },
    {
      wards: [
        "AMAR",
        "ANDAMIN",
        "BACHAMA",
        "BIKWIN",
        "DAROFAI",
        "DIDANGO",
        "JEN ARDIDO",
        "JEN KAIGAMA",
        "KARIM 'A'",
        "KARIM 'B'",
        "KWANCHI",
      ],
      name: "KARIM-LAMIDO",
    },
    {
      wards: [
        "ABONG",
        "AKWENTO/BOKO",
        "ASHUKU/ENEME",
        "BAISSA",
        "BENTE/GALEA",
        "BISSAULA",
        "DIDAN",
        "NDAFORO/GEANDA",
        "NJUWANDE",
        "NYIDO/TOSSO",
      ],
      name: "KURMI",
    },
    {
      wards: [
        "ABBARE I",
        "ABBERE II",
        "DONADDA",
        "GARIN DOGO",
        "GARIN MAGAJI",
        "JIMLARI",
        "KUNINI",
        "LAU I",
        "LAU II",
        "MAYO LOPE",
      ],
      name: "LAU",
    },
    {
      wards: [
        "GEMBU 'A'",
        "GEMBU 'B'",
        "KABRI",
        "KAKARA",
        "MAGU",
        "MAYO-NDAGA",
        "MBAMNGA",
        "NDUM-YAJI",
        "NGUROJE",
        "TITONG",
        "WARWAR",
      ],
      name: "SARDAUNA",
    },
    {
      wards: [
        "BETE",
        "BIKASHIBILA",
        "CHANCHANJI",
        "DUTSE",
        "FETE",
        "GAHWETON",
        "MANYA",
        "ROGO",
        "SHIBONG",
        "TIKARI",
        "YUKUBEN",
      ],
      name: "TAKUM",
    },
    {
      wards: [
        "FIKYU",
        "KPAMBO",
        "KPAMBO PURI",
        "KWESATI",
        "LISSAM I",
        "LISSAM II",
        "LUMBU",
        "RUFU",
        "DIKA",
        "JENUWA",
        "KWAMBIA",
      ],
      name: "USSA",
    },
    {
      wards: [
        "AKWANA",
        "AVYI",
        "BANTAJE",
        "CHONKU",
        "HOSPITAL",
        "JIBU",
        "KENTE",
        "PUJE",
        "RAFIN KADA",
        "TSOKUNDI",
      ],
      name: "WUKARI",
    },
    {
      wards: [
        "BIKASSA I",
        "BIKASSA II",
        "NYAJA I",
        "NYAJA II",
        "PANTISAWA I",
        "PANTISAWA II",
        "PUPULE I",
        "PUPULE II",
        "PUPULE III",
        "SUMBU I",
        "SUMBU II",
      ],
      name: "YORRO",
    },
    {
      wards: [
        "BITAKO",
        "BUBONG",
        "DINDING",
        "LAMMA",
        "MONKIN A",
        "MONKIN B",
        "YAKOKO",
        "ZING AI",
        "ZING AII",
        "ZING B",
      ],
      name: "ZING",
    },
  ],
};

export const TARABA = { states, SR };
