const SR = {
  name: "ZAMFARA",
  email: "Zamfara@apcaims.com",
  password: "zamfara_3dk0",
  phone: "08108850572",
  statecode: "ZAMFARA",
  img: "images/profile2.jpg",
  userType: "STATEREP",
};

const states = {
  statecode: "ZAMFARA",
  state: "ZAMFARA",
  lga: [
    {
      wards: [
        "BAGEGA",
        "BARAYAR-ZAKI",
        "DAN GALADIMA",
        "GALADIMA",
        "MAGAJI",
        "MATSERI",
        "SABON BIRINI",
        "WARAMU",
        "WUYA",
        "YAR'SABAYA",
      ],
      name: "ANKA",
    },
    {
      wards: [
        "BAKURA",
        "BIRNIN TUDU",
        "DAKKO",
        "DAMRI",
        "DAN MANAU",
        "DANKADU",
        "NASARAWA",
        "RINI",
        "YAR GEDA",
        "YAR KUFOJI",
      ],
      name: "BAKURA",
    },
    {
      wards: [
        "BIRNIN MAGAJI",
        "DANFAMI SABON BIRINI",
        "GORA",
        "GUSAMI GARI",
        "GUSAMI HAYI",
        "KIYAWA",
        "MODOMAWA EAST",
        "MODOMAWA WEST",
        "NASARAWA GODAL EAST",
        "NASARAWA GODAL WEST",
      ],
      name: "BIRNIN MAGAJI",
    },
    {
      wards: [
        "ADABKA",
        "BUKKUYUM",
        "GWASHI",
        "KYARAM",
        "MASAMA",
        "NASARAWA",
        "RUWAN JEMA",
        "YASHI",
        "ZARUMMAI",
        "ZAUMA",
      ],
      name: "BUKKUYUM",
    },
    {
      wards: [
        "BINGI NORTH",
        "BINGI SOUTH",
        "BUNGUDU",
        "FURFURI/KWAI-KWAI",
        "GADA / KARAKKAI",
        "KWATARKWASHI",
        "NAHUCE",
        "RAWAYYA/ BELA",
        "SAMAWA",
        "SANKALAWA",
        "TOFA",
      ],
      name: "BUNGUDU",
    },
    {
      wards: [
        "BARDOKI",
        "BIRNIN MAGAJI",
        "BIRNIN TUDU",
        "FALALE",
        "FELFELDU / GAMO",
        "GAYARI",
        "GYALANGE",
        "ILLELAR AWAL",
        "MAGAJIN GARI",
        "SHIYAR RAFI",
        "UBANDAWAKI",
      ],
      name: "GUMMI",
    },
    {
      wards: [
        "GALADIMA",
        "MADA",
        "MADAWAKI",
        "MAGAMI",
        "MAYANA",
        "RIJIYA",
        "RUWAN BORE",
        "SABON GARI",
        "TUDUN WADA",
        "WANKE",
        "WONAKA",
      ],
      name: "GUSAU",
    },
    {
      wards: [
        "BANGA",
        "DAN - ISA",
        "GABAKE",
        "GALADIMA DAN GALADIMA",
        "KAGARA",
        "KUNGURKI",
        "KURYA MADARO",
        "KYAM BARAWA",
        "S/BAURA/S/MAFARA",
        "SAKAJIKI",
        "YANKABA",
      ],
      name: "KAURA NAMODA",
    },
    {
      wards: [
        "BIRNIN KAYA / DOSARA",
        "DAMAGA / DAMAGIWA",
        "FARU / MAGAMI",
        "GIDAN GOGA",
        "GORA",
        "JANBAKO",
        "KAYA",
        "MARADUN NORTH",
        "MARADUN SOUTH",
        "TSIBIRI",
      ],
      name: "MARADUN",
    },
    {
      wards: [
        "BINDIN",
        "BINGI",
        "DAN GULBI",
        "DAN KURMI",
        "DAN SADAU",
        "KANOMA",
        "KUYAN BANA",
        "MARU",
        "MAYANCHI",
        "RUWAN DORAWA",
      ],
      name: "MARU",
    },
    {
      wards: [
        "BADARAWA",
        "CHIKI",
        "GALADI",
        "JANGERU",
        "KATURU",
        "KURYA",
        "KWARE",
        "SHANAWA",
        "SHINKAFI NORTH",
        "SHINKAFI SOUTH",
      ],
      name: "SHINKAFI",
    },
    {
      wards: [
        "GARBADU",
        "GWARAM",
        "JANGEBE",
        "KAGARA",
        "MORAI",
        "RUWAN BORE",
        "RUWAN GIZO",
        "SAUNA R/ GORA",
        "SHIYAR GALADIMA",
        "SHIYAR KAYAYE/MATUSGI",
        "TAKE TSABA/MAKERA",
      ],
      name: "TALATA MAFARA",
    },
    {
      wards: [
        "BILBIS",
        "CHEDIYA",
        "DANJIBGA/KUNCHIN - KALGO",
        "DAUKI",
        "KETA/KIZARA",
        "KWAREN GANUWA",
        "TSAFE",
        "YAN KUZO 'B'",
        "YAN WAREN DAJI",
        "YANDOTON DAJI",
        "YANKUZO 'A'",
      ],
      name: "TSAFE",
    },
    {
      wards: [
        "BOKO",
        "DAURAN / BIRNIN-TSABA",
        "DOLE",
        "GALADIMA/YANRUWA",
        "KANWA",
        "KUTURU/MAYASA",
        "KWASHBAWA",
        "MASHEM",
        "RUKUDAWA",
        "YAN BUKI/ DUTSI",
        "ZURMI",
      ],
      name: "ZURMI",
    },
  ],
};

export const ZAMFARA = { states, SR };
